In [48]:
import pandas as pd

In [82]:
chemicals = pd.read_csv("data/chemical_names_cleaned_2_18.csv")

In [83]:
chemicals.head()

,original_ingredient,cas_number,clean_name,api_rn,api_name
0,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania
1,CITRONELLOL,NaN,CITRONELLOL,106-22-9,Citronellol
2,LINALOOL,NaN,LINALOOL,78-70-6,(¬±)-Linalool
3,HEXYL CINNAMAL,NaN,HEXYL CINNAMAL,101-86-0,Œ±-Hexylcinnamaldehyde
4,Limonene (1-methyl-4-prop-1-en-2-yl-cyclohexen...,5989-27-5,Limonene (1-methyl-4-prop-1-en-2-yl-cyclohexen...,5989-27-5,(+)-Limonene

In [89]:
chemicals = chemicals.rename(columns = {"original_ingredient": 'Ingredient Name'})

In [90]:
chemicals.head()

,Ingredient Name,cas_number,clean_name,api_rn,api_name
0,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania
1,CITRONELLOL,NaN,CITRONELLOL,106-22-9,Citronellol
2,LINALOOL,NaN,LINALOOL,78-70-6,(¬±)-Linalool
3,HEXYL CINNAMAL,NaN,HEXYL CINNAMAL,101-86-0,Œ±-Hexylcinnamaldehyde
4,Limonene (1-methyl-4-prop-1-en-2-yl-cyclohexen...,5989-27-5,Limonene (1-methyl-4-prop-1-en-2-yl-cyclohexen...,5989-27-5,(+)-Limonene

In [87]:
len(chemicals)

496

In [84]:
all_data = pd.read_csv("data/CDPH Search results - 1_12_2026, 3_34_15 PM.csv")

In [88]:
all_data.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,Concentration,Ingredient Submitted Date,Ingredient Removed Date
0,18358,Nail Alliance - Entity,Entity Nudite,Cool Pink Nail Sculpting Powder,NaN,NaN,6/24/2019,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,5.000000,6/24/2019,NaN
1,38661,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,40.000000,9/21/2015,NaN
2,38662,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Sprinkle,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,31.000000,9/21/2015,NaN
3,38667,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,12.000000,9/21/2015,NaN
4,38665,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,21.500000,9/21/2015,NaN

In [86]:
len(all_data)

534508

In [91]:
first_merge = all_data.merge(chemicals, on = "Ingredient Name", how = 'left')

In [93]:
first_merge.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,Concentration,Ingredient Submitted Date,Ingredient Removed Date,cas_number,clean_name,api_rn,api_name
0,18358,Nail Alliance - Entity,Entity Nudite,Cool Pink Nail Sculpting Powder,NaN,NaN,6/24/2019,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,5.000000,6/24/2019,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania
1,38661,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,40.000000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania
2,38662,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Sprinkle,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,31.000000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania
3,38667,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,12.000000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania
4,38665,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,21.500000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania

In [94]:
first_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 534508 entries, 0 to 534507
Data columns (total 17 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Product Id                 534508 non-null  int64
 1   Company                    534508 non-null  object
 2   Brand                      534308 non-null  object
 3   Product Name               534508 non-null  object
 4   Variant                    187813 non-null  object
 5   Product Discontinued Date  39102 non-null   object
 6   Product Submitted Date     534508 non-null  object
 7   Ingredient Name            534186 non-null  object
 8   Function                   433384 non-null  object
 9   Unit of Measure            222747 non-null  object
 10  Concentration              224495 non-null  object
 11  Ingredient Submitted Date  534186 non-null  object
 12  Ingredient Removed Date    6627 non-null    object
 13  cas_number                 444736 non-null  object
 14  clean_name                 531353 non-null  object
 15  api_rn                     529527 non-null  object
 16  api_name                   531353 non-null  object
dtypes: int64(1), object(16)
memory usage: 69.3+ MB

In [99]:
na = first_merge[first_merge["api_name"].isna()]
na.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,Concentration,Ingredient Submitted Date,Ingredient Removed Date,cas_number,clean_name,api_rn,api_name
896,115795,Davines S.p.A.,[comfort zone],[comfort zone] - AROMASOUL INDIAN blend,NaN,NaN,9/8/2022,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,Fragrance,NaN,NaN,10/10/2024,NaN,NaN,NaN,NaN,NaN
1217,135693,Davines S.p.A.,[comfort zone],[comfort zone] - TRANQUILLITYTM eau de toilette,NaN,NaN,5/30/2024,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,Fragrance,NaN,NaN,3/20/2024,NaN,NaN,NaN,NaN,NaN
1271,170020,Davines S.p.A.,[comfort zone],[comfort zone] – BODY STRATEGIST collagen cream,NaN,NaN,11/19/2025,"[3R-(3a,3aß,7ß,8aa)]-1-(2,3,4,7,8,8a-hexahydro...",Fragrance,NaN,NaN,11/17/2025,NaN,NaN,NaN,NaN,NaN
1287,170233,Davines S.p.A.,[comfort zone],[comfort zone] – BODY STRATEGIST collagen rich...,NaN,NaN,11/19/2025,"[3R-(3a,3aß,7ß,8aa)]-1-(2,3,4,7,8,8a-hexahydro...",Fragrance,NaN,NaN,11/19/2025,NaN,NaN,NaN,NaN,NaN
1291,170237,Davines S.p.A.,[comfort zone],[comfort zone] – BODY STRATEGIST detox algae m...,NaN,NaN,11/19/2025,"[3R-(3a,3aß,7ß,8aa)]-1-(2,3,4,7,8,8a-hexahydro...",Fragrance,NaN,NaN,11/19/2025,NaN,NaN,NaN,NaN,NaN

In [101]:
na_ingredients = na["Ingredient Name"].unique()

In [108]:
na_names = pd.DataFrame(na_ingredients)

In [109]:
na_names.to_csv("na_names.csv")

In [111]:
na_names_cleaned = pd.read_csv("data/na_names_cleaned.csv")

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 1687: invalid continuation byte

In [49]:
harms = pd.read_csv("reportable_ingredients.csv")

In [50]:
harms.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3324 entries, 0 to 3323
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Chemical Name                 3324 non-null   object
 1   CAS RN                        3049 non-null   object
 2   Synonyms                      571 non-null    object
 3   Hazard Traits                 3324 non-null   object
 4   Authoritative List            3324 non-null   object
 5   When to Report (Any, FF, FA)  3324 non-null   object
 6   Unnamed: 6                    1 non-null      object
dtypes: object(7)
memory usage: 181.9+ KB

In [51]:
ings = pd.read_csv("ingredients_with_api_data-cleaned.csv")

In [52]:
ings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 496 entries, 0 to 495
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   original_ingredient  495 non-null    object
 1   cas_number           371 non-null    object
 2   clean_name           495 non-null    object
 3   api_rn               460 non-null    object
 4   api_name             464 non-null    object
dtypes: object(5)
memory usage: 19.5+ KB

In [53]:
#all_traits = set()
#for traits in harms['Hazard Traits'].str.split('; '):
    #all_traits.update(traits)

In [54]:
#for trait in all_traits:
    #harms[trait] = harms['Hazard Traits'].str.contains(trait, regex=False).astype(int)

In [55]:
#harms.head()

In [56]:
ings = ings.rename(columns={'api_rn': 'CAS RN'})

In [57]:
len(ings)

496

In [58]:
merge = pd.merge(ings, harms, how = "left", on = "CAS RN")

In [59]:
merge.head()

,original_ingredient,cas_number,clean_name,CAS RN,api_name,Chemical Name,Synonyms,Hazard Traits,Authoritative List,"When to Report (Any, FF, FA)",Unnamed: 6
0,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,"Titanium dioxide (airborne, unbound particles ...",CI 77891,Carcinogenicity,IARC Carcinogens - 2B; Prop 65,Any,NaN
1,CITRONELLOL,NaN,CITRONELLOL,106-22-9,Citronellol,NaN,NaN,NaN,NaN,NaN,NaN
2,LINALOOL,NaN,LINALOOL,78-70-6,(±)-Linalool,"1,6-Octadien-3-ol, 3,7-dimethyl-",LINALOOL,Fragrance Allergen,Annex III of the EU Cosmetics Regulation No. 1...,FA,NaN
3,HEXYL CINNAMAL,NaN,HEXYL CINNAMAL,101-86-0,α-Hexylcinnamaldehyde,2-Benzylideneoctanal,HEXYL CINNAMAL,Fragrance Allergen,Annex III of the EU Cosmetics Regulation No. 1...,FA,NaN
4,Limonene (1-methyl-4-prop-1-en-2-yl-cyclohexen...,5989-27-5,Limonene (1-methyl-4-prop-1-en-2-yl-cyclohexen...,5989-27-5,(+)-Limonene,NaN,NaN,NaN,NaN,NaN,NaN

In [66]:
merge['Hazard Traits'].isnull().sum()

np.int64(122)

In [67]:
len(merge)

10360

In [75]:
1918/10360

0.18513513513513513

In [60]:
merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10360 entries, 0 to 10359
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   original_ingredient           10085 non-null  object
 1   cas_number                    645 non-null    object
 2   clean_name                    10085 non-null  object
 3   CAS RN                        460 non-null    object
 4   api_name                      1560 non-null   object
 5   Chemical Name                 10238 non-null  object
 6   Synonyms                      1345 non-null   object
 7   Hazard Traits                 10238 non-null  object
 8   Authoritative List            10238 non-null  object
 9   When to Report (Any, FF, FA)  10238 non-null  object
 10  Unnamed: 6                    36 non-null     object
dtypes: object(11)
memory usage: 890.4+ KB

In [77]:
NAN = merge[merge["Hazard Traits"] == 'Hazard Trait Undefined']
NAN.head()

,original_ingredient,cas_number,clean_name,CAS RN,api_name,Chemical Name,Synonyms,Hazard Traits,Authoritative List,"When to Report (Any, FF, FA)",Unnamed: 6
86,NaN,NaN,NaN,NaN,NaN,10:2 Fluorotelomer acetate,NaN,Hazard Trait Undefined,CECBP - Priority Chemicals,FF,NaN
90,NaN,NaN,NaN,NaN,NaN,"2-Bromoallyl-2,4,6-tribromophenyl ether",NaN,Hazard Trait Undefined,CECBP - Priority Chemicals,FF,NaN
92,NaN,NaN,NaN,NaN,NaN,2-Ethylhexyl diphenyl phosphate,NaN,Hazard Trait Undefined,CECBP - Priority Chemicals,FF,NaN
93,NaN,NaN,NaN,NaN,NaN,2-Hydroxypropyl 2-(2-hyrdoxyethyl)ethyl tetrab...,NaN,Hazard Trait Undefined,CECBP - Priority Chemicals,FF,NaN
96,NaN,NaN,NaN,NaN,NaN,"4,4′-Sulfonylbis[2-(2-propen-1-yl)phenol] (TGSA)",NaN,Hazard Trait Undefined,CECBP - Priority Chemicals,FF,NaN

In [79]:
NAN.groupby("cas_number").size().rename("count").reset_index()

    cas_number  count
0     106-50-3      1
1     112-02-7      1
2      12/2/24     53
3     121-54-0      1
4     123-03-5      1
5   17301-53-0      1
6   27854-31-5      1
7      57-09-0      1
8   61789-80-8      1
9    7173-51-5      1
10   8001-54-5      1

In [78]:
NAN.groupby("Chemical Name").size().rename("count").reset_index()

                                        Chemical Name  count
0                          10:2 Fluorotelomer acetate     36
1             2-Bromoallyl-2,4,6-tribromophenyl ether     36
2                     2-Ethylhexyl diphenyl phosphate     36
3   2-Hydroxypropyl 2-(2-hyrdoxyethyl)ethyl tetrab...     36
4    4,4'-Sulfonylbis[2-(2-propen-1-yl)phenol] (TGSA)     36
5    4,4′-Sulfonylbis[2-(2-propen-1-yl)phenol] (TGSA)     36
6        5:3 Fluorotelomer carboxylic acid (5:3 FTCA)     36
7   6:2 Chlorinated polyfluorinated ether sulfonic...     36
8                           6:2 Fluorotelomer acetate     36
9        7:3 Fluorotelomer carboxylic acid (7:3 FTCA)     36
10  8:2 Chlorinated polyfluorinated ether sulfonic...     36
11                          8:2 Fluorotelomer acetate     36
12       8:2 Fluorotelomer carboxylic acid (8:2 FTCA)      1
13    8:2 Fluorotelomer phosphate monoester (8:2 PAP)     36
14  9-Chlorohexadecafluoro-3-oxanonane-1-sulfonic ...     36
15  Alkyl(60%C14, 30%C16, 5%C18, 5%C12) dimethylbe...     36
16         Alkyltrimethyl ammonium compounds (ATMACs)     36
17   Ammonium 4,8-dioxa-3H-perfluorononanoate (ADONA)     36
18                            Behentrimonium chloride      1
19                              Benzalkonium chloride      1
20                              Benzethonium chloride      1
21     Benzyl-C12-18-alkyldimethyl ammonium chlorides     36
22      Benzylalkyldimethyl ammonium compounds (BACs)     36
23        Bis(1,3-dichloro-2-propyl)phosphate (BDCPP)     36
24     Bis(perfluorohexyl)phosphinic acid (6:6 PFPiA)     36
25  Brominated and Chlorinated Organic Compounds u...     36
26  C12-14-Alkyl(ethylbenzyl)dimethyl ammonium chl...     36
27           C20-22-Alkyltrimethyl ammonium chlorides     36
28                                Cetrimonium bromide      1
29                               Cetrimonium chloride      1
30                           Cetylpyridinium chloride      1
31                                     Cyclosiloxanes     36
32         Di-C14-18-alkyldimethyl ammonium chlorides     36
33                        Di-o-cresylphosphate (DoCP)     36
34       Dialkyldimethyl ammonium compounds (DADMACs)     36
35                                Dicresyl phosphates     36
36                  Didecyldimethyl ammonium chloride      1
37               Diglycidyl Ethers of p,p′-Bisphenols     36
38                                         Esterquats     36
39        Isobutoxypentabromocyclododecanes (iBPBCDs)     36
40  N-Ethyl-N-(2-hydroxyethyl)perfluoro octanesulf...     36
41  N-Ethyl-N-(2-hydroxyethyl)perfluoro octanesulf...     36
42  N-Ethyl-perfluorooctane sulfonamido acetic aci...     36
43                Non-Halogenated Aromatic Phosphates     36
44            Perfluoro(2-ethoxyethane) sulfonic acid     36
45  Perfluoro-3,6-dioxa-4-methyl-7-octene sulfonic...     36
46                  Perfluoro-3,6-dioxaheptanoic acid     36
47                      Perfluorodecylphosphonic acid     36
48            Perfluoroethylcyclohexane sulfonic acid     36
49  Perfluorohexylperfluorooctylphosphinic acid (6...     36
50             Perfluorohexylphosphonic acid (PFHxPA)     36
51              Perfluorooctylphosphonic acid (PFOPA)     36
52                                  Polyquaternium 42     36
53               Polyquaternium compounds (Polyquats)     36
54                                      QA Herbicides     36
55               Quaternary Ammonium Compounds (QACs)     36
56      Quaternary Ammonium Herbicides and Pesticides     36
57                                      Quaternium 18      1
58                         Radioactivity, Gross Alpha     36
59                          Radioactivity, Gross Beta     36
60              Tetrabromophthalic acid, mixed esters     36
61                                    p,p'-bisphenols     36
62                                 p-Phenylenediamine      1

In [61]:
hazards = merge.groupby("Hazard Traits").size().rename("count").reset_index()

In [ ]:
hazards

In [74]:
pd.set_option('display.max_rows', None)
hazards

                                         Hazard Traits  count
0    Bioaccumulation; Carcinogenicity; Cardiovascul...     36
1    Bioaccumulation; Carcinogenicity; Cardiovascul...     36
2    Bioaccumulation; Carcinogenicity; Cardiovascul...     36
3    Bioaccumulation; Carcinogenicity; Dermatotoxic...     36
4    Bioaccumulation; Carcinogenicity; Dermatotoxic...     36
5    Bioaccumulation; Carcinogenicity; Developmenta...      1
6    Bioaccumulation; Carcinogenicity; Developmenta...     36
7    Bioaccumulation; Carcinogenicity; Developmenta...     36
8    Bioaccumulation; Carcinogenicity; Developmenta...     36
9    Bioaccumulation; Carcinogenicity; Environmenta...      2
10   Bioaccumulation; Carcinogenicity; Environmenta...      1
11   Bioaccumulation; Carcinogenicity; Environmenta...      1
12   Bioaccumulation; Carcinogenicity; Environmenta...      1
13   Bioaccumulation; Carcinogenicity; Environmenta...     36
14   Bioaccumulation; Carcinogenicity; Environmenta...      2
15   Bioaccumulation; Carcinogenicity; Environmenta...      1
16   Bioaccumulation; Cardiovascular Toxicity; Derm...     36
17   Bioaccumulation; Developmental Toxicity; Envir...     36
18   Bioaccumulation; Endocrine Toxicity; Environme...      1
19   Bioaccumulation; Endocrine Toxicity; Environme...      2
20   Bioaccumulation; Endocrine toxicity; Environme...      1
21          Bioaccumulation; Environmental Persistence    495
22         Bioaccumulation; Environmental Persistence      36
23   Bioaccumulation; Environmental Persistence; En...      1
24   Bioaccumulation; Environmental Persistence; Fr...      2
25   Bioaccumulation; Environmental Persistence; Re...      1
26   Bioaccumulation; Environmental Persistence; Re...      2
27                  Bioaccumulation; Environmental tox     36
28                                     Carcinogenicity   2885
29   Carcinogenicity; Cardiovascular Toxicity; Derm...     36
30   Carcinogenicity; Cardiovascular Toxicity; Derm...     36
31   Carcinogenicity; Cardiovascular Toxicity; Derm...      1
32   Carcinogenicity; Cardiovascular Toxicity; Deve...      1
33   Carcinogenicity; Cardiovascular Toxicity; Deve...      1
34   Carcinogenicity; Cardiovascular Toxicity; Hema...      1
35   Carcinogenicity; Cardiovascular Toxicity; Hepa...      1
36   Carcinogenicity; Dermatotoxicity; Developmenta...      2
37   Carcinogenicity; Dermatotoxicity; Developmenta...      1
38   Carcinogenicity; Dermatotoxicity; Developmenta...      1
39   Carcinogenicity; Dermatotoxicity; Endocrine To...      1
40   Carcinogenicity; Dermatotoxicity; Hepatotoxici...      1
41   Carcinogenicity; Dermatotoxicity; Hepatotoxici...      1
42   Carcinogenicity; Dermatotoxicity; Hepatotoxici...     36
43   Carcinogenicity; Dermatotoxicity; Hepatotoxici...     36
44   Carcinogenicity; Dermatotoxicity; Hepatotoxici...     36
45   Carcinogenicity; Dermatotoxicity; Neurotoxicit...      1
46   Carcinogenicity; Dermatotoxicity; Ocular Toxic...      1
47             Carcinogenicity; Developmental Toxicity    108
48   Carcinogenicity; Developmental Toxicity; Endoc...     72
49   Carcinogenicity; Developmental Toxicity; Endoc...     36
50   Carcinogenicity; Developmental Toxicity; Envir...     36
51   Carcinogenicity; Developmental Toxicity; Hepat...      1
52   Carcinogenicity; Developmental Toxicity; Hepat...      1
53   Carcinogenicity; Developmental Toxicity; Neuro...      1
54   Carcinogenicity; Endocrine Toxicity; Hepatotox...     36
55   Carcinogenicity; Environmental Persistence; He...      1
56                  Carcinogenicity; Environmental tox     72
57   Carcinogenicity; Environmental tox; Hepatotoxi...     36
58   Carcinogenicity; Environmental tox; Neurotoxicity      1
59                       Carcinogenicity; Genotoxicity     42
60   Carcinogenicity; Hematotoxicity; Hepatotoxicit...      1
61   Carcinogenicity; Hematotoxicity; Other Toxicol...      1
62   Carcinogenicity; Hepatotoxicity and Digestive ...      1
63   Carcinogenicity; Hepatotoxicity and Digestive ...      1
64   Carcinogenicity; Hepatotoxicity and Digestive ...     36
65   Carcinogenicity; Immunotoxicity; Respiratory T...      1
66   Carcinogenicity; Nephrotoxicity and Other Toxi...      1
67   Carcinogenicity; Nephrotoxicity and Other Toxi...     36
68                      Carcinogenicity; Neurotoxicity     38
69   Carcinogenicity; Ocular Toxicity; Reproductive...      1
70              Carcinogenicity; Reproductive Toxicity     74
71   Carcinogenicity; Reproductive Toxicity; Respir...      2
72               Carcinogenicity; Respiratory Toxicity     74
73                             Cardiovascular Toxicity      1
74   Cardiovascular Toxicity; Dermatotoxicity; Hepa...      1
75   Cardiovascular Toxicity; Developmental Toxicit...      1
76              Cardiovascular Toxicity; Neurotoxicity     36
77   Cardiovascular Toxicity; Neurotoxicity; Reprod...     36
78   Dermatotoxicity; Developmental Toxicity; Neuro...      1
79   Dermatotoxicity; Hematotoxicity; Ocular Toxici...      1
80   Dermatotoxicity; Nephrotoxicity and Other Toxi...      1
81   Dermatotoxicity; Neurotoxicity; Ocular Toxicit...      1
82   Dermatotoxicity; Neurotoxicity; Respiratory To...      1
83   Dermatotoxicity; Ocular Toxicity; Reproductive...     36
84   Dermatotoxicity; Ocular Toxicity; Respiratory ...      3
85               Dermatotoxicity; Respiratory Toxicity      1
86                              Developmental Toxicity    218
87          Developmental Toxicity; Endocrine Toxicity      2
88   Developmental Toxicity; Endocrine Toxicity; En...      1
89   Developmental Toxicity; Endocrine Toxicity; He...      2
90   Developmental Toxicity; Endocrine Toxicity; He...    252
91   Developmental Toxicity; Endocrine Toxicity; Im...      1
92   Developmental Toxicity; Endocrine Toxicity; Im...    180
93   Developmental Toxicity; Endocrine Toxicity; Ne...    288
94   Developmental Toxicity; Endocrine Toxicity; Re...      1
95   Developmental Toxicity; Environmental tox; Hep...      1
96   Developmental Toxicity; Environmental tox; Neu...      1
97   Developmental Toxicity; Hematotoxicity; Reprod...      1
98   Developmental Toxicity; Nephrotoxicity and Oth...      1
99   Developmental Toxicity; Nephrotoxicity and Oth...      3
100              Developmental Toxicity; Neurotoxicity     38
101  Developmental Toxicity; Neurotoxicity; Reprodu...     73
102      Developmental Toxicity; Reproductive Toxicity     39
103                                 Endocrine Toxicity    510
104  Endocrine Toxicity; Neurotoxicity; Reproductiv...      1
105          Endocrine Toxicity; Reproductive Toxicity      5
106                                 Endocrine toxicity      1
107                                  Environmental tox    146
108                   Environmental tox; Neurotoxicity     73
109  Environmental tox; Neurotoxicity; Ocular Toxic...      1
110  Environmental tox; Neurotoxicity; Reproductive...      1
111  Environmental tox; Neurotoxicity; Respiratory ...      1
112                                 Fragrance Allergen     57
113                                       Genotoxicity      1
114                             Hazard Trait Undefined   1918
115  Hematotoxicity; Hepatotoxicity and Digestive S...     36
116                      Hematotoxicity; Neurotoxicity      4
117  Hepatotoxicity and Digestive System Toxicity; ...      3
118  Musculoskeletal Toxicity; Neurotoxicity; Respi...      1
119     Musculoskeletal Toxicity; Respiratory Toxicity     37
120  Nephrotoxicity and Other Toxicity to the Urina...      1
121  Nephrotoxicity and Other Toxicity to the Urina...      2
122                                      Neurotoxicity    293
123  Neurotoxicity; Ocular Toxicity; Respiratory To...     36
124               Neurotoxicity; Reproductive Toxicity     36
125  Neurotoxicity; Reproductive Toxicity; Respirat...      1
126                Neurotoxicity; Respiratory Toxicity      2
127                                    Ocular Toxicity     36
128              Ocular Toxicity; Respiratory Toxicity      1
129                              Reproductive Toxicity    626
130        Reproductive Toxicity; Respiratory Toxicity      1
131                               Respiratory Toxicity    414

In [63]:
hazards["Hazard Traits"].unique()

array(['Bioaccumulation; Carcinogenicity; Cardiovascular Toxicity; Dermatotoxicity; Developmental Toxicity; Environmental Persistence; Nephrotoxicity and Other Toxicity to the Urinary System; Neurotoxicity; Reproductive Toxicity',
       'Bioaccumulation; Carcinogenicity; Cardiovascular Toxicity; Developmental Toxicity; Environmental Persistence; Hematotoxicity; Hepatotoxicity and Digestive System Toxicity; Nephrotoxicity and Other Toxicity to the Urinary System; Neurotoxicity; Reproductive Toxicity',
       'Bioaccumulation; Carcinogenicity; Cardiovascular Toxicity; Environmental Persistence; Environmental tox; Hematotoxicity; Hepatotoxicity and Digestive System Toxicity; Immunotoxicity; Nephrotoxicity and Other Toxicity to the Urinary System; Neurotoxicity',
       'Bioaccumulation; Carcinogenicity; Dermatotoxicity; Endocrine Toxicity; Environmental Persistence; Hematotoxicity; Hepatotoxicity and Digestive System Toxicity; Neurotoxicity; Reproductive Toxicity; Respiratory Toxicity',
       'Bioaccumulation; Carcinogenicity; Dermatotoxicity; Environmental Persistence; Environmental tox; Hepatotoxicity and Digestive System Toxicity; Reproductive Toxicity',
       'Bioaccumulation; Carcinogenicity; Developmental Toxicity; Endocrine Toxicity; Environmental Persistence; Hepatotoxicity and Digestive System Toxicity; Immunotoxicity; Reproductive Toxicity; Respiratory Toxicity',
       'Bioaccumulation; Carcinogenicity; Developmental Toxicity; Endocrine Toxicity; Hepatotoxicity and Digestive System Toxicity; Immunotoxicity; Reproductive Toxicity',
       'Bioaccumulation; Carcinogenicity; Developmental Toxicity; Environmental Persistence; Environmental tox; Musculoskeletal Toxicity; Nephrotoxicity and Other Toxicity to the Urinary System; Reproductive Toxicity; Respiratory Toxicity',
       'Bioaccumulation; Carcinogenicity; Developmental Toxicity; Environmental Persistence; Neurotoxicity; Reproductive Toxicity',
       'Bioaccumulation; Carcinogenicity; Environmental Persistence',
       'Bioaccumulation; Carcinogenicity; Environmental Persistence; Environmental tox; Hematotoxicity; Hepatotoxicity and Digestive System Toxicity; Neurotoxicity; Ocular Toxicity; Other Toxicological Hazard Traits; Respiratory Toxicity',
       'Bioaccumulation; Carcinogenicity; Environmental Persistence; Genotoxicity',
       'Bioaccumulation; Carcinogenicity; Environmental Persistence; Genotoxicity; Neurotoxicity; Reproductive Toxicity',
       'Bioaccumulation; Carcinogenicity; Environmental Persistence; Hematotoxicity; Immunotoxicity; Other Toxicological Hazard Traits; Reproductive Toxicity; Respiratory Toxicity',
       'Bioaccumulation; Carcinogenicity; Environmental Persistence; Hepatotoxicity and Digestive System Toxicity; Immunotoxicity; Reproductive Toxicity',
       'Bioaccumulation; Carcinogenicity; Environmental Persistence; Neurotoxicity; Respiratory Toxicity',
       'Bioaccumulation; Cardiovascular Toxicity; Dermatotoxicity; Developmental Toxicity; Endocrine Toxicity; Environmental Persistence; Hepatotoxicity and Digestive System Toxicity; Musculoskeletal Toxicity; Neurotoxicity; Respiratory Toxicity',
       'Bioaccumulation; Developmental Toxicity; Environmental Persistence; Neurotoxicity; Reproductive Toxicity',
       'Bioaccumulation; Endocrine Toxicity; Environmental Persistence',
       'Bioaccumulation; Endocrine Toxicity; Environmental Persistence; Hepatotoxicity and Digestive System Toxicity; Reproductive Toxicity',
       'Bioaccumulation; Endocrine toxicity; Environmental tox',
       'Bioaccumulation; Environmental Persistence',
       'Bioaccumulation; Environmental Persistence ',
       'Bioaccumulation; Environmental Persistence; Environmental tox',
       'Bioaccumulation; Environmental Persistence; Fragrance Allergen',
       'Bioaccumulation; Environmental Persistence; Reproductive Toxicity',
       'Bioaccumulation; Environmental Persistence; Respiratory Toxicity',
       'Bioaccumulation; Environmental tox', 'Carcinogenicity',
       'Carcinogenicity; Cardiovascular Toxicity; Dermatotoxicity; Developmental Toxicity; Hepatotoxicity and Digestive System Toxicity; Neurotoxicity; Other Toxicological Hazard Traits; Respiratory Toxicity',
       'Carcinogenicity; Cardiovascular Toxicity; Dermatotoxicity; Developmental Toxicity; Neurotoxicity; Respiratory Toxicity',
       'Carcinogenicity; Cardiovascular Toxicity; Dermatotoxicity; Hepatotoxicity and Digestive System Toxicity; Nephrotoxicity and Other Toxicity to the Urinary System; Neurotoxicity; Other Toxicological Hazard Traits',
       'Carcinogenicity; Cardiovascular Toxicity; Developmental Toxicity; Genotoxicity; Hematotoxicity; Immunotoxicity; Neurodevelopmental Toxicity; Neurotoxicity; Reproductive Toxicity; Respiratory Toxicity',
       'Carcinogenicity; Cardiovascular Toxicity; Developmental Toxicity; Respiratory Toxicity',
       'Carcinogenicity; Cardiovascular Toxicity; Hematotoxicity; Respiratory Toxicity',
       'Carcinogenicity; Cardiovascular Toxicity; Hepatotoxicity and Digestive System Toxicity; Neurotoxicity; Respiratory Toxicity',
       'Carcinogenicity; Dermatotoxicity; Developmental Toxicity; Genotoxicity; Hematotoxicity; Neurotoxicity; Reproductive Toxicity; Respiratory Toxicity',
       'Carcinogenicity; Dermatotoxicity; Developmental Toxicity; Genotoxicity; Neurotoxicity; Ocular Toxicity; Reproductive Toxicity; Respiratory Toxicity',
       'Carcinogenicity; Dermatotoxicity; Developmental Toxicity; Hematotoxicity; Hepatotoxicity and Digestive System Toxicity; Reproductive Toxicity; Respiratory Toxicity',
       'Carcinogenicity; Dermatotoxicity; Endocrine Toxicity; Hepatotoxicity and Digestive System Toxicity; Nephrotoxicity and Other Toxicity to the Urinary System; Neurotoxicity; Ocular Toxicity',
       'Carcinogenicity; Dermatotoxicity; Hepatotoxicity and Digestive System Toxicity; Nephrotoxicity and Other Toxicity to the Urinary System; Neurotoxicity; Ocular Toxicity',
       'Carcinogenicity; Dermatotoxicity; Hepatotoxicity and Digestive System Toxicity; Nephrotoxicity and Other Toxicity to the Urinary System; Neurotoxicity; Ocular Toxicity; Reproductive Toxicity; Respiratory Toxicity',
       'Carcinogenicity; Dermatotoxicity; Hepatotoxicity and Digestive System Toxicity; Neurotoxicity',
       'Carcinogenicity; Dermatotoxicity; Hepatotoxicity and Digestive System Toxicity; Ocular Toxicity; Respiratory Toxicity',
       'Carcinogenicity; Dermatotoxicity; Hepatotoxicity and Digestive System Toxicity; Reproductive Toxicity',
       'Carcinogenicity; Dermatotoxicity; Neurotoxicity; Ocular Toxicity; Respiratory Toxicity',
       'Carcinogenicity; Dermatotoxicity; Ocular Toxicity; Respiratory Toxicity',
       'Carcinogenicity; Developmental Toxicity',
       'Carcinogenicity; Developmental Toxicity; Endocrine Toxicity; Immunotoxicity; Reproductive Toxicity; Respiratory Toxicity',
       'Carcinogenicity; Developmental Toxicity; Endocrine Toxicity; Neurotoxicity; Reproductive Toxicity',
       'Carcinogenicity; Developmental Toxicity; Environmental tox; Hematotoxicity; Immunotoxicity; Other Toxicological Hazard Traits; Respiratory Toxicity',
       'Carcinogenicity; Developmental Toxicity; Hepatotoxicity and Digestive System Toxicity; Nephrotoxicity and Other Toxicity to the Urinary System; Neurotoxicity; Ocular Toxicity',
       'Carcinogenicity; Developmental Toxicity; Hepatotoxicity and Digestive System Toxicity; Neurotoxicity; Ocular Toxicity; Reproductive Toxicity; Respiratory Toxicity',
       'Carcinogenicity; Developmental Toxicity; Neurotoxicity; Reproductive Toxicity',
       'Carcinogenicity; Endocrine Toxicity; Hepatotoxicity and Digestive System Toxicity; Nephrotoxicity and Other Toxicity to the Urinary System; Respiratory Toxicity',
       'Carcinogenicity; Environmental Persistence; Hematotoxicity; Hepatotoxicity and Digestive System Toxicity; Nephrotoxicity and Other Toxicity to the Urinary System; Neurotoxicity',
       'Carcinogenicity; Environmental tox',
       'Carcinogenicity; Environmental tox; Hepatotoxicity and Digestive System Toxicity; Immunotoxicity; Respiratory Toxicity',
       'Carcinogenicity; Environmental tox; Neurotoxicity',
       'Carcinogenicity; Genotoxicity',
       'Carcinogenicity; Hematotoxicity; Hepatotoxicity and Digestive System Toxicity; Nephrotoxicity and Other Toxicity to the Urinary System; Neurotoxicity; Ocular Toxicity; Respiratory Toxicity',
       'Carcinogenicity; Hematotoxicity; Other Toxicological Hazard Traits',
       'Carcinogenicity; Hepatotoxicity and Digestive System Toxicity',
       'Carcinogenicity; Hepatotoxicity and Digestive System Toxicity; Neurotoxicity; Respiratory Toxicity',
       'Carcinogenicity; Hepatotoxicity and Digestive System Toxicity; Respiratory Toxicity',
       'Carcinogenicity; Immunotoxicity; Respiratory Toxicity',
       'Carcinogenicity; Nephrotoxicity and Other Toxicity to the Urinary System; Neurotoxicity',
       'Carcinogenicity; Nephrotoxicity and Other Toxicity to the Urinary System; Respiratory Toxicity',
       'Carcinogenicity; Neurotoxicity',
       'Carcinogenicity; Ocular Toxicity; Reproductive Toxicity; Respiratory Toxicity',
       'Carcinogenicity; Reproductive Toxicity',
       'Carcinogenicity; Reproductive Toxicity; Respiratory Toxicity',
       'Carcinogenicity; Respiratory Toxicity', 'Cardiovascular Toxicity',
       'Cardiovascular Toxicity; Dermatotoxicity; Hepatotoxicity and Digestive System Toxicity; Nephrotoxicity and Other Toxicity to the Urinary System; Neurotoxicity; Ocular Toxicity; Other Toxicological Hazard Traits; Respiratory Toxicity',
       'Cardiovascular Toxicity; Developmental Toxicity; Hepatotoxicity and Digestive System Toxicity; Immunotoxicity; Neurotoxicity; Respiratory Toxicity',
       'Cardiovascular Toxicity; Neurotoxicity',
       'Cardiovascular Toxicity; Neurotoxicity; Reproductive Toxicity; Respiratory Toxicity',
       'Dermatotoxicity; Developmental Toxicity; Neurotoxicity; Ocular Toxicity; Respiratory Toxicity',
       'Dermatotoxicity; Hematotoxicity; Ocular Toxicity; Respiratory Toxicity',
       'Dermatotoxicity; Nephrotoxicity and Other Toxicity to the Urinary System; Respiratory Toxicity',
       'Dermatotoxicity; Neurotoxicity; Ocular Toxicity; Respiratory Toxicity',
       'Dermatotoxicity; Neurotoxicity; Respiratory Toxicity',
       'Dermatotoxicity; Ocular Toxicity; Reproductive Toxicity; Respiratory Toxicity',
       'Dermatotoxicity; Ocular Toxicity; Respiratory Toxicity',
       'Dermatotoxicity; Respiratory Toxicity', 'Developmental Toxicity',
       'Developmental Toxicity; Endocrine Toxicity',
       'Developmental Toxicity; Endocrine Toxicity; Environmental tox; Immunotoxicity; Ocular Toxicity; Reproductive Toxicity; Respiratory Toxicity',
       'Developmental Toxicity; Endocrine Toxicity; Hepatotoxicity and Digestive System Toxicity; Immunotoxicity; Other Toxicological Hazard Traits; Reproductive Toxicity; Respiratory Toxicity',
       'Developmental Toxicity; Endocrine Toxicity; Hepatotoxicity and Digestive System Toxicity; Neurotoxicity; Reproductive Toxicity',
       'Developmental Toxicity; Endocrine Toxicity; Immunotoxicity; Other Toxicological Hazard Traits; Reproductive Toxicity; Respiratory Toxicity',
       'Developmental Toxicity; Endocrine Toxicity; Immunotoxicity; Reproductive Toxicity; Respiratory Toxicity',
       'Developmental Toxicity; Endocrine Toxicity; Neurotoxicity; Reproductive Toxicity',
       'Developmental Toxicity; Endocrine Toxicity; Reproductive Toxicity',
       'Developmental Toxicity; Environmental tox; Hepatotoxicity and Digestive System Toxicity; Nephrotoxicity and Other Toxicity to the Urinary System; Neurodevelopmental Toxicity; Neurotoxicity; Reproductive Toxicity',
       'Developmental Toxicity; Environmental tox; Neurotoxicity',
       'Developmental Toxicity; Hematotoxicity; Reproductive Toxicity',
       'Developmental Toxicity; Nephrotoxicity and Other Toxicity to the Urinary System; Neurotoxicity; Ocular Toxicity; Respiratory Toxicity',
       'Developmental Toxicity; Nephrotoxicity and Other Toxicity to the Urinary System; Ocular Toxicity; Respiratory Toxicity',
       'Developmental Toxicity; Neurotoxicity',
       'Developmental Toxicity; Neurotoxicity; Reproductive Toxicity',
       'Developmental Toxicity; Reproductive Toxicity',
       'Endocrine Toxicity',
       'Endocrine Toxicity; Neurotoxicity; Reproductive Toxicity',
       'Endocrine Toxicity; Reproductive Toxicity', 'Endocrine toxicity',
       'Environmental tox', 'Environmental tox; Neurotoxicity',
       'Environmental tox; Neurotoxicity; Ocular Toxicity; Respiratory Toxicity',
       'Environmental tox; Neurotoxicity; Reproductive Toxicity',
       'Environmental tox; Neurotoxicity; Respiratory Toxicity',
       'Fragrance Allergen', 'Genotoxicity', 'Hazard Trait Undefined',
       'Hematotoxicity; Hepatotoxicity and Digestive System Toxicity; Nephrotoxicity and Other Toxicity to the Urinary System; Neurotoxicity',
       'Hematotoxicity; Neurotoxicity',
       'Hepatotoxicity and Digestive System Toxicity; Neurotoxicity',
       'Musculoskeletal Toxicity; Neurotoxicity; Respiratory Toxicity',
       'Musculoskeletal Toxicity; Respiratory Toxicity',
       'Nephrotoxicity and Other Toxicity to the Urinary System',
       'Nephrotoxicity and Other Toxicity to the Urinary System; Neurotoxicity',
       'Neurotoxicity',
       'Neurotoxicity; Ocular Toxicity; Respiratory Toxicity',
       'Neurotoxicity; Reproductive Toxicity',
       'Neurotoxicity; Reproductive Toxicity; Respiratory Toxicity',
       'Neurotoxicity; Respiratory Toxicity', 'Ocular Toxicity',
       'Ocular Toxicity; Respiratory Toxicity', 'Reproductive Toxicity',
       'Reproductive Toxicity; Respiratory Toxicity',
       'Respiratory Toxicity'], dtype=object)

In [64]:
hazards.sort_values("count", ascending = False)

                                         Hazard Traits  count
28                                     Carcinogenicity   2885
114                             Hazard Trait Undefined   1918
129                              Reproductive Toxicity    626
103                                 Endocrine Toxicity    510
21          Bioaccumulation; Environmental Persistence    495
..                                                 ...    ...
74   Cardiovascular Toxicity; Dermatotoxicity; Hepa...      1
73                             Cardiovascular Toxicity      1
25   Bioaccumulation; Environmental Persistence; Re...      1
69   Carcinogenicity; Ocular Toxicity; Reproductive...      1
66   Carcinogenicity; Nephrotoxicity and Other Toxi...      1

[132 rows x 2 columns]