In [2]:
import pandas as pd

In [3]:
chemicals = pd.read_csv("data/chemical_names_cleaned_2_18.csv")

In [4]:
chemicals.head()

,original_ingredient,cas_number,clean_name,api_rn,api_name
0,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,8023-85-6,Cedrus Atlantica Oil,8023-85-6,Cedrus Atlantica Oil
1,"[3R-(3a,3aß,7ß,8aa)]-1-(2,3,4,7,8,8a-hexahydro...",32388-55-9,Acetylcedrene,32388-55-9,Acetylcedrene
2,"1-Naphthalenepropanol, a-ethenyldecahydro- 2-h...",515-03-7,Sclareol,515-03-7,Sclareol
3,Myroxylon Pereirae Oil/Extract (Myroxylon bals...,8007-00-9,Myroxylon Pereirae Oil/Extract,8007-00-9,Myroxylon Pereirae Oil/Extract
4,Turpentine gum (Pinus spp.); Turpentine oil an...,9005-90-7,Turpentine,9005-90-7,Turpentine

In [5]:
chemicals = chemicals.rename(columns = {"original_ingredient": 'Ingredient Name'})

In [6]:
chemicals.head()

,Ingredient Name,cas_number,clean_name,api_rn,api_name
0,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,8023-85-6,Cedrus Atlantica Oil,8023-85-6,Cedrus Atlantica Oil
1,"[3R-(3a,3aß,7ß,8aa)]-1-(2,3,4,7,8,8a-hexahydro...",32388-55-9,Acetylcedrene,32388-55-9,Acetylcedrene
2,"1-Naphthalenepropanol, a-ethenyldecahydro- 2-h...",515-03-7,Sclareol,515-03-7,Sclareol
3,Myroxylon Pereirae Oil/Extract (Myroxylon bals...,8007-00-9,Myroxylon Pereirae Oil/Extract,8007-00-9,Myroxylon Pereirae Oil/Extract
4,Turpentine gum (Pinus spp.); Turpentine oil an...,9005-90-7,Turpentine,9005-90-7,Turpentine

In [7]:
len(chemicals)

505

In [8]:
all_data = pd.read_csv("data/CDPH Search results - 1_12_2026, 3_34_15 PM.csv")

In [9]:
len(all_data)

534508

In [10]:
first_merge = all_data.merge(chemicals, on = "Ingredient Name", how = 'left')

In [11]:
first_merge.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,Concentration,Ingredient Submitted Date,Ingredient Removed Date,cas_number,clean_name,api_rn,api_name
0,18358,Nail Alliance - Entity,Entity Nudite,Cool Pink Nail Sculpting Powder,NaN,NaN,6/24/2019,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,5.000000,6/24/2019,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania
1,38661,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,40.000000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania
2,38662,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Sprinkle,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,31.000000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania
3,38667,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,12.000000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania
4,38665,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,21.500000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania

In [12]:
first_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 534508 entries, 0 to 534507
Data columns (total 17 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Product Id                 534508 non-null  int64
 1   Company                    534508 non-null  object
 2   Brand                      534308 non-null  object
 3   Product Name               534508 non-null  object
 4   Variant                    187813 non-null  object
 5   Product Discontinued Date  39102 non-null   object
 6   Product Submitted Date     534508 non-null  object
 7   Ingredient Name            534186 non-null  object
 8   Function                   433384 non-null  object
 9   Unit of Measure            222747 non-null  object
 10  Concentration              224495 non-null  object
 11  Ingredient Submitted Date  534186 non-null  object
 12  Ingredient Removed Date    6627 non-null    object
 13  cas_number                 447569 non-null  object
 14  clean_name                 534186 non-null  object
 15  api_rn                     532360 non-null  object
 16  api_name                   534186 non-null  object
dtypes: int64(1), object(16)
memory usage: 69.3+ MB

In [13]:
na = first_merge[first_merge["api_name"].isna()]
na.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,Concentration,Ingredient Submitted Date,Ingredient Removed Date,cas_number,clean_name,api_rn,api_name
1402,72818,Exclusive Fragrances & Cosmetics,10 Corso Como,10 Corso Como Massage Oil,10 Corso Como,NaN,6/29/2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404,72816,IPD Inc,10 Corso Como,Corso Como Bath Pearls,Corso Como,NaN,6/25/2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10283,109738,Aloisia Beauty Products Inc.,Aloisia Beauty,Light Hydration Emulsion,NaN,NaN,6/6/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10284,109736,Aloisia Beauty Products Inc.,Aloisia Beauty,Renew Concentrated Serum,NaN,NaN,6/6/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10286,109739,Aloisia Beauty Products Inc.,Aloisia Beauty,Revitalize Eye Cream,NaN,NaN,6/6/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
na["Ingredient Name"].unique()

array([nan], dtype=object)

In [15]:
na_ingredients = na["Ingredient Name"].unique().tolist()
na_ingredients

[nan]

In [16]:
na_names = pd.DataFrame(na_ingredients)

In [17]:
na_names.to_csv("na_names.csv")

In [18]:
na_names_cleaned = pd.read_csv("data/na_names_cleaned.csv", encoding='latin-1')

na_names_cleaned = na_names_cleaned.apply(
    lambda col: col.str.replace('\xa0', ' ', regex=False) if col.dtype == 'object' else col
)

In [19]:
na_names_cleaned["name"].unique().tolist()

['Cedrus Atlantica Oil/Extract (Cedrus atlantica\\xa0oil and extract; Cedrus Atlantica Bark Extract; Cedrus Atlantica Bark Oil; Cedrus Atlantica Bark Water; Cedrus Atlantica Leaf Extract; Cedrus Atlantica Wood Extract; Cedrus Atlantica Wood Oil) 92201-55-3 / 8023-85-6,',
 '[3R-(3a,3a§,7§,8aa)]-1-(2,3,4,7,8,8a-hexahydro-3,6,8,8-tetramethyl-1H-3a,7-methanoazulen-5-yl)ethan-1-one (Acetyl Cedrene) 32388-55-9,',
 '1-Naphthalenepropanol, a-ethenyldecahydro- 2-hydroxy-a,2,5,5,8a-pentamethyl-, [1R-[1a(R),2§,4a§,8aa]]- (Sclareol; [1R-(1alpha)]-alpha-Ethenyldecahydro-2-hydroxy-a,2,5,5,8a-pentamethyl-1-naphthalenepropanol) 515-03-7,',
 'Myroxylon Pereirae Oil/Extract (Myroxylon balsamum\\xa0var.\\xa0pereirae; extracts and distillates; Balsam Peru oil, absolute and anhydrol (Balsam Oil Peru); Myroxylon Balsamum Pereirae Balsam Extract; Myroxylon Balsamum Pereirae Balsam Oil; Myroxylon Pereirae Oil; Myroxylon Pereirae Resin Extract; Myroxylon Pereirae Resin; Myroxylon Pereirae (Balsam Peru) Oil; Myroxylon Pereirae (Balsam Peru) Resin; Myroxylon Pereirae (Balsam Peru) Resin Extract) 8007-00-9,',
 'Turpentine gum (Pinus\\xa0spp.); Turpentine oil and rectified oil; Turpentine, steam distilled (Pinus\\xa0spp.) (Turpentine) 9005-90-7 / 8006-64-2 / 8052-14-0,',
 'Butane (containing greater than or equal to  0,1\\xa0% butadiene (203-450-8)) 106-97-8,',
 ' Pinus Mugo (Pinus mugo\\xa0leaf and twig oil and extract; Pinus Mugo Leaf Oil; Pinus Mugo Twig Leaf Extract; Pinus Mugo Twig Oil; Pinus Mugo Leaf/Twig Extract) 90082-72-7,',
 '(±)-1,7,7-trimethyl-3-[(4-methylphenyl)methylene]bicyclo[2.2.1]heptan-2-one (covering any of the individual isomers and/or combinations thereof (4-MBC); 4-Methylbenzylidene Camphor (4-MBC)) 36861-47-9,',
 'Pinus Pumila (Pinus pumila\\xa0leaf and twig oil and extract; Pinus Pumila Needle Extract; Pinus Pumila Twig Leaf Extract; Pinus Pumila Twig Leaf Oil; Pinus Mugo Leaf/Twig Extract; Pinus Mugo Twig Oil; Pinus Pumilio Branch/Leaf Oil; Pinus Pumilio Leaf Extract) 97676-05-6],']

In [20]:
na_names_cleaned = na_names_cleaned.rename(columns={'name': 'Ingredient Name'})
na_names_cleaned = na_names_cleaned.rename(columns={'api_cas': 'api_rn'})
na_names_cleaned.head()

,Ingredient Name,api_rn,api_name
0,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,8023-85-6,Cedrus Atlantica Oil
1,"[3R-(3a,3a§,7§,8aa)]-1-(2,3,4,7,8,8a-hexahydro...",32388-55-9,Acetylcedrene
2,"1-Naphthalenepropanol, a-ethenyldecahydro- 2-h...",515-03-7,Sclareol
3,Myroxylon Pereirae Oil/Extract (Myroxylon bals...,8007-00-9,Myroxylon Pereirae Oil/Extract
4,Turpentine gum (Pinus\xa0spp.); Turpentine oil...,9005-90-7,Turpentine

In [21]:
first_merge.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,Concentration,Ingredient Submitted Date,Ingredient Removed Date,cas_number,clean_name,api_rn,api_name
0,18358,Nail Alliance - Entity,Entity Nudite,Cool Pink Nail Sculpting Powder,NaN,NaN,6/24/2019,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,5.000000,6/24/2019,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania
1,38661,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,40.000000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania
2,38662,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Sprinkle,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,31.000000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania
3,38667,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,12.000000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania
4,38665,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,21.500000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania

In [22]:
first_merge.update(na_names_cleaned)

In [23]:
na_names_cleaned

,Ingredient Name,api_rn,api_name
0,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,8023-85-6,Cedrus Atlantica Oil
1,"[3R-(3a,3a§,7§,8aa)]-1-(2,3,4,7,8,8a-hexahydro...",32388-55-9,Acetylcedrene
2,"1-Naphthalenepropanol, a-ethenyldecahydro- 2-h...",515-03-7,Sclareol
3,Myroxylon Pereirae Oil/Extract (Myroxylon bals...,8007-00-9,Myroxylon Pereirae Oil/Extract
4,Turpentine gum (Pinus\xa0spp.); Turpentine oil...,9005-90-7,Turpentine
5,Butane (containing greater than or equal to 0...,106-97-8,Butane
6,Pinus Mugo (Pinus mugo\xa0leaf and twig oil a...,90082-72-7,"Pine,ÊPinus mugo, ext."
7,"(±)-1,7,7-trimethyl-3-[(4-methylphenyl)methyle...",36861-47-9,3-(4_-Methylbenzylidene)camphor
8,Pinus Pumila (Pinus pumila\xa0leaf and twig oi...,97676-05-6,"Pine,ÊPinus pumila, ext."

In [24]:
first_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 534508 entries, 0 to 534507
Data columns (total 17 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Product Id                 534508 non-null  int64
 1   Company                    534508 non-null  object
 2   Brand                      534308 non-null  object
 3   Product Name               534508 non-null  object
 4   Variant                    187813 non-null  object
 5   Product Discontinued Date  39102 non-null   object
 6   Product Submitted Date     534508 non-null  object
 7   Ingredient Name            534186 non-null  object
 8   Function                   433384 non-null  object
 9   Unit of Measure            222747 non-null  object
 10  Concentration              224495 non-null  object
 11  Ingredient Submitted Date  534186 non-null  object
 12  Ingredient Removed Date    6627 non-null    object
 13  cas_number                 447569 non-null  object
 14  clean_name                 534186 non-null  object
 15  api_rn                     532360 non-null  object
 16  api_name                   534186 non-null  object
dtypes: int64(1), object(16)
memory usage: 69.3+ MB

In [25]:
harms = pd.read_csv("reportable_ingredients.csv")

In [26]:
harms.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3324 entries, 0 to 3323
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Chemical Name                 3324 non-null   object
 1   CAS RN                        3049 non-null   object
 2   Synonyms                      571 non-null    object
 3   Hazard Traits                 3324 non-null   object
 4   Authoritative List            3324 non-null   object
 5   When to Report (Any, FF, FA)  3324 non-null   object
 6   Unnamed: 6                    1 non-null      object
dtypes: object(7)
memory usage: 181.9+ KB

In [27]:
harms.rename(columns={'CAS RN': 'api_rn'}, inplace=True)

In [28]:
chemicals.head()

,Ingredient Name,cas_number,clean_name,api_rn,api_name
0,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,8023-85-6,Cedrus Atlantica Oil,8023-85-6,Cedrus Atlantica Oil
1,"[3R-(3a,3aß,7ß,8aa)]-1-(2,3,4,7,8,8a-hexahydro...",32388-55-9,Acetylcedrene,32388-55-9,Acetylcedrene
2,"1-Naphthalenepropanol, a-ethenyldecahydro- 2-h...",515-03-7,Sclareol,515-03-7,Sclareol
3,Myroxylon Pereirae Oil/Extract (Myroxylon bals...,8007-00-9,Myroxylon Pereirae Oil/Extract,8007-00-9,Myroxylon Pereirae Oil/Extract
4,Turpentine gum (Pinus spp.); Turpentine oil an...,9005-90-7,Turpentine,9005-90-7,Turpentine

In [29]:
chemicals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Ingredient Name  504 non-null    object
 1   cas_number       380 non-null    object
 2   clean_name       504 non-null    object
 3   api_rn           489 non-null    object
 4   api_name         504 non-null    object
dtypes: object(5)
memory usage: 19.9+ KB

In [30]:
len(chemicals)

505

In [31]:
harms.head()

,Chemical Name,api_rn,Synonyms,Hazard Traits,Authoritative List,"When to Report (Any, FF, FA)",Unnamed: 6
0,(±) Tetrahydrofurfuryl (R)-2-[4-(6-chloroquino...,119738-06-6,NaN,Reproductive Toxicity,EC Annex VI CMRs - Cat. 1B,FF,NaN
1,"(±)-1,7,7-trimethyl-3-[(4-methylphenyl)methyle...",36861-47-9,"4-Methylbenzylidene Camphor (4-MBC); (±)-1,7,7...",Endocrine Toxicity,EC EDs,FF,NaN
2,"(1a,2a,3ß,6ß)-1,2,3,6-tetrahydro-3,6-methanoph...",2746-19-2,NaN,Respiratory Toxicity,EC Annex VI Resp. Sens. - Cat. 1,FF,NaN
3,"(1R,3E,4S)-1,7,7-trimethyl-3-(4-methylbenzylid...",95342-41-9,NaN,Endocrine Toxicity,EC EDs,FF,NaN
4,"(1R,3Z,4S)-1,7,7-trimethyl-3-(4-methylbenzylid...",852541-21-0,NaN,Endocrine Toxicity,EC EDs,FF,NaN

In [32]:
len(harms)

3324

In [33]:
harms.head()

,Chemical Name,api_rn,Synonyms,Hazard Traits,Authoritative List,"When to Report (Any, FF, FA)",Unnamed: 6
0,(±) Tetrahydrofurfuryl (R)-2-[4-(6-chloroquino...,119738-06-6,NaN,Reproductive Toxicity,EC Annex VI CMRs - Cat. 1B,FF,NaN
1,"(±)-1,7,7-trimethyl-3-[(4-methylphenyl)methyle...",36861-47-9,"4-Methylbenzylidene Camphor (4-MBC); (±)-1,7,7...",Endocrine Toxicity,EC EDs,FF,NaN
2,"(1a,2a,3ß,6ß)-1,2,3,6-tetrahydro-3,6-methanoph...",2746-19-2,NaN,Respiratory Toxicity,EC Annex VI Resp. Sens. - Cat. 1,FF,NaN
3,"(1R,3E,4S)-1,7,7-trimethyl-3-(4-methylbenzylid...",95342-41-9,NaN,Endocrine Toxicity,EC EDs,FF,NaN
4,"(1R,3Z,4S)-1,7,7-trimethyl-3-(4-methylbenzylid...",852541-21-0,NaN,Endocrine Toxicity,EC EDs,FF,NaN

In [34]:
harms_agg = harms.groupby('api_rn').agg({
    'Hazard Traits': '; '.join,   
    'Chemical Name': 'first',
    'Synonyms': 'first',
    'Authoritative List': '; '.join,
    'When to Report (Any, FF, FA)': 'first'
}).reset_index()

In [35]:
chemicals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Ingredient Name  504 non-null    object
 1   cas_number       380 non-null    object
 2   clean_name       504 non-null    object
 3   api_rn           489 non-null    object
 4   api_name         504 non-null    object
dtypes: object(5)
memory usage: 19.9+ KB

In [36]:
result = chemicals.merge(harms_agg, on='api_rn', how='left')
result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 10 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Ingredient Name               504 non-null    object
 1   cas_number                    380 non-null    object
 2   clean_name                    504 non-null    object
 3   api_rn                        489 non-null    object
 4   api_name                      504 non-null    object
 5   Hazard Traits                 359 non-null    object
 6   Chemical Name                 359 non-null    object
 7   Synonyms                      213 non-null    object
 8   Authoritative List            359 non-null    object
 9   When to Report (Any, FF, FA)  359 non-null    object
dtypes: object(10)
memory usage: 39.6+ KB

In [37]:
len(result)

505

In [38]:
na = result[result["Hazard Traits"].isna()]
na.head()

,Ingredient Name,cas_number,clean_name,api_rn,api_name,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)"
0,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,8023-85-6,Cedrus Atlantica Oil,8023-85-6,Cedrus Atlantica Oil,NaN,NaN,NaN,NaN,NaN
4,Turpentine gum (Pinus spp.); Turpentine oil an...,9005-90-7,Turpentine,9005-90-7,Turpentine,NaN,NaN,NaN,NaN,NaN
10,CITRONELLOL,NaN,CITRONELLOL,106-22-9,Citronellol,NaN,NaN,NaN,NaN,NaN
13,Limonene (1-methyl-4-prop-1-en-2-yl-cyclohexen...,5989-27-5,Limonene (1-methyl-4-prop-1-en-2-yl-cyclohexen...,5989-27-5,(+)-Limonene,NaN,NaN,NaN,NaN,NaN
15,"Aloe vera, non-decolorized (unfiltered) whole ...",NaN,"Aloe vera, non-decolorized (unfiltered) whole ...",8001-97-6,Aloe vera,NaN,NaN,NaN,NaN,NaN

In [39]:
len(na)

146

In [40]:
len(result) - len(na)

359

In [41]:
result = result.dropna(subset =['Hazard Traits'])
len(result)

359

In [42]:
harms_agg.head()

,api_rn,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)"
0,85-00-7,Hazard Trait Undefined,Diquat dibromide,None,CECBP - Priority Chemicals,FF
1,100-00-5,Carcinogenicity,1-Chloro-4-nitrobenzene,4-Chloronitrobenzene,IARC Carcinogens - 2B; Prop 65,Any
2,100-02-7,Dermatotoxicity; Environmental tox; Other Toxi...,4-Nitrophenol,None,CA TACs; CECBP - Priority Chemicals; CWA 303(c...,FF
3,100-17-4,Carcinogenicity,para-Nitroanisole,None,IARC Carcinogens - 2B; Prop 65,Any
4,100-25-4,Reproductive Toxicity,p-Dinitrobenzene,None,Prop 65,Any

In [43]:
harms_agg.rename(columns={'Chemical Name': 'Ingredient Name'}, inplace=True)

In [44]:
na.head()

,Ingredient Name,cas_number,clean_name,api_rn,api_name,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)"
0,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,8023-85-6,Cedrus Atlantica Oil,8023-85-6,Cedrus Atlantica Oil,NaN,NaN,NaN,NaN,NaN
4,Turpentine gum (Pinus spp.); Turpentine oil an...,9005-90-7,Turpentine,9005-90-7,Turpentine,NaN,NaN,NaN,NaN,NaN
10,CITRONELLOL,NaN,CITRONELLOL,106-22-9,Citronellol,NaN,NaN,NaN,NaN,NaN
13,Limonene (1-methyl-4-prop-1-en-2-yl-cyclohexen...,5989-27-5,Limonene (1-methyl-4-prop-1-en-2-yl-cyclohexen...,5989-27-5,(+)-Limonene,NaN,NaN,NaN,NaN,NaN
15,"Aloe vera, non-decolorized (unfiltered) whole ...",NaN,"Aloe vera, non-decolorized (unfiltered) whole ...",8001-97-6,Aloe vera,NaN,NaN,NaN,NaN,NaN

In [45]:
na.to_csv("na_harms.csv")

In [46]:
na.groupby("Ingredient Name").size().rename("count").reset_index().head()

                                     Ingredient Name  count
0  1,1'-Sulfonylbis[3,5-dibromo-4-(2,3-dibromopro...      1
1  1,3-Dioxane, 2-(2,4-dimethyl-3-cyclohexen-1-yl...      1
2  1-(1,2,3,4,5,6,7,8-octahydro-2,3,8,8-tetrameth...      1
3  1-Methoxy-4-(1E)-1-propen-1-yl-benzene (trans-...      1
4  2,4-Hexadienal (89% trans, trans isomer; 11% c...      1

In [47]:
len(na)

146

In [48]:
na_cleaned = pd.read_csv("data/na_harms_cleaned.csv", encoding='latin-1')

In [49]:
na_cleaned

,Unnamed: 0,Ingredient Name,cas_number,clean_name,api_rn,api_name,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)"
0,0,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,8023-85-6,Cedrus Atlantica Oil,8023-85-6,Cedrus Atlantica Oil,Fragrance Allergen,Cedrus Atlantica Oil/Extract,Cedrus atlanticaÊoil and extract; Cedrus Atlan...,Annex III of the EU Cosmetics Regulation No. 1...,FA
1,4,Turpentine gum (PinusÂ spp.); Turpentine oil a...,9005-90-7,Turpentine,9005-90-7,Turpentine,Fragrance Allergen,Turpentine gum (PinusÊspp.); Turpentine oil an...,Turpentine,Annex III of the EU Cosmetics Regulation No. 1...,FA
2,10,CITRONELLOL,NaN,CITRONELLOL,106-22-9,Citronellol,Fragrance Allergen,"Citronellol /+- 3,7-dimethyloct-6-en-1-ol","CITRONELLOL; (3R)-3,7-dimethyloct-6-en-1-ol; (...",Annex III of the EU Cosmetics Regulation No. 1...,FA
3,13,Limonene (1-methyl-4-prop-1-en-2-yl-cyclohexen...,5989-27-5,Limonene (1-methyl-4-prop-1-en-2-yl-cyclohexen...,5989-27-5,(+)-Limonene,Fragrance Allergen,Limonene,1-methyl-4-prop-1-en-2-yl-cyclohexene; dl-limo...,Annex III of the EU Cosmetics Regulation No. 1...,FA
4,15,"Aloe vera, non-decolorized (unfiltered) whole ...",NaN,"Aloe vera, non-decolorized (unfiltered) whole ...",8001-97-6,Aloe vera,Carcinogenicity,"Aloe vera, non-decolorized whole leaf extract",NaN,IARC Carcinogens - 2B; Prop 65,Any
...,...,...,...,...,...,...,...,...,...,...,...
145,500,Goldenseal root powder,NaN,Goldenseal root powder,NaN,Goldenseal root powder,Carcinogenicity,NaN,NaN,IARC Carcinogens - 2B; Prop 65,Any
146,504,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,92201-55-3,Cedrus Atlantica Oil Extract (Cedrus atlantica...,92201-55-3,"Cedrus atlantica, ext.",Fragrance Allergen,Cedrus Atlantica Oil/Extract,Cedrus atlanticaÊoil and extract; Cedrus Atlan...,Annex III of the EU Cosmetics Regulation No. 1...,NaN
147,508,"Alcoholic beverages, when associated with alco...",64-17-5,Ethyl alcohol in alcoholic beverages (Ethanol ...,64-17-5,Ethanol,Hazard Trait Undefined,NaN,NaN,NaN,NaN
148,512,Myristamide DEA 7545-23-5,7545-23-5,Myristamide DEA,7545-23-5,Myristic acid diethanolamide,Hazard Trait Undefined,NaN,NaN,NaN,NaN
149,516,Turpentine gum (PinusÊspp.); Turpentine oil an...,9005-90-7,Turpentine gum (Pinus spp.); Turpentine oil an...,9005-90-7,Turpentine,Fragrance Allergen,Turpentine gum (PinusÊspp.); Turpentine oil an...,Turpentine,Annex III of the EU Cosmetics Regulation No. 1...,NaN

In [50]:
len(na_cleaned)

150

In [51]:
hazards_merged = pd.concat([result, na_cleaned])

In [52]:
len(hazards_merged)

509

In [53]:
hazards_merged.info()

<class 'pandas.core.frame.DataFrame'>
Index: 509 entries, 1 to 149
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Ingredient Name               508 non-null    object
 1   cas_number                    390 non-null    object
 2   clean_name                    508 non-null    object
 3   api_rn                        497 non-null    object
 4   api_name                      508 non-null    object
 5   Hazard Traits                 509 non-null    object
 6   Chemical Name                 441 non-null    object
 7   Synonyms                      294 non-null    object
 8   Authoritative List            470 non-null    object
 9   When to Report (Any, FF, FA)  467 non-null    object
 10  Unnamed: 0                    150 non-null    float64
dtypes: float64(1), object(10)
memory usage: 47.7+ KB

In [54]:
hazards_merged

,Ingredient Name,cas_number,clean_name,api_rn,api_name,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)",Unnamed: 0
1,"[3R-(3a,3aß,7ß,8aa)]-1-(2,3,4,7,8,8a-hexahydro...",32388-55-9,Acetylcedrene,32388-55-9,Acetylcedrene,Fragrance Allergen,"[3R-(3α,3aβ,7β,8aα)]-1-(2,3,4,7,8,8a-hexahydro...",Acetyl Cedrene,Annex III of the EU Cosmetics Regulation No. 1...,FA,NaN
2,"1-Naphthalenepropanol, a-ethenyldecahydro- 2-h...",515-03-7,Sclareol,515-03-7,Sclareol,Bioaccumulation; Environmental Persistence; Fr...,"1-Naphthalenepropanol, a-ethenyldecahydro- 2-h...",Sclareol; [1R-(1alpha)]-alpha-Ethenyldecahydro...,Annex III of the EU Cosmetics Regulation No. 1...,"FA, FF",NaN
3,Myroxylon Pereirae Oil/Extract (Myroxylon bals...,8007-00-9,Myroxylon Pereirae Oil/Extract,8007-00-9,Myroxylon Pereirae Oil/Extract,Fragrance Allergen,Myroxylon Pereirae Oil/Extract,Myroxylon balsamum var. pereirae; extracts and...,Annex III of the EU Cosmetics Regulation No. 1...,FA,NaN
5,Butane (containing greater than or equal to 0...,106-97-8,Butane,106-97-8,Butane,Carcinogenicity; Genotoxicity,"Butane (containing ≥ 0,1 % butadiene (203-450-8))",None,EC Annex VI CMRs - Cat. 1A; EC Annex VI CMRs -...,FF,NaN
6,Pinus Mugo (Pinus mugo leaf and twig oil and e...,90082-72-7,"Pine, Pinus mugo, ext.",90082-72-7,"Pine, Pinus mugo, ext.",Fragrance Allergen,Pinus Mugo,Pinus mugo leaf and twig oil and extract; Pinu...,Annex III of the EU Cosmetics Regulation No. 1...,FA,NaN
...,...,...,...,...,...,...,...,...,...,...,...
145,Goldenseal root powder,NaN,Goldenseal root powder,NaN,Goldenseal root powder,Carcinogenicity,NaN,NaN,IARC Carcinogens - 2B; Prop 65,Any,500.0
146,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,92201-55-3,Cedrus Atlantica Oil Extract (Cedrus atlantica...,92201-55-3,"Cedrus atlantica, ext.",Fragrance Allergen,Cedrus Atlantica Oil/Extract,Cedrus atlanticaÊoil and extract; Cedrus Atlan...,Annex III of the EU Cosmetics Regulation No. 1...,NaN,504.0
147,"Alcoholic beverages, when associated with alco...",64-17-5,Ethyl alcohol in alcoholic beverages (Ethanol ...,64-17-5,Ethanol,Hazard Trait Undefined,NaN,NaN,NaN,NaN,508.0
148,Myristamide DEA 7545-23-5,7545-23-5,Myristamide DEA,7545-23-5,Myristic acid diethanolamide,Hazard Trait Undefined,NaN,NaN,NaN,NaN,512.0
149,Turpentine gum (PinusÊspp.); Turpentine oil an...,9005-90-7,Turpentine gum (Pinus spp.); Turpentine oil an...,9005-90-7,Turpentine,Fragrance Allergen,Turpentine gum (PinusÊspp.); Turpentine oil an...,Turpentine,Annex III of the EU Cosmetics Regulation No. 1...,NaN,516.0

In [55]:

len(all_data)

534508

In [56]:
all_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 534508 entries, 0 to 534507
Data columns (total 13 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Product Id                 534508 non-null  int64
 1   Company                    534508 non-null  object
 2   Brand                      534308 non-null  object
 3   Product Name               534508 non-null  object
 4   Variant                    187813 non-null  object
 5   Product Discontinued Date  39102 non-null   object
 6   Product Submitted Date     534508 non-null  object
 7   Ingredient Name            534186 non-null  object
 8   Function                   433384 non-null  object
 9   Unit of Measure            222747 non-null  object
 10  Concentration              224495 non-null  object
 11  Ingredient Submitted Date  534186 non-null  object
 12  Ingredient Removed Date    6627 non-null    object
dtypes: int64(1), object(12)
memory usage: 53.0+ MB

In [57]:
all_data.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,Concentration,Ingredient Submitted Date,Ingredient Removed Date
0,18358,Nail Alliance - Entity,Entity Nudite,Cool Pink Nail Sculpting Powder,NaN,NaN,6/24/2019,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,5.000000,6/24/2019,NaN
1,38661,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,40.000000,9/21/2015,NaN
2,38662,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Sprinkle,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,31.000000,9/21/2015,NaN
3,38667,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,12.000000,9/21/2015,NaN
4,38665,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,21.500000,9/21/2015,NaN

In [58]:
final_merge = all_data.merge(hazards_merged, on = "Ingredient Name", how = 'left')

In [59]:
final_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 534514 entries, 0 to 534513
Data columns (total 23 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Product Id                    534514 non-null  int64
 1   Company                       534514 non-null  object
 2   Brand                         534314 non-null  object
 3   Product Name                  534514 non-null  object
 4   Variant                       187814 non-null  object
 5   Product Discontinued Date     39104 non-null   object
 6   Product Submitted Date        534514 non-null  object
 7   Ingredient Name               534192 non-null  object
 8   Function                      433390 non-null  object
 9   Unit of Measure               222748 non-null  object
 10  Concentration                 224496 non-null  object
 11  Ingredient Submitted Date     534192 non-null  object
 12  Ingredient Removed Date       6627 non-null    object
 13  cas_number                    447311 non-null  object
 14  clean_name                    533878 non-null  object
 15  api_rn                        532242 non-null  object
 16  api_name                      533878 non-null  object
 17  Hazard Traits                 534200 non-null  object
 18  Chemical Name                 527158 non-null  object
 19  Synonyms                      454215 non-null  object
 20  Authoritative List            530637 non-null  object
 21  When to Report (Any, FF, FA)  529833 non-null  object
 22  Unnamed: 0                    157739 non-null  float64
dtypes: float64(1), int64(1), object(21)
memory usage: 93.8+ MB

In [60]:
na_final =final_merge[final_merge["Hazard Traits"].isna()]
len(na_final)

314

In [61]:
final_merge.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,...,cas_number,clean_name,api_rn,api_name,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)",Unnamed: 0
0,18358,Nail Alliance - Entity,Entity Nudite,Cool Pink Nail Sculpting Powder,NaN,NaN,6/24/2019,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN
1,38661,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN
2,38662,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Sprinkle,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN
3,38667,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN
4,38665,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN

In [62]:
na_final.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,...,cas_number,clean_name,api_rn,api_name,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)",Unnamed: 0
896,115795,Davines S.p.A.,[comfort zone],[comfort zone] - AROMASOUL INDIAN blend,NaN,NaN,9/8/2022,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,Fragrance,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1217,135693,Davines S.p.A.,[comfort zone],[comfort zone] - TRANQUILLITYTM eau de toilette,NaN,NaN,5/30/2024,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,Fragrance,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1381,170568,Davines S.p.A.,[comfort zone],[comfort zone] – TRANQUILLITYTM magnesium body...,NaN,NaN,11/27/2025,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,Fragrance,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1432,151733,"ONEOSEVEN Co., Ltd.",107,SCALP PURIFYING Microbiome Shampoo,NaN,NaN,3/16/2025,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,Fragrance,Percent,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2552,171817,"Fourcompany Co.,Ltd.",Abib,Abib Airy clear Sunscreen gel Smoothing tube,NaN,NaN,12/18/2025,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,Conditioning/Emollient,Percent,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
harm_updates = {
    'Cedrus Atlantica Oil/Extract (Cedrus atlantica\xa0oil and extract; Cedrus Atlantica Bark Extract; Cedrus Atlantica Bark Oil; Cedrus Atlantica Bark Water; Cedrus Atlantica Leaf Extract; Cedrus Atlantica Wood Extract; Cedrus Atlantica Wood Oil) 92201-55-3 / 8023-85-6': 'Fragrance Allergen',
    'Alcoholic beverages, when associated with alcohol abuse': 'Hazard Trait Undefined',
    'Myristamide DEA 7545-23-5 ': 'Hazard Trait Undefined',
    'Turpentine gum (Pinus\xa0spp.); Turpentine oil and rectified oil; Turpentine, steam distilled (Pinus\xa0spp.) (Turpentine) 9005-90-7 / 8006-64-2 / 8052-14-0': 'Hazard Trait Undefined',
}

for ingredient, hazard in harm_updates.items():
    final_merge.loc[final_merge['Ingredient Name'].str.contains(ingredient, na=False, regex = False), 'Hazard Traits'] = hazard

In [64]:
final_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 534514 entries, 0 to 534513
Data columns (total 23 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Product Id                    534514 non-null  int64
 1   Company                       534514 non-null  object
 2   Brand                         534314 non-null  object
 3   Product Name                  534514 non-null  object
 4   Variant                       187814 non-null  object
 5   Product Discontinued Date     39104 non-null   object
 6   Product Submitted Date        534514 non-null  object
 7   Ingredient Name               534192 non-null  object
 8   Function                      433390 non-null  object
 9   Unit of Measure               222748 non-null  object
 10  Concentration                 224496 non-null  object
 11  Ingredient Submitted Date     534192 non-null  object
 12  Ingredient Removed Date       6627 non-null    object
 13  cas_number                    447311 non-null  object
 14  clean_name                    533878 non-null  object
 15  api_rn                        532242 non-null  object
 16  api_name                      533878 non-null  object
 17  Hazard Traits                 534514 non-null  object
 18  Chemical Name                 527158 non-null  object
 19  Synonyms                      454215 non-null  object
 20  Authoritative List            530637 non-null  object
 21  When to Report (Any, FF, FA)  529833 non-null  object
 22  Unnamed: 0                    157739 non-null  float64
dtypes: float64(1), int64(1), object(21)
memory usage: 93.8+ MB

In [65]:
final_merge["Hazard Traits"]

0         Carcinogenicity
1         Carcinogenicity
2         Carcinogenicity
3         Carcinogenicity
4         Carcinogenicity
               ...
534509    Carcinogenicity
534510    Carcinogenicity
534511    Carcinogenicity
534512    Carcinogenicity
534513    Carcinogenicity
Name: Hazard Traits, Length: 534514, dtype: object

In [66]:
final_merge.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,...,cas_number,clean_name,api_rn,api_name,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)",Unnamed: 0
0,18358,Nail Alliance - Entity,Entity Nudite,Cool Pink Nail Sculpting Powder,NaN,NaN,6/24/2019,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN
1,38661,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN
2,38662,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Sprinkle,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN
3,38667,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN
4,38665,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN

In [67]:
final_merge

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,...,cas_number,clean_name,api_rn,api_name,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)",Unnamed: 0
0,18358,Nail Alliance - Entity,Entity Nudite,Cool Pink Nail Sculpting Powder,NaN,NaN,6/24/2019,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN
1,38661,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN
2,38662,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Sprinkle,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN
3,38667,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN
4,38665,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534509,71004,J. Strickland & Co.,Zuri Naturally Sheer,Wet/ Dry Pressed Powder - Moroccan Bronze,NaN,5/17/2012,12/3/2009,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN
534510,71016,J. Strickland & Co.,Zuri Naturally Sheer,"Wet/ Dry Pressed Powder, Sahara Sunset",NaN,5/17/2012,12/3/2009,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN
534511,71013,J. Strickland & Co.,Zuri Naturally Sheer,Wet/Dry Powder - Caribbean Creme,NaN,5/17/2012,12/3/2009,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN
534512,71008,J. Strickland & Co.,Zuri Naturally Sheer,Wet/Dry Powder - Willow Soft,NaN,5/17/2012,12/3/2009,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN
534513,71002,J. Strickland & Co.,Zuri Naturally Sheer,Wet/Dry Pressed Powder - Fresh Hazelnut,NaN,5/17/2012,12/3/2009,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN

In [68]:
final_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 534514 entries, 0 to 534513
Data columns (total 23 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Product Id                    534514 non-null  int64
 1   Company                       534514 non-null  object
 2   Brand                         534314 non-null  object
 3   Product Name                  534514 non-null  object
 4   Variant                       187814 non-null  object
 5   Product Discontinued Date     39104 non-null   object
 6   Product Submitted Date        534514 non-null  object
 7   Ingredient Name               534192 non-null  object
 8   Function                      433390 non-null  object
 9   Unit of Measure               222748 non-null  object
 10  Concentration                 224496 non-null  object
 11  Ingredient Submitted Date     534192 non-null  object
 12  Ingredient Removed Date       6627 non-null    object
 13  cas_number                    447311 non-null  object
 14  clean_name                    533878 non-null  object
 15  api_rn                        532242 non-null  object
 16  api_name                      533878 non-null  object
 17  Hazard Traits                 534514 non-null  object
 18  Chemical Name                 527158 non-null  object
 19  Synonyms                      454215 non-null  object
 20  Authoritative List            530637 non-null  object
 21  When to Report (Any, FF, FA)  529833 non-null  object
 22  Unnamed: 0                    157739 non-null  float64
dtypes: float64(1), int64(1), object(21)
memory usage: 93.8+ MB

In [69]:
# Strip whitespace, split on semicolon, explode into rows
final_merge_explode = final_merge.copy()
final_merge_explode["Hazard Traits"] = final_merge_explode["Hazard Traits"].str.split(";")
final_merge_explode = final_merge_explode.explode("Hazard Traits")
final_merge_explode["Hazard Traits"] = final_merge_explode["Hazard Traits"].str.strip()
final_merge_explode = final_merge_explode.reset_index(drop=True)

In [70]:
len(final_merge_explode)

575438

In [71]:
final_merge_explode.drop_duplicates()
final_merge_explode.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,...,cas_number,clean_name,api_rn,api_name,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)",Unnamed: 0
0,18358,Nail Alliance - Entity,Entity Nudite,Cool Pink Nail Sculpting Powder,NaN,NaN,6/24/2019,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN
1,38661,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN
2,38662,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Sprinkle,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN
3,38667,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN
4,38665,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN

In [72]:
len(final_merge_explode)

575438

In [73]:
final_merge_explode.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 575438 entries, 0 to 575437
Data columns (total 23 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Product Id                    575438 non-null  int64
 1   Company                       575438 non-null  object
 2   Brand                         575226 non-null  object
 3   Product Name                  575438 non-null  object
 4   Variant                       203843 non-null  object
 5   Product Discontinued Date     42061 non-null   object
 6   Product Submitted Date        575438 non-null  object
 7   Ingredient Name               575116 non-null  object
 8   Function                      468304 non-null  object
 9   Unit of Measure               244410 non-null  object
 10  Concentration                 246257 non-null  object
 11  Ingredient Submitted Date     575116 non-null  object
 12  Ingredient Removed Date       8310 non-null    object
 13  cas_number                    482819 non-null  object
 14  clean_name                    574802 non-null  object
 15  api_rn                        572434 non-null  object
 16  api_name                      574802 non-null  object
 17  Hazard Traits                 575438 non-null  object
 18  Chemical Name                 567630 non-null  object
 19  Synonyms                      480886 non-null  object
 20  Authoritative List            571324 non-null  object
 21  When to Report (Any, FF, FA)  570520 non-null  object
 22  Unnamed: 0                    169831 non-null  float64
dtypes: float64(1), int64(1), object(21)
memory usage: 101.0+ MB

In [74]:
final_merge_explode["final_name"] = final_merge_explode["api_name"].fillna(final_merge_explode["Product Name"])

In [75]:
final_merge_explode.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,...,clean_name,api_rn,api_name,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)",Unnamed: 0,final_name
0,18358,Nail Alliance - Entity,Entity Nudite,Cool Pink Nail Sculpting Powder,NaN,NaN,6/24/2019,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania
1,38661,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania
2,38662,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Sprinkle,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania
3,38667,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania
4,38665,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania

In [76]:
final_merge_explode.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,...,clean_name,api_rn,api_name,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)",Unnamed: 0,final_name
0,18358,Nail Alliance - Entity,Entity Nudite,Cool Pink Nail Sculpting Powder,NaN,NaN,6/24/2019,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania
1,38661,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania
2,38662,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Sprinkle,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania
3,38667,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania
4,38665,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania

In [77]:
final_merge_explode.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,...,clean_name,api_rn,api_name,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)",Unnamed: 0,final_name
0,18358,Nail Alliance - Entity,Entity Nudite,Cool Pink Nail Sculpting Powder,NaN,NaN,6/24/2019,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania
1,38661,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania
2,38662,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Sprinkle,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania
3,38667,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania
4,38665,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania

In [78]:
final_merge_explode["Product Discontinued Date"] = pd.to_datetime(final_merge_explode['Product Discontinued Date'])
final_merge_explode['Product Discontinued Year'] = final_merge_explode['Product Discontinued Date'].dt.year
final_merge_explode["Product Submitted Date"] = pd.to_datetime(final_merge_explode['Product Submitted Date'])
final_merge_explode['Product Submitted Year'] = final_merge_explode['Product Submitted Date'].dt.year
final_merge_explode["Ingredient Submitted Date"] = pd.to_datetime(final_merge_explode['Ingredient Submitted Date'])
final_merge_explode['Ingredient Submitted Year'] = final_merge_explode['Ingredient Submitted Date'].dt.year
final_merge_explode["Ingredient Removed Date"] = pd.to_datetime(final_merge_explode['Ingredient Removed Date'])
final_merge_explode['Ingredient Removed Year'] = final_merge_explode['Ingredient Removed Date'].dt.year

In [79]:
final_merge_explode['Ingredient Submitted Year'] = final_merge_explode['Ingredient Submitted Year'].astype('Int64')
final_merge_explode['Product Submitted Year'] = final_merge_explode['Product Submitted Year'].astype('Int64')
final_merge_explode['Ingredient Removed Year'] = final_merge_explode['Ingredient Removed Year'].astype('Int64')
final_merge_explode['Product Discontinued Year'] = final_merge_explode['Product Discontinued Year'].astype('Int64')

In [80]:
final_merge_explode.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,...,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)",Unnamed: 0,final_name,Product Discontinued Year,Product Submitted Year,Ingredient Submitted Year,Ingredient Removed Year
0,18358,Nail Alliance - Entity,Entity Nudite,Cool Pink Nail Sculpting Powder,NaN,NaT,2019-06-24,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania,<NA>,2019,2019,<NA>
1,38661,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Solid,NaT,2015-09-21,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania,<NA>,2015,2015,<NA>
2,38662,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Sprinkle,NaT,2015-09-21,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania,<NA>,2015,2015,<NA>
3,38667,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaT,2015-09-21,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania,<NA>,2015,2015,<NA>
4,38665,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaT,2015-09-21,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania,<NA>,2015,2015,<NA>

In [81]:
final_merge_explode = final_merge_explode.drop(columns=["Ingredient Submitted Date", "Ingredient Removed Date", "Product Discontinued Date", "Product Submitted Date"])

In [82]:
final_merge_explode.head()

,Product Id,Company,Brand,Product Name,Variant,Ingredient Name,Function,Unit of Measure,Concentration,cas_number,...,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)",Unnamed: 0,final_name,Product Discontinued Year,Product Submitted Year,Ingredient Submitted Year,Ingredient Removed Year
0,18358,Nail Alliance - Entity,Entity Nudite,Cool Pink Nail Sculpting Powder,NaN,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,5.000000,13463-67-7,...,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania,<NA>,2019,2019,<NA>
1,38661,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Solid,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,40.000000,13463-67-7,...,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania,<NA>,2015,2015,<NA>
2,38662,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Sprinkle,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,31.000000,13463-67-7,...,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania,<NA>,2015,2015,<NA>
3,38667,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,12.000000,13463-67-7,...,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania,<NA>,2015,2015,<NA>
4,38665,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,21.500000,13463-67-7,...,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania,<NA>,2015,2015,<NA>

In [83]:
hazard_map = {
    "Endocrine toxicity": "Endocrine Toxicity",
    "Environmental tox": "Environmental Toxicity"
}

In [84]:
final_merge_explode["Hazard Traits"] = final_merge_explode["Hazard Traits"].replace(hazard_map)

In [85]:
hazard_count = final_merge_explode.groupby("Hazard Traits")["Product Id"].nunique().rename("count").reset_index()
hazard_count = hazard_count.sort_values("count", ascending = False)

In [86]:
hazard_year = final_merge_explode.groupby(["Product Submitted Year", "Hazard Traits"])["Product Id"].nunique().rename("count").reset_index()
hazard_year.to_csv("website/charts/hazardbyyear.csv", index = False)

In [87]:
import altair as alt

In [88]:
alt.Chart(hazard_year).mark_bar().encode(
    x = "Product Submitted Year",
    y = "count",
    color = "Hazard Traits:N"
)

alt.Chart(...)

In [89]:
ingreds = final_merge_explode.groupby("final_name").size().rename("count").reset_index()
ingreds.sort_values("count", ascending = False).head(10)

                 final_name  count
805                 Titania  99128
8             (¬±)-Linalool  44423
2              (+)-Limonene  42034
225             Citronellol  25768
394                Geraniol  23636
223                  Citral  19064
163          Benzyl alcohol  17246
882  Œ±-Hexylcinnamaldehyde  17131
252                Coumarin  16979
167       Benzyl salicylate  15145

In [90]:
final_merge_explode[final_merge_explode["final_name"] == "Titania"][["final_name", "Hazard Traits"]].drop_duplicates()

  final_name    Hazard Traits
0    Titania  Carcinogenicity

In [91]:
final_merge_explode[final_merge_explode["final_name"] == "(¬±)-Linalool"][["final_name", "Hazard Traits"]].drop_duplicates()

       final_name       Hazard Traits
22  (¬±)-Linalool  Fragrance Allergen

In [92]:
final_merge_explode[final_merge_explode["final_name"] == "(+)-Limonene"][["final_name", "Hazard Traits"]].drop_duplicates()

      final_name       Hazard Traits
24  (+)-Limonene  Fragrance Allergen

In [93]:
final_merge_explode[final_merge_explode["final_name"] == "Citronellol"][["final_name", "Hazard Traits"]].drop_duplicates()

     final_name       Hazard Traits
21  Citronellol  Fragrance Allergen

In [94]:
final_merge_explode[final_merge_explode["final_name"] == "Geraniol"][["final_name", "Hazard Traits"]].drop_duplicates()

   final_name       Hazard Traits
64   Geraniol  Fragrance Allergen

In [95]:
final_merge_explode[final_merge_explode["final_name"] == "Citral"][["final_name", "Hazard Traits"]].drop_duplicates()

   final_name       Hazard Traits
63     Citral  Fragrance Allergen

In [96]:
final_merge_explode[final_merge_explode["final_name"] == "Benzyl alcohol"][["final_name", "Hazard Traits"]].drop_duplicates()

         final_name       Hazard Traits
213  Benzyl alcohol  Fragrance Allergen

In [97]:
final_merge_explode[final_merge_explode["final_name"] == "Œ±-Hexylcinnamaldehyde"][["final_name", "Hazard Traits"]].drop_duplicates()

                final_name       Hazard Traits
23  Œ±-Hexylcinnamaldehyde  Fragrance Allergen

In [98]:
final_merge_explode[final_merge_explode["final_name"] == "Benzyl salicylate"][["final_name", "Hazard Traits"]].drop_duplicates()

            final_name       Hazard Traits
216  Benzyl salicylate  Fragrance Allergen

In [99]:
final_merge_explode.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 575438 entries, 0 to 575437
Data columns (total 24 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Product Id                    575438 non-null  int64
 1   Company                       575438 non-null  object
 2   Brand                         575226 non-null  object
 3   Product Name                  575438 non-null  object
 4   Variant                       203843 non-null  object
 5   Ingredient Name               575116 non-null  object
 6   Function                      468304 non-null  object
 7   Unit of Measure               244410 non-null  object
 8   Concentration                 246257 non-null  object
 9   cas_number                    482819 non-null  object
 10  clean_name                    574802 non-null  object
 11  api_rn                        572434 non-null  object
 12  api_name                      574802 non-null  object
 13  Hazard Traits                 575438 non-null  object
 14  Chemical Name                 567630 non-null  object
 15  Synonyms                      480886 non-null  object
 16  Authoritative List            571324 non-null  object
 17  When to Report (Any, FF, FA)  570520 non-null  object
 18  Unnamed: 0                    169831 non-null  float64
 19  final_name                    575438 non-null  object
 20  Product Discontinued Year     42061 non-null   Int64
 21  Product Submitted Year        575438 non-null  Int64
 22  Ingredient Submitted Year     575116 non-null  Int64
 23  Ingredient Removed Year       8310 non-null    Int64
dtypes: Int64(4), float64(1), int64(1), object(18)
memory usage: 107.6+ MB

In [100]:
brand_sub = final_merge_explode.groupby("Brand")["Product Id"].nunique().rename("count").reset_index()
brand_sub.sort_values("count", ascending = False)

                                      Brand  count
551                       Bath & Body Works   7007
3448                               Sephora    3679
4136               Victoria's Secret Beauty   3171
4326                           bareMinerals   2605
2607                                   NARS   2569
...                                     ...    ...
923                     Christian Louboutin      1
2597       NARCISO RODRIGUEZ - JASMINE MUSC      1
2598  NARCISO RODRIGUEZ - MUSC NOIR FOR HER      1
928                               Chromatic      1
0                             Entity Nudite      1

[4448 rows x 2 columns]

In [101]:
discontinued_year = final_merge_explode.groupby("Product Discontinued Year")["Product Id"].nunique().rename("count").reset_index()
discontinued_year = discontinued_year[discontinued_year["Product Discontinued Year"] < 2026]

In [102]:
discontinued_year

    Product Discontinued Year  count
0                        2001      2
1                        2004     21
2                        2005      6
3                        2006     14
4                        2007    158
5                        2008    294
6                        2009    629
7                        2010    956
8                        2011   1092
9                        2012    793
10                       2013   2809
11                       2014   1992
12                       2015   1246
13                       2016   1989
14                       2017    886
15                       2018    686
16                       2019    616
17                       2020    477
18                       2021    897
19                       2022   1856
20                       2023   2454
21                       2024   1089
22                       2025   2042

In [103]:
import altair as alt

In [104]:
alt.Chart(discontinued_year).mark_line().encode(
    x = "Product Discontinued Year",
    y = "count"
)

alt.Chart(...)

In [105]:
final_merge_explode["Company"].nunique()

1396

In [106]:
final_merge_explode["Brand"].nunique()

4448

In [107]:
final_merge_explode["Product Id"].nunique()

165503

In [108]:
final_merge_explode["final_name"].nunique()

885

In [109]:
final_merge_explode.to_csv("data/viz_main_table.csv")

In [110]:
submission_year = final_merge_explode.groupby("Product Submitted Year")["Product Id"].nunique().rename("count").reset_index()
submission_year = submission_year[submission_year["Product Submitted Year"] < 2026]
submission_year.to_csv('website/charts/prodsbyyear.csv', index=False)

In [111]:
submission_year["count"].sum()

np.int64(165177)

In [112]:
cats = pd.read_csv("data/categories_table.csv")

In [113]:
viz_table = pd.merge(final_merge_explode, cats, how = "left", on = "Product Id" )

In [114]:
pd.set_option('display.max_columns', None)

In [115]:
viz_table.head()

,Product Id,Company,Brand,Product Name,Variant,Ingredient Name,Function,Unit of Measure,Concentration,cas_number,clean_name,api_rn,api_name,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)",Unnamed: 0_x,final_name,Product Discontinued Year,Product Submitted Year,Ingredient Submitted Year,Ingredient Removed Year,Unnamed: 0_y,Body Area,Product Category,Product Form
0,18358,Nail Alliance - Entity,Entity Nudite,Cool Pink Nail Sculpting Powder,NaN,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,5.000000,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania,<NA>,2019,2019,<NA>,0.0,Nails,Artificial Nails and Related Products,Powder
1,38661,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Solid,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,40.000000,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania,<NA>,2015,2015,<NA>,1.0,Eye Area,Eye Shadow,Powder
2,38662,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Sprinkle,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,31.000000,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania,<NA>,2015,2015,<NA>,2.0,Eye Area,Eye Shadow,Powder
3,38667,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,12.000000,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania,<NA>,2015,2015,<NA>,3.0,Eye Area,Eye Shadow,Powder
4,38665,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,21.500000,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania,<NA>,2015,2015,<NA>,4.0,Eye Area,Eye Shadow,Powder

In [116]:
viz_table["Hazard Traits"].unique()

array(['Carcinogenicity', 'Fragrance Allergen', 'Reproductive Toxicity',
       'Respiratory Toxicity', 'Bioaccumulation',
       'Environmental Persistence',
       'Hepatotoxicity and Digestive System Toxicity', 'Immunotoxicity',
       'Endocrine Toxicity', 'Developmental Toxicity',
       'Hazard Trait Undefined', 'Other Toxicological Hazard Traits',
       'Dermatotoxicity', 'Hematotoxicity', 'Ocular Toxicity',
       'Cardiovascular Toxicity',
       'Nephrotoxicity and Other Toxicity to the Urinary System',
       'Neurotoxicity', 'Genotoxicity', 'Environmental Toxicity',
       'Musculoskeletal Toxicity', 'Neurodevelopmental Toxicity'],
      dtype=object)

In [117]:
bod = viz_table.groupby("Body Area")["Product Id"].nunique().rename("product count").reset_index()
bod.sort_values("product count", ascending = False)

                      Body Area  product count
6                          Face          40368
0                Body (general)          33018
11                         Lips          28853
5                      Eye Area          22155
8                 Hair or Scalp          19117
12                        Nails          13615
9                         Hands           8379
13  Neck/chest/decolletage area           5267
14             Other (Specify):           3959
7                          Feet           2168
10                         Legs           1984
4                  Elbows/Knees           1535
2            Body Cavity (oral)            459
15           Vulva/genital area            179
1            Body Cavity (anal)             16
3         Body Cavity (vaginal)              6

In [118]:
body_area_map = {
    "Other (Specify):": "Other",
    "Body Cavity (anal)": "Other",
    "Body Cavity (vaginal)": "Other",
    "Vulva/genital area": "Other",
    "Body Cavity (oral)": "Other",
    "Body (general)": "Body"
}

In [119]:
bod = viz_table.groupby("Body Area")["Product Id"].nunique().rename("product count").reset_index()
bod["Body Area"] = bod["Body Area"].replace(body_area_map)
bod = bod.groupby("Body Area")["product count"].sum().reset_index()
bod = bod.sort_values("product count", ascending = False)
bod

                      Body Area  product count
3                          Face          40368
0                          Body          33018
8                          Lips          28853
2                      Eye Area          22155
5                 Hair or Scalp          19117
9                         Nails          13615
6                         Hands           8379
10  Neck/chest/decolletage area           5267
11                        Other           4619
4                          Feet           2168
7                          Legs           1984
1                  Elbows/Knees           1535

In [120]:

bod.to_csv("website/charts/body_area.csv", index=False)

In [121]:
bod["product count"].sum()

np.int64(181078)

In [122]:
categories = viz_table.groupby("Product Category")["Product Id"].nunique().rename("product count").reset_index()
cat_map = {
    "Lip Color - Lipsticks, Liners, and Pencils": "Lip Color",
    "Foundations and Bases": "Foundation & Base",
    "Nail Polish and Enamel": "Nail Polish & Enamel",
    "Skin Moisturizers (making a cosmetic claim)": "Moisturizer",
    "Body Washes and Soaps": "Body Wash",
    "Perfumes/Eaux de Parfum": "Perfume",
    "Face Powders": "Face Powder",
    "Lip Gloss/Shine": "Lip Gloss"
}
categories["Product Category"] = categories["Product Category"].replace(cat_map)
categories_10 = categories.sort_values("product count", ascending = False).head(10)

In [123]:
categories_10

            Product Category  product count
41                 Lip Color          17802
25         Foundation & Base          16900
18                Eye Shadow          14384
50      Nail Polish & Enamel          10635
42                 Lip Gloss           9567
79               Moisturizer           8808
11                 Body Wash           7217
68                   Perfume           6175
19  Eyeliner/Eyebrow Pencils           5593
20               Face Powder           5561

In [124]:
categories_10.to_csv("website/charts/top_10_cats.csv", index=False)

In [125]:
alt.Chart(categories).mark_bar().encode(
    x = "Product Category",
    y = "product count"
)

alt.Chart(...)

In [126]:
final_merge_explode["Brand"].nunique()

4448

In [127]:
final_merge.to_csv("final_hazard_merge_2_19.csv")

In [128]:
hazard_traits_clean = final_merge['Hazard Traits'].str.strip().str.lower().str.replace(r'\s*,\s*', '; ', regex=True)

hazard_dummies = (
    hazard_traits_clean
    .str.get_dummies(sep=';')
    .rename(columns=lambda x: x.strip().title())
)

# Collapse any duplicate columns
hazard_dummies = hazard_dummies.T.groupby(level=0).max().T.astype(bool)
pd.set_option("display.max_columns", None)
final_merge_expanded = pd.concat([final_merge, hazard_dummies], axis=1)
final_merge_expanded

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,Concentration,Ingredient Submitted Date,Ingredient Removed Date,cas_number,clean_name,api_rn,api_name,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)",Unnamed: 0,Bioaccumulation,Carcinogenicity,Cardiovascular Toxicity,Dermatotoxicity,Developmental Toxicity,Endocrine Toxicity,Environmental Persistence,Environmental Tox,Fragrance Allergen,Genotoxicity,Hazard Trait Undefined,Hematotoxicity,Hepatotoxicity And Digestive System Toxicity,Immunotoxicity,Musculoskeletal Toxicity,Nephrotoxicity And Other Toxicity To The Urinary System,Neurodevelopmental Toxicity,Neurotoxicity,Ocular Toxicity,Other Toxicological Hazard Traits,Reproductive Toxicity,Respiratory Toxicity
0,18358,Nail Alliance - Entity,Entity Nudite,Cool Pink Nail Sculpting Powder,NaN,NaN,6/24/2019,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,5.000000,6/24/2019,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,38661,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,40.000000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,38662,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Sprinkle,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,31.000000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,38667,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,12.000000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,38665,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,21.500000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534509,71004,J. Strickland & Co.,Zuri Naturally Sheer,Wet/ Dry Pressed Powder - Moroccan Bronze,NaN,5/17/2012,12/3/2009,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,10.000000,12/3/2009,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
534510,71016,J. Strickland & Co.,Zuri Naturally Sheer,"Wet/ Dry Pressed Powder, Sahara Sunset",NaN,5/17/2012,12/3/2009,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,10.000000,12/3/2009,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
534511,71013,J. Strickland & Co.,Zuri Naturally Sheer,Wet/Dry Powder - Caribbean Creme,NaN,5/17/2012,12/3/2009,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,10.000000,12/3/2009,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
534512,71008,J. Strickland & Co.,Zuri Naturally Sheer,Wet/Dry Powder - Willow Soft,NaN,5/17/2012,12/3/2009,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,10.000000,12/3/2009,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
534513,71002,J. Strickland & Co.,Zuri Naturally Sheer,Wet/Dry Pressed Powder - Fresh Hazelnut,NaN,5/17/2012,12/3/2009,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,10.000000,12/3/2009,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [129]:
final_merge_expanded[final_merge_expanded["Product Id"] == 88706]

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,Concentration,Ingredient Submitted Date,Ingredient Removed Date,cas_number,clean_name,api_rn,api_name,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)",Unnamed: 0,Bioaccumulation,Carcinogenicity,Cardiovascular Toxicity,Dermatotoxicity,Developmental Toxicity,Endocrine Toxicity,Environmental Persistence,Environmental Tox,Fragrance Allergen,Genotoxicity,Hazard Trait Undefined,Hematotoxicity,Hepatotoxicity And Digestive System Toxicity,Immunotoxicity,Musculoskeletal Toxicity,Nephrotoxicity And Other Toxicity To The Urinary System,Neurodevelopmental Toxicity,Neurotoxicity,Ocular Toxicity,Other Toxicological Hazard Traits,Reproductive Toxicity,Respiratory Toxicity
6129,88706,AG Hair Ltd,AG Hair,Deflect fast-dry heat protection,NaN,3/31/2022,10/27/2021,Limonene (1-methyl-4-prop-1-en-2-yl-cyclohexen...,Fragrance,Percent,0.071377,10/27/2021,NaN,5989-27-5,Limonene (1-methyl-4-prop-1-en-2-yl-cyclohexen...,5989-27-5,(+)-Limonene,Fragrance Allergen,Limonene,1-methyl-4-prop-1-en-2-yl-cyclohexene; dl-limo...,Annex III of the EU Cosmetics Regulation No. 1...,FA,13.0,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
6130,88706,AG Hair Ltd,AG Hair,Deflect fast-dry heat protection,NaN,3/31/2022,10/27/2021,LINALOOL,Fragrance,Percent,0.007156,10/27/2021,NaN,NaN,LINALOOL,78-70-6,(¬±)-Linalool,Fragrance Allergen,"1,6-Octadien-3-ol, 3,7-dimethyl-",LINALOOL,Annex III of the EU Cosmetics Regulation No. 1...,FA,NaN,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
6131,88706,AG Hair Ltd,AG Hair,Deflect fast-dry heat protection,NaN,3/31/2022,10/27/2021,CITRONELLOL,Fragrance,Percent,0.002384,10/27/2021,NaN,NaN,CITRONELLOL,106-22-9,Citronellol,Fragrance Allergen,"Citronellol /+- 3,7-dimethyloct-6-en-1-ol","CITRONELLOL; (3R)-3,7-dimethyloct-6-en-1-ol; (...",Annex III of the EU Cosmetics Regulation No. 1...,FA,10.0,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
6132,88706,AG Hair Ltd,AG Hair,Deflect fast-dry heat protection,NaN,3/31/2022,10/27/2021,COUMARIN,Fragrance,Percent,0.003476,10/27/2021,NaN,NaN,COUMARIN,91-64-5,Coumarin,Fragrance Allergen,2H-1-Benzopyran-2-one,COUMARIN,Annex III of the EU Cosmetics Regulation No. 1...,FA,NaN,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
6133,88706,AG Hair Ltd,AG Hair,Deflect fast-dry heat protection,NaN,3/31/2022,10/27/2021,Benzyl benzoate 120-51-4,Fragrance,Percent,0.055539,10/27/2021,NaN,120-51-4,Benzyl benzoate,120-51-4,Benzyl benzoate,Fragrance Allergen,Benzyl benzoate,None,Annex III of the EU Cosmetics Regulation No. 1...,FA,NaN,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
6134,88706,AG Hair Ltd,AG Hair,Deflect fast-dry heat protection,NaN,3/31/2022,10/27/2021,CITRAL,Fragrance,Percent,0.001549,10/27/2021,NaN,NaN,CITRAL,5392-40-5,Citral,Fragrance Allergen,Citral,"3,7-Dimethyl-2,6-octadienal; (E)-3,7-dimethylo...",Annex III of the EU Cosmetics Regulation No. 1...,FA,17.0,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False

In [130]:
final_merge_expanded.to_csv("hazard_reformatted_2_19.csv")

In [131]:
final_merge_expanded[final_merge_expanded["Product Id"] == 26454]

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,Concentration,Ingredient Submitted Date,Ingredient Removed Date,cas_number,clean_name,api_rn,api_name,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)",Unnamed: 0,Bioaccumulation,Carcinogenicity,Cardiovascular Toxicity,Dermatotoxicity,Developmental Toxicity,Endocrine Toxicity,Environmental Persistence,Environmental Tox,Fragrance Allergen,Genotoxicity,Hazard Trait Undefined,Hematotoxicity,Hepatotoxicity And Digestive System Toxicity,Immunotoxicity,Musculoskeletal Toxicity,Nephrotoxicity And Other Toxicity To The Urinary System,Neurodevelopmental Toxicity,Neurotoxicity,Ocular Toxicity,Other Toxicological Hazard Traits,Reproductive Toxicity,Respiratory Toxicity
9875,26454,Revlon Consumer Product Corporation,Almay,Almay 3-in-1 Matte Foundation,Neutral Sun Beige,NaN,8/12/2019,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/mL,7.200000,8/12/2019,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9876,26454,Revlon Consumer Product Corporation,Almay,Almay 3-in-1 Matte Foundation,Neutral Sun Beige,NaN,8/12/2019,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/mL,7.200000,8/12/2019,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [132]:
print(final_merge.columns.tolist())

['Product Id', 'Company', 'Brand', 'Product Name', 'Variant', 'Product Discontinued Date', 'Product Submitted Date', 'Ingredient Name', 'Function', 'Unit of Measure', 'Concentration', 'Ingredient Submitted Date', 'Ingredient Removed Date', 'cas_number', 'clean_name', 'api_rn', 'api_name', 'Hazard Traits', 'Chemical Name', 'Synonyms', 'Authoritative List', 'When to Report (Any, FF, FA)', 'Unnamed: 0']

In [133]:
prod_info = pd.read_csv("data/CDPH_ProdInfo.csv")

/var/folders/p6/tqnlcwnd075_z06_lxt45pv40000gn/T/ipykernel_8401/3474833877.py:1: DtypeWarning: Columns (5,9,10,12,13) have mixed types. Specify dtype option on import or set low_memory=False.
  prod_info = pd.read_csv("data/CDPH_ProdInfo.csv")

In [134]:
prod_info.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,Concentration,Ingredient Submitted Date,Ingredient Removed Date,UPC,Body Area,Product Category,Product Form,Intended Market
0,18358,Nail Alliance - Entity,Entity Nudite,Cool Pink Nail Sculpting Powder,NaN,NaN,6/24/2019,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,5.000000,6/24/2019,NaN,Not Available,Nails,Artificial Nails and Related Products,Powder,Not Available
1,38661,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,40.000000,9/21/2015,NaN,Not Available,Eye Area,Eye Shadow,Powder,Not Available
2,38662,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Sprinkle,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,31.000000,9/21/2015,NaN,Not Available,Eye Area,Eye Shadow,Powder,Not Available
3,38667,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,12.000000,9/21/2015,NaN,Not Available,Eye Area,Eye Shadow,Powder,Not Available
4,38665,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,21.500000,9/21/2015,NaN,Not Available,Eye Area,Eye Shadow,Powder,Not Available

In [135]:
prod_info["prod_name_combined"] = prod_info["Company"].astype(str)  + '_' + prod_info["Brand"].astype(str)  + '_' + prod_info["Product Name"].astype(str)  + '_' + prod_info["Variant"].astype(str)

In [136]:
prod_info.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,Concentration,Ingredient Submitted Date,Ingredient Removed Date,UPC,Body Area,Product Category,Product Form,Intended Market,prod_name_combined
0,18358,Nail Alliance - Entity,Entity Nudite,Cool Pink Nail Sculpting Powder,NaN,NaN,6/24/2019,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,5.000000,6/24/2019,NaN,Not Available,Nails,Artificial Nails and Related Products,Powder,Not Available,Nail Alliance - Entity_ Entity Nudite_Cool Pin...
1,38661,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,40.000000,9/21/2015,NaN,Not Available,Eye Area,Eye Shadow,Powder,Not Available,"Xtreme Color, Inc._ Hard Candy_Fierce Effects-..."
2,38662,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Sprinkle,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,31.000000,9/21/2015,NaN,Not Available,Eye Area,Eye Shadow,Powder,Not Available,"Xtreme Color, Inc._ Hard Candy_Fierce Effects-..."
3,38667,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,12.000000,9/21/2015,NaN,Not Available,Eye Area,Eye Shadow,Powder,Not Available,"Xtreme Color, Inc._ Hard Candy_Fierce Effects-..."
4,38665,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,21.500000,9/21/2015,NaN,Not Available,Eye Area,Eye Shadow,Powder,Not Available,"Xtreme Color, Inc._ Hard Candy_Fierce Effects-..."

In [137]:
final_merge_expanded.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,Concentration,Ingredient Submitted Date,Ingredient Removed Date,cas_number,clean_name,api_rn,api_name,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)",Unnamed: 0,Bioaccumulation,Carcinogenicity,Cardiovascular Toxicity,Dermatotoxicity,Developmental Toxicity,Endocrine Toxicity,Environmental Persistence,Environmental Tox,Fragrance Allergen,Genotoxicity,Hazard Trait Undefined,Hematotoxicity,Hepatotoxicity And Digestive System Toxicity,Immunotoxicity,Musculoskeletal Toxicity,Nephrotoxicity And Other Toxicity To The Urinary System,Neurodevelopmental Toxicity,Neurotoxicity,Ocular Toxicity,Other Toxicological Hazard Traits,Reproductive Toxicity,Respiratory Toxicity
0,18358,Nail Alliance - Entity,Entity Nudite,Cool Pink Nail Sculpting Powder,NaN,NaN,6/24/2019,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,5.000000,6/24/2019,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,38661,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,40.000000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,38662,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Sprinkle,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,31.000000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,38667,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,12.000000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,38665,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,21.500000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [138]:
cats = pd.read_csv("database tables/categories_table.csv")

In [139]:
merge_data = pd.merge(final_merge_expanded, cats, on = "Product Id", how = "left")

In [140]:
merge_data.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,Concentration,Ingredient Submitted Date,Ingredient Removed Date,cas_number,clean_name,api_rn,api_name,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)",Unnamed: 0_x,Bioaccumulation,Carcinogenicity,Cardiovascular Toxicity,Dermatotoxicity,Developmental Toxicity,Endocrine Toxicity,Environmental Persistence,Environmental Tox,Fragrance Allergen,Genotoxicity,Hazard Trait Undefined,Hematotoxicity,Hepatotoxicity And Digestive System Toxicity,Immunotoxicity,Musculoskeletal Toxicity,Nephrotoxicity And Other Toxicity To The Urinary System,Neurodevelopmental Toxicity,Neurotoxicity,Ocular Toxicity,Other Toxicological Hazard Traits,Reproductive Toxicity,Respiratory Toxicity,Unnamed: 0_y,Body Area,Product Category,Product Form
0,18358,Nail Alliance - Entity,Entity Nudite,Cool Pink Nail Sculpting Powder,NaN,NaN,6/24/2019,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,5.000000,6/24/2019,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0.0,Nails,Artificial Nails and Related Products,Powder
1,38661,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,40.000000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,1.0,Eye Area,Eye Shadow,Powder
2,38662,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Sprinkle,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,31.000000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,2.0,Eye Area,Eye Shadow,Powder
3,38667,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,12.000000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,3.0,Eye Area,Eye Shadow,Powder
4,38665,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,21.500000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,4.0,Eye Area,Eye Shadow,Powder

In [141]:
rep = merge_data[merge_data["Reproductive Toxicity"] == True]

In [142]:
len(rep)

580231

In [143]:
rep.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,Concentration,Ingredient Submitted Date,Ingredient Removed Date,cas_number,clean_name,api_rn,api_name,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)",Unnamed: 0_x,Bioaccumulation,Carcinogenicity,Cardiovascular Toxicity,Dermatotoxicity,Developmental Toxicity,Endocrine Toxicity,Environmental Persistence,Environmental Tox,Fragrance Allergen,Genotoxicity,Hazard Trait Undefined,Hematotoxicity,Hepatotoxicity And Digestive System Toxicity,Immunotoxicity,Musculoskeletal Toxicity,Nephrotoxicity And Other Toxicity To The Urinary System,Neurodevelopmental Toxicity,Neurotoxicity,Ocular Toxicity,Other Toxicological Hazard Traits,Reproductive Toxicity,Respiratory Toxicity,Unnamed: 0_y,Body Area,Product Category,Product Form
41,104004,AMOREPACIFIC US INC.,Innisfree,Balancing Cream with Green Tea,NaN,NaN,4/7/2022,Lilial,Fragrance,NaN,NaN,4/7/2022,NaN,NaN,Lilial,80-54-6,Lilial,Reproductive Toxicity,2-(4-tert-Butylbenzyl)propionaldehyde,BUTYLPHENYL METHYLPROPIONAL; Lilial,EC Annex VI CMRs - Cat. 1B,FF,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,21.0,Face,Facial Cream,Cream/Gel/Foam
42,104004,AMOREPACIFIC US INC.,Innisfree,Balancing Cream with Green Tea,NaN,NaN,4/7/2022,Lilial,Fragrance,NaN,NaN,4/7/2022,NaN,NaN,Lilial,80-54-6,Lilial,Reproductive Toxicity,2-(4-tert-Butylbenzyl)propionaldehyde,BUTYLPHENYL METHYLPROPIONAL; Lilial,EC Annex VI CMRs - Cat. 1B,FF,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,22.0,Face,Facial Cream,Cream/Gel/Foam
43,104004,AMOREPACIFIC US INC.,Innisfree,Balancing Cream with Green Tea,NaN,NaN,4/7/2022,Lilial,Fragrance,NaN,NaN,4/7/2022,NaN,NaN,Lilial,80-54-6,Lilial,Reproductive Toxicity,2-(4-tert-Butylbenzyl)propionaldehyde,BUTYLPHENYL METHYLPROPIONAL; Lilial,EC Annex VI CMRs - Cat. 1B,FF,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,23.0,Face,Facial Cream,Cream/Gel/Foam
44,104004,AMOREPACIFIC US INC.,Innisfree,Balancing Cream with Green Tea,NaN,NaN,4/7/2022,Lilial,Fragrance,NaN,NaN,4/7/2022,NaN,NaN,Lilial,80-54-6,Lilial,Reproductive Toxicity,2-(4-tert-Butylbenzyl)propionaldehyde,BUTYLPHENYL METHYLPROPIONAL; Lilial,EC Annex VI CMRs - Cat. 1B,FF,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,24.0,Face,Facial Cream,Cream/Gel/Foam
45,104004,AMOREPACIFIC US INC.,Innisfree,Balancing Cream with Green Tea,NaN,NaN,4/7/2022,Lilial,Fragrance,NaN,NaN,4/7/2022,NaN,NaN,Lilial,80-54-6,Lilial,Reproductive Toxicity,2-(4-tert-Butylbenzyl)propionaldehyde,BUTYLPHENYL METHYLPROPIONAL; Lilial,EC Annex VI CMRs - Cat. 1B,FF,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,25.0,Face,Facial Cream,Cream/Gel/Foam

In [144]:
rep = rep.drop(columns=['Unnamed: 0_x', 'Unnamed: 0_y'])

In [145]:
rep.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,Concentration,Ingredient Submitted Date,Ingredient Removed Date,cas_number,clean_name,api_rn,api_name,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)",Bioaccumulation,Carcinogenicity,Cardiovascular Toxicity,Dermatotoxicity,Developmental Toxicity,Endocrine Toxicity,Environmental Persistence,Environmental Tox,Fragrance Allergen,Genotoxicity,Hazard Trait Undefined,Hematotoxicity,Hepatotoxicity And Digestive System Toxicity,Immunotoxicity,Musculoskeletal Toxicity,Nephrotoxicity And Other Toxicity To The Urinary System,Neurodevelopmental Toxicity,Neurotoxicity,Ocular Toxicity,Other Toxicological Hazard Traits,Reproductive Toxicity,Respiratory Toxicity,Body Area,Product Category,Product Form
41,104004,AMOREPACIFIC US INC.,Innisfree,Balancing Cream with Green Tea,NaN,NaN,4/7/2022,Lilial,Fragrance,NaN,NaN,4/7/2022,NaN,NaN,Lilial,80-54-6,Lilial,Reproductive Toxicity,2-(4-tert-Butylbenzyl)propionaldehyde,BUTYLPHENYL METHYLPROPIONAL; Lilial,EC Annex VI CMRs - Cat. 1B,FF,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,Face,Facial Cream,Cream/Gel/Foam
42,104004,AMOREPACIFIC US INC.,Innisfree,Balancing Cream with Green Tea,NaN,NaN,4/7/2022,Lilial,Fragrance,NaN,NaN,4/7/2022,NaN,NaN,Lilial,80-54-6,Lilial,Reproductive Toxicity,2-(4-tert-Butylbenzyl)propionaldehyde,BUTYLPHENYL METHYLPROPIONAL; Lilial,EC Annex VI CMRs - Cat. 1B,FF,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,Face,Facial Cream,Cream/Gel/Foam
43,104004,AMOREPACIFIC US INC.,Innisfree,Balancing Cream with Green Tea,NaN,NaN,4/7/2022,Lilial,Fragrance,NaN,NaN,4/7/2022,NaN,NaN,Lilial,80-54-6,Lilial,Reproductive Toxicity,2-(4-tert-Butylbenzyl)propionaldehyde,BUTYLPHENYL METHYLPROPIONAL; Lilial,EC Annex VI CMRs - Cat. 1B,FF,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,Face,Facial Cream,Cream/Gel/Foam
44,104004,AMOREPACIFIC US INC.,Innisfree,Balancing Cream with Green Tea,NaN,NaN,4/7/2022,Lilial,Fragrance,NaN,NaN,4/7/2022,NaN,NaN,Lilial,80-54-6,Lilial,Reproductive Toxicity,2-(4-tert-Butylbenzyl)propionaldehyde,BUTYLPHENYL METHYLPROPIONAL; Lilial,EC Annex VI CMRs - Cat. 1B,FF,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,Face,Facial Cream,Cream/Gel/Foam
45,104004,AMOREPACIFIC US INC.,Innisfree,Balancing Cream with Green Tea,NaN,NaN,4/7/2022,Lilial,Fragrance,NaN,NaN,4/7/2022,NaN,NaN,Lilial,80-54-6,Lilial,Reproductive Toxicity,2-(4-tert-Butylbenzyl)propionaldehyde,BUTYLPHENYL METHYLPROPIONAL; Lilial,EC Annex VI CMRs - Cat. 1B,FF,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,Face,Facial Cream,Cream/Gel/Foam

In [146]:
rep = rep.drop_duplicates()

In [147]:
rep_cats = rep.groupby("Product Category").size().rename("count").reset_index()
rep_cats.sort_values("count", ascending = False)

                               Product Category  count
23                        Foundations and Bases  15762
58                      Other Skin Care Product    727
71  Skin Moisturizers (making a cosmetic claim)    510
62                      Perfumes/Eaux de Parfum    436
11                        Body Washes and Soaps    317
..                                          ...    ...
22                      Foot Powders and Sprays      2
21                          Feminine Deodorants      1
41                             Makeup Fixatives      1
4         Artificial Nails and Related Products      1
32                           Hair Straighteners      1

[77 rows x 2 columns]

In [148]:
rep_found = rep[rep["Product Category"] == "Foundations and Bases"]
rep_found.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,Concentration,Ingredient Submitted Date,Ingredient Removed Date,cas_number,clean_name,api_rn,api_name,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)",Bioaccumulation,Carcinogenicity,Cardiovascular Toxicity,Dermatotoxicity,Developmental Toxicity,Endocrine Toxicity,Environmental Persistence,Environmental Tox,Fragrance Allergen,Genotoxicity,Hazard Trait Undefined,Hematotoxicity,Hepatotoxicity And Digestive System Toxicity,Immunotoxicity,Musculoskeletal Toxicity,Nephrotoxicity And Other Toxicity To The Urinary System,Neurodevelopmental Toxicity,Neurotoxicity,Ocular Toxicity,Other Toxicological Hazard Traits,Reproductive Toxicity,Respiratory Toxicity,Body Area,Product Category,Product Form
591409,126495,"Access Business Group International, LLC",Amway Global,Artistry Youth XTend Lifting Smoothing Foundat...,NaN,NaN,6/7/2023,Methylparaben (Methyl p-Hydroxybenzoate) 99-76-3,Preservative/Stabilizer,NaN,NaN,6/7/2023,NaN,99-76-3,Methylparaben (Methyl p-Hydroxybenzoate),99-76-3,Methylparaben,Endocrine Toxicity; Reproductive Toxicity,Methylparaben,Methyl p-Hydroxybenzoate,CECBP - Priority Chemicals,FF,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,Face,Foundations and Bases,Liquid
591413,126495,"Access Business Group International, LLC",Amway Global,Artistry Youth XTend Lifting Smoothing Foundat...,NaN,NaN,6/7/2023,Ethyl paraben (Ethyl 4-hydroxybenzoate) 120-47-8,Preservative/Stabilizer,NaN,NaN,6/7/2023,NaN,120-47-8,Ethyl paraben (Ethyl 4-hydroxybenzoate),120-47-8,Ethylparaben,Endocrine Toxicity; Reproductive Toxicity,Ethyl paraben,Ethyl 4-hydroxybenzoate,CECBP - Priority Chemicals,FF,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,Face,Foundations and Bases,Liquid
591421,126495,"Access Business Group International, LLC",Amway Global,Artistry Youth XTend Lifting Smoothing Foundat...,NaN,NaN,6/7/2023,n-Propylparaben (Propylparaben) 94-13-3,Preservative/Stabilizer,NaN,NaN,6/7/2023,NaN,94-13-3,n-Propylparaben (Propylparaben),94-13-3,Propylparaben,Endocrine Toxicity; Reproductive Toxicity,n-Propylparaben,Propylparaben,CECBP - Priority Chemicals,FF,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,Face,Foundations and Bases,Liquid
591425,126496,"Access Business Group International, LLC",Amway Global,Artistry Youth XTend Lifting Smoothing Foundat...,NaN,NaN,6/7/2023,Ethyl paraben (Ethyl 4-hydroxybenzoate) 120-47-8,Preservative/Stabilizer,NaN,NaN,6/7/2023,NaN,120-47-8,Ethyl paraben (Ethyl 4-hydroxybenzoate),120-47-8,Ethylparaben,Endocrine Toxicity; Reproductive Toxicity,Ethyl paraben,Ethyl 4-hydroxybenzoate,CECBP - Priority Chemicals,FF,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,Face,Foundations and Bases,Liquid
591433,126496,"Access Business Group International, LLC",Amway Global,Artistry Youth XTend Lifting Smoothing Foundat...,NaN,NaN,6/7/2023,Methylparaben (Methyl p-Hydroxybenzoate) 99-76-3,Preservative/Stabilizer,NaN,NaN,6/7/2023,NaN,99-76-3,Methylparaben (Methyl p-Hydroxybenzoate),99-76-3,Methylparaben,Endocrine Toxicity; Reproductive Toxicity,Methylparaben,Methyl p-Hydroxybenzoate,CECBP - Priority Chemicals,FF,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,Face,Foundations and Bases,Liquid

In [149]:
_found = rep_found.drop_duplicates(subset=["Product Id"])

In [150]:
len(rep_found)

15762

In [151]:
rep_found_brand = rep_found.groupby("Brand").size().rename("count").reset_index()
rep_found_brand.sort_values("count", ascending = False)

                      Brand  count
15                  Kryolan  15101
5         Charlotte Tilbury    173
3        CLE DE PEAU BEAUTE    145
19                     NARS    131
1   Anastasia Beverly Hills     76
21           SISLEY - PARIS     30
20                 SHISEIDO     17
14             Kevyn Aucoin     17
0              Amway Global     12
10                     Hera     12
4                   Catrice     10
16                   Lumene      8
13                     IOPE      6
22               sulwhasoo       6
8                  GUERLAIN      5
17                   MAVALA      4
11               IL MAKIAGE      3
12                   INGLOT      1
9                    HERMES      1
18                   Miniso      1
7                     GUCCI      1
6            Dose of Colors      1
2                   CLARINS      1

In [152]:
viz_table.head()

,Product Id,Company,Brand,Product Name,Variant,Ingredient Name,Function,Unit of Measure,Concentration,cas_number,clean_name,api_rn,api_name,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)",Unnamed: 0_x,final_name,Product Discontinued Year,Product Submitted Year,Ingredient Submitted Year,Ingredient Removed Year,Unnamed: 0_y,Body Area,Product Category,Product Form
0,18358,Nail Alliance - Entity,Entity Nudite,Cool Pink Nail Sculpting Powder,NaN,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,5.000000,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania,<NA>,2019,2019,<NA>,0.0,Nails,Artificial Nails and Related Products,Powder
1,38661,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Solid,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,40.000000,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania,<NA>,2015,2015,<NA>,1.0,Eye Area,Eye Shadow,Powder
2,38662,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Sprinkle,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,31.000000,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania,<NA>,2015,2015,<NA>,2.0,Eye Area,Eye Shadow,Powder
3,38667,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,12.000000,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania,<NA>,2015,2015,<NA>,3.0,Eye Area,Eye Shadow,Powder
4,38665,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,21.500000,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN,Titania,<NA>,2015,2015,<NA>,4.0,Eye Area,Eye Shadow,Powder

In [154]:
database_table = viz_table[["Company", "Brand","Product Name", "Variant", "Product Category", "api_name", "Hazard Traits", "Concentration", "Unit of Measure"]]
database_table = database_table.rename(columns = {"api_name": "Ingredient Name"})
database_table.to_csv("database tables/database_table.csv")

In [155]:
database_table.head()

,Company,Brand,Product Name,Variant,Product Category,Ingredient Name,Hazard Traits,Concentration,Unit of Measure
0,Nail Alliance - Entity,Entity Nudite,Cool Pink Nail Sculpting Powder,NaN,Artificial Nails and Related Products,Titania,Carcinogenicity,5.000000,mg/g
1,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Solid,Eye Shadow,Titania,Carcinogenicity,40.000000,mg/g
2,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Sprinkle,Eye Shadow,Titania,Carcinogenicity,31.000000,mg/g
3,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,Eye Shadow,Titania,Carcinogenicity,12.000000,mg/g
4,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,Eye Shadow,Titania,Carcinogenicity,21.500000,mg/g

In [156]:
prod_info["Unit of Measure"].unique()

array(['mg/g', nan, 'Percent', 'mg/mL', 'µg/mL', 'µg/g', 'percent'],
      dtype=object)