In [59]:
import pandas as pd

In [60]:
chemicals = pd.read_csv("data/chemical_names_cleaned_2_18.csv")

In [61]:
chemicals.head()

,original_ingredient,cas_number,clean_name,api_rn,api_name
0,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,8023-85-6,Cedrus Atlantica Oil,8023-85-6,Cedrus Atlantica Oil
1,"[3R-(3a,3aß,7ß,8aa)]-1-(2,3,4,7,8,8a-hexahydro...",32388-55-9,Acetylcedrene,32388-55-9,Acetylcedrene
2,"1-Naphthalenepropanol, a-ethenyldecahydro- 2-h...",515-03-7,Sclareol,515-03-7,Sclareol
3,Myroxylon Pereirae Oil/Extract (Myroxylon bals...,8007-00-9,Myroxylon Pereirae Oil/Extract,8007-00-9,Myroxylon Pereirae Oil/Extract
4,Turpentine gum (Pinus spp.); Turpentine oil an...,9005-90-7,Turpentine,9005-90-7,Turpentine

In [62]:
chemicals = chemicals.rename(columns = {"original_ingredient": 'Ingredient Name'})

In [63]:
chemicals.head()

,Ingredient Name,cas_number,clean_name,api_rn,api_name
0,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,8023-85-6,Cedrus Atlantica Oil,8023-85-6,Cedrus Atlantica Oil
1,"[3R-(3a,3aß,7ß,8aa)]-1-(2,3,4,7,8,8a-hexahydro...",32388-55-9,Acetylcedrene,32388-55-9,Acetylcedrene
2,"1-Naphthalenepropanol, a-ethenyldecahydro- 2-h...",515-03-7,Sclareol,515-03-7,Sclareol
3,Myroxylon Pereirae Oil/Extract (Myroxylon bals...,8007-00-9,Myroxylon Pereirae Oil/Extract,8007-00-9,Myroxylon Pereirae Oil/Extract
4,Turpentine gum (Pinus spp.); Turpentine oil an...,9005-90-7,Turpentine,9005-90-7,Turpentine

In [64]:
len(chemicals)

505

In [65]:
all_data = pd.read_csv("data/CDPH Search results - 1_12_2026, 3_34_15 PM.csv")

In [66]:
all_data.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,Concentration,Ingredient Submitted Date,Ingredient Removed Date
0,18358,Nail Alliance - Entity,Entity Nudite,Cool Pink Nail Sculpting Powder,NaN,NaN,6/24/2019,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,5.000000,6/24/2019,NaN
1,38661,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,40.000000,9/21/2015,NaN
2,38662,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Sprinkle,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,31.000000,9/21/2015,NaN
3,38667,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,12.000000,9/21/2015,NaN
4,38665,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,21.500000,9/21/2015,NaN

In [67]:
len(all_data)

534508

In [68]:
first_merge = all_data.merge(chemicals, on = "Ingredient Name", how = 'left')

In [69]:
first_merge.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,Concentration,Ingredient Submitted Date,Ingredient Removed Date,cas_number,clean_name,api_rn,api_name
0,18358,Nail Alliance - Entity,Entity Nudite,Cool Pink Nail Sculpting Powder,NaN,NaN,6/24/2019,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,5.000000,6/24/2019,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania
1,38661,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,40.000000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania
2,38662,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Sprinkle,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,31.000000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania
3,38667,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,12.000000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania
4,38665,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,21.500000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania

In [70]:
first_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 534508 entries, 0 to 534507
Data columns (total 17 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Product Id                 534508 non-null  int64
 1   Company                    534508 non-null  object
 2   Brand                      534308 non-null  object
 3   Product Name               534508 non-null  object
 4   Variant                    187813 non-null  object
 5   Product Discontinued Date  39102 non-null   object
 6   Product Submitted Date     534508 non-null  object
 7   Ingredient Name            534186 non-null  object
 8   Function                   433384 non-null  object
 9   Unit of Measure            222747 non-null  object
 10  Concentration              224495 non-null  object
 11  Ingredient Submitted Date  534186 non-null  object
 12  Ingredient Removed Date    6627 non-null    object
 13  cas_number                 447569 non-null  object
 14  clean_name                 534186 non-null  object
 15  api_rn                     532360 non-null  object
 16  api_name                   534186 non-null  object
dtypes: int64(1), object(16)
memory usage: 69.3+ MB

In [71]:
na = first_merge[first_merge["api_name"].isna()]
na.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,Concentration,Ingredient Submitted Date,Ingredient Removed Date,cas_number,clean_name,api_rn,api_name
1402,72818,Exclusive Fragrances & Cosmetics,10 Corso Como,10 Corso Como Massage Oil,10 Corso Como,NaN,6/29/2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404,72816,IPD Inc,10 Corso Como,Corso Como Bath Pearls,Corso Como,NaN,6/25/2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10283,109738,Aloisia Beauty Products Inc.,Aloisia Beauty,Light Hydration Emulsion,NaN,NaN,6/6/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10284,109736,Aloisia Beauty Products Inc.,Aloisia Beauty,Renew Concentrated Serum,NaN,NaN,6/6/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10286,109739,Aloisia Beauty Products Inc.,Aloisia Beauty,Revitalize Eye Cream,NaN,NaN,6/6/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [72]:
na["Ingredient Name"].unique()

array([nan], dtype=object)

In [73]:
na_ingredients = na["Ingredient Name"].unique().tolist()
na_ingredients

[nan]

In [74]:
na_names = pd.DataFrame(na_ingredients)

In [75]:
na_names.to_csv("na_names.csv")

In [76]:
na_names_cleaned = pd.read_csv("data/na_names_cleaned.csv", encoding='latin-1')

na_names_cleaned = na_names_cleaned.apply(
    lambda col: col.str.replace('\xa0', ' ', regex=False) if col.dtype == 'object' else col
)

In [77]:
na_names_cleaned["name"].unique().tolist()

['Cedrus Atlantica Oil/Extract (Cedrus atlantica\\xa0oil and extract; Cedrus Atlantica Bark Extract; Cedrus Atlantica Bark Oil; Cedrus Atlantica Bark Water; Cedrus Atlantica Leaf Extract; Cedrus Atlantica Wood Extract; Cedrus Atlantica Wood Oil) 92201-55-3 / 8023-85-6,',
 '[3R-(3a,3a§,7§,8aa)]-1-(2,3,4,7,8,8a-hexahydro-3,6,8,8-tetramethyl-1H-3a,7-methanoazulen-5-yl)ethan-1-one (Acetyl Cedrene) 32388-55-9,',
 '1-Naphthalenepropanol, a-ethenyldecahydro- 2-hydroxy-a,2,5,5,8a-pentamethyl-, [1R-[1a(R),2§,4a§,8aa]]- (Sclareol; [1R-(1alpha)]-alpha-Ethenyldecahydro-2-hydroxy-a,2,5,5,8a-pentamethyl-1-naphthalenepropanol) 515-03-7,',
 'Myroxylon Pereirae Oil/Extract (Myroxylon balsamum\\xa0var.\\xa0pereirae; extracts and distillates; Balsam Peru oil, absolute and anhydrol (Balsam Oil Peru); Myroxylon Balsamum Pereirae Balsam Extract; Myroxylon Balsamum Pereirae Balsam Oil; Myroxylon Pereirae Oil; Myroxylon Pereirae Resin Extract; Myroxylon Pereirae Resin; Myroxylon Pereirae (Balsam Peru) Oil; Myroxylon Pereirae (Balsam Peru) Resin; Myroxylon Pereirae (Balsam Peru) Resin Extract) 8007-00-9,',
 'Turpentine gum (Pinus\\xa0spp.); Turpentine oil and rectified oil; Turpentine, steam distilled (Pinus\\xa0spp.) (Turpentine) 9005-90-7 / 8006-64-2 / 8052-14-0,',
 'Butane (containing greater than or equal to  0,1\\xa0% butadiene (203-450-8)) 106-97-8,',
 ' Pinus Mugo (Pinus mugo\\xa0leaf and twig oil and extract; Pinus Mugo Leaf Oil; Pinus Mugo Twig Leaf Extract; Pinus Mugo Twig Oil; Pinus Mugo Leaf/Twig Extract) 90082-72-7,',
 '(±)-1,7,7-trimethyl-3-[(4-methylphenyl)methylene]bicyclo[2.2.1]heptan-2-one (covering any of the individual isomers and/or combinations thereof (4-MBC); 4-Methylbenzylidene Camphor (4-MBC)) 36861-47-9,',
 'Pinus Pumila (Pinus pumila\\xa0leaf and twig oil and extract; Pinus Pumila Needle Extract; Pinus Pumila Twig Leaf Extract; Pinus Pumila Twig Leaf Oil; Pinus Mugo Leaf/Twig Extract; Pinus Mugo Twig Oil; Pinus Pumilio Branch/Leaf Oil; Pinus Pumilio Leaf Extract) 97676-05-6],']

In [78]:
na_names_cleaned = na_names_cleaned.rename(columns={'name': 'Ingredient Name'})
na_names_cleaned = na_names_cleaned.rename(columns={'api_cas': 'api_rn'})
na_names_cleaned.head()

,Ingredient Name,api_rn,api_name
0,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,8023-85-6,Cedrus Atlantica Oil
1,"[3R-(3a,3a§,7§,8aa)]-1-(2,3,4,7,8,8a-hexahydro...",32388-55-9,Acetylcedrene
2,"1-Naphthalenepropanol, a-ethenyldecahydro- 2-h...",515-03-7,Sclareol
3,Myroxylon Pereirae Oil/Extract (Myroxylon bals...,8007-00-9,Myroxylon Pereirae Oil/Extract
4,Turpentine gum (Pinus\xa0spp.); Turpentine oil...,9005-90-7,Turpentine

In [79]:
first_merge.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,Concentration,Ingredient Submitted Date,Ingredient Removed Date,cas_number,clean_name,api_rn,api_name
0,18358,Nail Alliance - Entity,Entity Nudite,Cool Pink Nail Sculpting Powder,NaN,NaN,6/24/2019,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,5.000000,6/24/2019,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania
1,38661,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,40.000000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania
2,38662,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Sprinkle,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,31.000000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania
3,38667,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,12.000000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania
4,38665,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,21.500000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania

In [80]:
first_merge.update(na_names_cleaned)

In [81]:
na_names_cleaned

,Ingredient Name,api_rn,api_name
0,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,8023-85-6,Cedrus Atlantica Oil
1,"[3R-(3a,3a§,7§,8aa)]-1-(2,3,4,7,8,8a-hexahydro...",32388-55-9,Acetylcedrene
2,"1-Naphthalenepropanol, a-ethenyldecahydro- 2-h...",515-03-7,Sclareol
3,Myroxylon Pereirae Oil/Extract (Myroxylon bals...,8007-00-9,Myroxylon Pereirae Oil/Extract
4,Turpentine gum (Pinus\xa0spp.); Turpentine oil...,9005-90-7,Turpentine
5,Butane (containing greater than or equal to 0...,106-97-8,Butane
6,Pinus Mugo (Pinus mugo\xa0leaf and twig oil a...,90082-72-7,"Pine,ÊPinus mugo, ext."
7,"(±)-1,7,7-trimethyl-3-[(4-methylphenyl)methyle...",36861-47-9,3-(4_-Methylbenzylidene)camphor
8,Pinus Pumila (Pinus pumila\xa0leaf and twig oi...,97676-05-6,"Pine,ÊPinus pumila, ext."

In [82]:
first_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 534508 entries, 0 to 534507
Data columns (total 17 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Product Id                 534508 non-null  int64
 1   Company                    534508 non-null  object
 2   Brand                      534308 non-null  object
 3   Product Name               534508 non-null  object
 4   Variant                    187813 non-null  object
 5   Product Discontinued Date  39102 non-null   object
 6   Product Submitted Date     534508 non-null  object
 7   Ingredient Name            534186 non-null  object
 8   Function                   433384 non-null  object
 9   Unit of Measure            222747 non-null  object
 10  Concentration              224495 non-null  object
 11  Ingredient Submitted Date  534186 non-null  object
 12  Ingredient Removed Date    6627 non-null    object
 13  cas_number                 447569 non-null  object
 14  clean_name                 534186 non-null  object
 15  api_rn                     532360 non-null  object
 16  api_name                   534186 non-null  object
dtypes: int64(1), object(16)
memory usage: 69.3+ MB

In [ ]:
harms = pd.read_csv("reportable_ingredients.csv")

In [84]:
harms.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3324 entries, 0 to 3323
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Chemical Name                 3324 non-null   object
 1   CAS RN                        3049 non-null   object
 2   Synonyms                      571 non-null    object
 3   Hazard Traits                 3324 non-null   object
 4   Authoritative List            3324 non-null   object
 5   When to Report (Any, FF, FA)  3324 non-null   object
 6   Unnamed: 6                    1 non-null      object
dtypes: object(7)
memory usage: 181.9+ KB

In [85]:
harms.rename(columns={'CAS RN': 'api_rn'}, inplace=True)

In [86]:
chemicals.head()

,Ingredient Name,cas_number,clean_name,api_rn,api_name
0,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,8023-85-6,Cedrus Atlantica Oil,8023-85-6,Cedrus Atlantica Oil
1,"[3R-(3a,3aß,7ß,8aa)]-1-(2,3,4,7,8,8a-hexahydro...",32388-55-9,Acetylcedrene,32388-55-9,Acetylcedrene
2,"1-Naphthalenepropanol, a-ethenyldecahydro- 2-h...",515-03-7,Sclareol,515-03-7,Sclareol
3,Myroxylon Pereirae Oil/Extract (Myroxylon bals...,8007-00-9,Myroxylon Pereirae Oil/Extract,8007-00-9,Myroxylon Pereirae Oil/Extract
4,Turpentine gum (Pinus spp.); Turpentine oil an...,9005-90-7,Turpentine,9005-90-7,Turpentine

In [87]:
chemicals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Ingredient Name  504 non-null    object
 1   cas_number       380 non-null    object
 2   clean_name       504 non-null    object
 3   api_rn           489 non-null    object
 4   api_name         504 non-null    object
dtypes: object(5)
memory usage: 19.9+ KB

In [99]:
len(chemicals)

505

In [100]:
harms.head()

,Chemical Name,api_rn,Synonyms,Hazard Traits,Authoritative List,"When to Report (Any, FF, FA)",Unnamed: 6
0,(±) Tetrahydrofurfuryl (R)-2-[4-(6-chloroquino...,119738-06-6,NaN,Reproductive Toxicity,EC Annex VI CMRs - Cat. 1B,FF,NaN
1,"(±)-1,7,7-trimethyl-3-[(4-methylphenyl)methyle...",36861-47-9,"4-Methylbenzylidene Camphor (4-MBC); (±)-1,7,7...",Endocrine Toxicity,EC EDs,FF,NaN
2,"(1a,2a,3ß,6ß)-1,2,3,6-tetrahydro-3,6-methanoph...",2746-19-2,NaN,Respiratory Toxicity,EC Annex VI Resp. Sens. - Cat. 1,FF,NaN
3,"(1R,3E,4S)-1,7,7-trimethyl-3-(4-methylbenzylid...",95342-41-9,NaN,Endocrine Toxicity,EC EDs,FF,NaN
4,"(1R,3Z,4S)-1,7,7-trimethyl-3-(4-methylbenzylid...",852541-21-0,NaN,Endocrine Toxicity,EC EDs,FF,NaN

In [106]:
len(harms)

3324

In [113]:
harms.head()

,Chemical Name,api_rn,Synonyms,Hazard Traits,Authoritative List,"When to Report (Any, FF, FA)",Unnamed: 6
0,(±) Tetrahydrofurfuryl (R)-2-[4-(6-chloroquino...,119738-06-6,NaN,Reproductive Toxicity,EC Annex VI CMRs - Cat. 1B,FF,NaN
1,"(±)-1,7,7-trimethyl-3-[(4-methylphenyl)methyle...",36861-47-9,"4-Methylbenzylidene Camphor (4-MBC); (±)-1,7,7...",Endocrine Toxicity,EC EDs,FF,NaN
2,"(1a,2a,3ß,6ß)-1,2,3,6-tetrahydro-3,6-methanoph...",2746-19-2,NaN,Respiratory Toxicity,EC Annex VI Resp. Sens. - Cat. 1,FF,NaN
3,"(1R,3E,4S)-1,7,7-trimethyl-3-(4-methylbenzylid...",95342-41-9,NaN,Endocrine Toxicity,EC EDs,FF,NaN
4,"(1R,3Z,4S)-1,7,7-trimethyl-3-(4-methylbenzylid...",852541-21-0,NaN,Endocrine Toxicity,EC EDs,FF,NaN

In [112]:
harms_agg = harms.groupby('api_rn').agg({
    'Hazard Traits': ', '.join,
    'Chemical Name': 'first',
    'Synonyms': 'first',
    'Authoritative List': ', '.join,
    'When to Report (Any, FF, FA)': 'first'
}).reset_index()
len(harms_agg)
harms_agg.head()

,api_rn,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)"
0,85-00-7,Hazard Trait Undefined,Diquat dibromide,None,CECBP - Priority Chemicals,FF
1,100-00-5,Carcinogenicity,1-Chloro-4-nitrobenzene,4-Chloronitrobenzene,IARC Carcinogens - 2B; Prop 65,Any
2,100-02-7,Dermatotoxicity; Environmental tox; Other Toxi...,4-Nitrophenol,None,CA TACs; CECBP - Priority Chemicals; CWA 303(c...,FF
3,100-17-4,Carcinogenicity,para-Nitroanisole,None,IARC Carcinogens - 2B; Prop 65,Any
4,100-25-4,Reproductive Toxicity,p-Dinitrobenzene,None,Prop 65,Any

In [115]:
chemicals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Ingredient Name  504 non-null    object
 1   cas_number       380 non-null    object
 2   clean_name       504 non-null    object
 3   api_rn           489 non-null    object
 4   api_name         504 non-null    object
dtypes: object(5)
memory usage: 19.9+ KB

In [114]:
result = chemicals.merge(harms_agg, on='api_rn', how='left')
result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 10 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Ingredient Name               504 non-null    object
 1   cas_number                    380 non-null    object
 2   clean_name                    504 non-null    object
 3   api_rn                        489 non-null    object
 4   api_name                      504 non-null    object
 5   Hazard Traits                 359 non-null    object
 6   Chemical Name                 359 non-null    object
 7   Synonyms                      213 non-null    object
 8   Authoritative List            359 non-null    object
 9   When to Report (Any, FF, FA)  359 non-null    object
dtypes: object(10)
memory usage: 39.6+ KB

In [139]:
len(result)

505

In [126]:
na = result[result["Hazard Traits"].isna()]
na.head()

,Ingredient Name,cas_number,clean_name,api_rn,api_name,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)"
0,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,8023-85-6,Cedrus Atlantica Oil,8023-85-6,Cedrus Atlantica Oil,NaN,NaN,NaN,NaN,NaN
4,Turpentine gum (Pinus spp.); Turpentine oil an...,9005-90-7,Turpentine,9005-90-7,Turpentine,NaN,NaN,NaN,NaN,NaN
10,CITRONELLOL,NaN,CITRONELLOL,106-22-9,Citronellol,NaN,NaN,NaN,NaN,NaN
13,Limonene (1-methyl-4-prop-1-en-2-yl-cyclohexen...,5989-27-5,Limonene (1-methyl-4-prop-1-en-2-yl-cyclohexen...,5989-27-5,(+)-Limonene,NaN,NaN,NaN,NaN,NaN
15,"Aloe vera, non-decolorized (unfiltered) whole ...",NaN,"Aloe vera, non-decolorized (unfiltered) whole ...",8001-97-6,Aloe vera,NaN,NaN,NaN,NaN,NaN

In [140]:
len(na)

146

In [141]:
len(result) - len(na)

359

In [143]:
result = result.dropna(subset =['Hazard Traits'])
len(result)

359

In [127]:
harms_agg.head()

,api_rn,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)"
0,85-00-7,Hazard Trait Undefined,Diquat dibromide,None,CECBP - Priority Chemicals,FF
1,100-00-5,Carcinogenicity,1-Chloro-4-nitrobenzene,4-Chloronitrobenzene,IARC Carcinogens - 2B; Prop 65,Any
2,100-02-7,Dermatotoxicity; Environmental tox; Other Toxi...,4-Nitrophenol,None,CA TACs; CECBP - Priority Chemicals; CWA 303(c...,FF
3,100-17-4,Carcinogenicity,para-Nitroanisole,None,IARC Carcinogens - 2B; Prop 65,Any
4,100-25-4,Reproductive Toxicity,p-Dinitrobenzene,None,Prop 65,Any

In [130]:
harms_agg.rename(columns={'Chemical Name': 'Ingredient Name'}, inplace=True)

In [135]:
na.head()

,Ingredient Name,cas_number,clean_name,api_rn,api_name,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)"
0,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,8023-85-6,Cedrus Atlantica Oil,8023-85-6,Cedrus Atlantica Oil,NaN,NaN,NaN,NaN,NaN
4,Turpentine gum (Pinus spp.); Turpentine oil an...,9005-90-7,Turpentine,9005-90-7,Turpentine,NaN,NaN,NaN,NaN,NaN
10,CITRONELLOL,NaN,CITRONELLOL,106-22-9,Citronellol,NaN,NaN,NaN,NaN,NaN
13,Limonene (1-methyl-4-prop-1-en-2-yl-cyclohexen...,5989-27-5,Limonene (1-methyl-4-prop-1-en-2-yl-cyclohexen...,5989-27-5,(+)-Limonene,NaN,NaN,NaN,NaN,NaN
15,"Aloe vera, non-decolorized (unfiltered) whole ...",NaN,"Aloe vera, non-decolorized (unfiltered) whole ...",8001-97-6,Aloe vera,NaN,NaN,NaN,NaN,NaN

In [137]:
na.to_csv("na_harms.csv")

In [124]:
na.groupby("Ingredient Name").size().rename("count").reset_index().head()

                                     Ingredient Name  count
0  1,1'-Sulfonylbis[3,5-dibromo-4-(2,3-dibromopro...      1
1  1,3-Dioxane, 2-(2,4-dimethyl-3-cyclohexen-1-yl...      1
2  1-(1,2,3,4,5,6,7,8-octahydro-2,3,8,8-tetrameth...      1
3  1-Methoxy-4-(1E)-1-propen-1-yl-benzene (trans-...      1
4  2,4-Hexadienal (89% trans, trans isomer; 11% c...      1

In [133]:
len(na)

146

In [148]:
na_cleaned = pd.read_csv("data/na_harms_cleaned.csv", encoding='latin-1')

In [149]:
final_merge = pd.concat([result, na_cleaned])

In [150]:
len(final_merge)

505

In [98]:
chemicals.head()

,Ingredient Name,cas_number,clean_name,api_rn,api_name
0,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,8023-85-6,Cedrus Atlantica Oil,8023-85-6,Cedrus Atlantica Oil
1,"[3R-(3a,3aß,7ß,8aa)]-1-(2,3,4,7,8,8a-hexahydro...",32388-55-9,Acetylcedrene,32388-55-9,Acetylcedrene
2,"1-Naphthalenepropanol, a-ethenyldecahydro- 2-h...",515-03-7,Sclareol,515-03-7,Sclareol
3,Myroxylon Pereirae Oil/Extract (Myroxylon bals...,8007-00-9,Myroxylon Pereirae Oil/Extract,8007-00-9,Myroxylon Pereirae Oil/Extract
4,Turpentine gum (Pinus spp.); Turpentine oil an...,9005-90-7,Turpentine,9005-90-7,Turpentine

In [89]:
ings = pd.read_csv("ingredients_with_api_data-cleaned.csv")

In [90]:
ings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 496 entries, 0 to 495
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   original_ingredient  495 non-null    object
 1   cas_number           371 non-null    object
 2   clean_name           495 non-null    object
 3   api_rn               460 non-null    object
 4   api_name             464 non-null    object
dtypes: object(5)
memory usage: 19.5+ KB

In [91]:
ings.head()

,original_ingredient,cas_number,clean_name,api_rn,api_name
0,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania
1,CITRONELLOL,NaN,CITRONELLOL,106-22-9,Citronellol
2,LINALOOL,NaN,LINALOOL,78-70-6,(±)-Linalool
3,HEXYL CINNAMAL,NaN,HEXYL CINNAMAL,101-86-0,α-Hexylcinnamaldehyde
4,Limonene (1-methyl-4-prop-1-en-2-yl-cyclohexen...,5989-27-5,Limonene (1-methyl-4-prop-1-en-2-yl-cyclohexen...,5989-27-5,(+)-Limonene

In [92]:
#all_traits = set()
#for traits in harms['Hazard Traits'].str.split('; '):
    #all_traits.update(traits)

In [93]:
#for trait in all_traits:
    #harms[trait] = harms['Hazard Traits'].str.contains(trait, regex=False).astype(int)

In [94]:
#harms.head()

In [95]:
ings = ings.rename(columns={'api_rn': 'CAS RN'})

In [96]:
len(ings)

496

In [ ]:
merge.head()

,original_ingredient,cas_number,clean_name,CAS RN,api_name,Chemical Name,Synonyms,Hazard Traits,Authoritative List,"When to Report (Any, FF, FA)",Unnamed: 6
0,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,"Titanium dioxide (airborne, unbound particles ...",CI 77891,Carcinogenicity,IARC Carcinogens - 2B; Prop 65,Any,NaN
1,CITRONELLOL,NaN,CITRONELLOL,106-22-9,Citronellol,NaN,NaN,NaN,NaN,NaN,NaN
2,LINALOOL,NaN,LINALOOL,78-70-6,(±)-Linalool,"1,6-Octadien-3-ol, 3,7-dimethyl-",LINALOOL,Fragrance Allergen,Annex III of the EU Cosmetics Regulation No. 1...,FA,NaN
3,HEXYL CINNAMAL,NaN,HEXYL CINNAMAL,101-86-0,α-Hexylcinnamaldehyde,2-Benzylideneoctanal,HEXYL CINNAMAL,Fragrance Allergen,Annex III of the EU Cosmetics Regulation No. 1...,FA,NaN
4,Limonene (1-methyl-4-prop-1-en-2-yl-cyclohexen...,5989-27-5,Limonene (1-methyl-4-prop-1-en-2-yl-cyclohexen...,5989-27-5,(+)-Limonene,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
merge['Hazard Traits'].isnull().sum()

np.int64(122)

In [ ]:
len(merge)

10360

In [ ]:
1918/10360

0.18513513513513513

In [ ]:
merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10360 entries, 0 to 10359
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   original_ingredient           10085 non-null  object
 1   cas_number                    645 non-null    object
 2   clean_name                    10085 non-null  object
 3   CAS RN                        460 non-null    object
 4   api_name                      1560 non-null   object
 5   Chemical Name                 10238 non-null  object
 6   Synonyms                      1345 non-null   object
 7   Hazard Traits                 10238 non-null  object
 8   Authoritative List            10238 non-null  object
 9   When to Report (Any, FF, FA)  10238 non-null  object
 10  Unnamed: 6                    36 non-null     object
dtypes: object(11)
memory usage: 890.4+ KB

In [ ]:
NAN = merge[merge["Hazard Traits"] == 'Hazard Trait Undefined']
NAN.head()

,original_ingredient,cas_number,clean_name,CAS RN,api_name,Chemical Name,Synonyms,Hazard Traits,Authoritative List,"When to Report (Any, FF, FA)",Unnamed: 6
86,NaN,NaN,NaN,NaN,NaN,10:2 Fluorotelomer acetate,NaN,Hazard Trait Undefined,CECBP - Priority Chemicals,FF,NaN
90,NaN,NaN,NaN,NaN,NaN,"2-Bromoallyl-2,4,6-tribromophenyl ether",NaN,Hazard Trait Undefined,CECBP - Priority Chemicals,FF,NaN
92,NaN,NaN,NaN,NaN,NaN,2-Ethylhexyl diphenyl phosphate,NaN,Hazard Trait Undefined,CECBP - Priority Chemicals,FF,NaN
93,NaN,NaN,NaN,NaN,NaN,2-Hydroxypropyl 2-(2-hyrdoxyethyl)ethyl tetrab...,NaN,Hazard Trait Undefined,CECBP - Priority Chemicals,FF,NaN
96,NaN,NaN,NaN,NaN,NaN,"4,4′-Sulfonylbis[2-(2-propen-1-yl)phenol] (TGSA)",NaN,Hazard Trait Undefined,CECBP - Priority Chemicals,FF,NaN

In [ ]:
NAN.groupby("cas_number").size().rename("count").reset_index()

    cas_number  count
0     106-50-3      1
1     112-02-7      1
2      12/2/24     53
3     121-54-0      1
4     123-03-5      1
5   17301-53-0      1
6   27854-31-5      1
7      57-09-0      1
8   61789-80-8      1
9    7173-51-5      1
10   8001-54-5      1

In [ ]:
NAN.groupby("Chemical Name").size().rename("count").reset_index()

                                        Chemical Name  count
0                          10:2 Fluorotelomer acetate     36
1             2-Bromoallyl-2,4,6-tribromophenyl ether     36
2                     2-Ethylhexyl diphenyl phosphate     36
3   2-Hydroxypropyl 2-(2-hyrdoxyethyl)ethyl tetrab...     36
4    4,4'-Sulfonylbis[2-(2-propen-1-yl)phenol] (TGSA)     36
..                                                ...    ...
58                         Radioactivity, Gross Alpha     36
59                          Radioactivity, Gross Beta     36
60              Tetrabromophthalic acid, mixed esters     36
61                                    p,p'-bisphenols     36
62                                 p-Phenylenediamine      1

[63 rows x 2 columns]

In [ ]:
hazards = merge.groupby("Hazard Traits").size().rename("count").reset_index()

In [ ]:
hazards

                                         Hazard Traits  count
0    Bioaccumulation; Carcinogenicity; Cardiovascul...     36
1    Bioaccumulation; Carcinogenicity; Cardiovascul...     36
2    Bioaccumulation; Carcinogenicity; Cardiovascul...     36
3    Bioaccumulation; Carcinogenicity; Dermatotoxic...     36
4    Bioaccumulation; Carcinogenicity; Dermatotoxic...     36
..                                                 ...    ...
127                                    Ocular Toxicity     36
128              Ocular Toxicity; Respiratory Toxicity      1
129                              Reproductive Toxicity    626
130        Reproductive Toxicity; Respiratory Toxicity      1
131                               Respiratory Toxicity    414

[132 rows x 2 columns]

In [ ]:
pd.set_option('display.max_rows', None)
hazards

                                         Hazard Traits  count
0    Bioaccumulation; Carcinogenicity; Cardiovascul...     36
1    Bioaccumulation; Carcinogenicity; Cardiovascul...     36
2    Bioaccumulation; Carcinogenicity; Cardiovascul...     36
3    Bioaccumulation; Carcinogenicity; Dermatotoxic...     36
4    Bioaccumulation; Carcinogenicity; Dermatotoxic...     36
5    Bioaccumulation; Carcinogenicity; Developmenta...      1
6    Bioaccumulation; Carcinogenicity; Developmenta...     36
7    Bioaccumulation; Carcinogenicity; Developmenta...     36
8    Bioaccumulation; Carcinogenicity; Developmenta...     36
9    Bioaccumulation; Carcinogenicity; Environmenta...      2
10   Bioaccumulation; Carcinogenicity; Environmenta...      1
11   Bioaccumulation; Carcinogenicity; Environmenta...      1
12   Bioaccumulation; Carcinogenicity; Environmenta...      1
13   Bioaccumulation; Carcinogenicity; Environmenta...     36
14   Bioaccumulation; Carcinogenicity; Environmenta...      2
15   Bioaccumulation; Carcinogenicity; Environmenta...      1
16   Bioaccumulation; Cardiovascular Toxicity; Derm...     36
17   Bioaccumulation; Developmental Toxicity; Envir...     36
18   Bioaccumulation; Endocrine Toxicity; Environme...      1
19   Bioaccumulation; Endocrine Toxicity; Environme...      2
20   Bioaccumulation; Endocrine toxicity; Environme...      1
21          Bioaccumulation; Environmental Persistence    495
22         Bioaccumulation; Environmental Persistence      36
23   Bioaccumulation; Environmental Persistence; En...      1
24   Bioaccumulation; Environmental Persistence; Fr...      2
25   Bioaccumulation; Environmental Persistence; Re...      1
26   Bioaccumulation; Environmental Persistence; Re...      2
27                  Bioaccumulation; Environmental tox     36
28                                     Carcinogenicity   2885
29   Carcinogenicity; Cardiovascular Toxicity; Derm...     36
30   Carcinogenicity; Cardiovascular Toxicity; Derm...     36
31   Carcinogenicity; Cardiovascular Toxicity; Derm...      1
32   Carcinogenicity; Cardiovascular Toxicity; Deve...      1
33   Carcinogenicity; Cardiovascular Toxicity; Deve...      1
34   Carcinogenicity; Cardiovascular Toxicity; Hema...      1
35   Carcinogenicity; Cardiovascular Toxicity; Hepa...      1
36   Carcinogenicity; Dermatotoxicity; Developmenta...      2
37   Carcinogenicity; Dermatotoxicity; Developmenta...      1
38   Carcinogenicity; Dermatotoxicity; Developmenta...      1
39   Carcinogenicity; Dermatotoxicity; Endocrine To...      1
40   Carcinogenicity; Dermatotoxicity; Hepatotoxici...      1
41   Carcinogenicity; Dermatotoxicity; Hepatotoxici...      1
42   Carcinogenicity; Dermatotoxicity; Hepatotoxici...     36
43   Carcinogenicity; Dermatotoxicity; Hepatotoxici...     36
44   Carcinogenicity; Dermatotoxicity; Hepatotoxici...     36
45   Carcinogenicity; Dermatotoxicity; Neurotoxicit...      1
46   Carcinogenicity; Dermatotoxicity; Ocular Toxic...      1
47             Carcinogenicity; Developmental Toxicity    108
48   Carcinogenicity; Developmental Toxicity; Endoc...     72
49   Carcinogenicity; Developmental Toxicity; Endoc...     36
50   Carcinogenicity; Developmental Toxicity; Envir...     36
51   Carcinogenicity; Developmental Toxicity; Hepat...      1
52   Carcinogenicity; Developmental Toxicity; Hepat...      1
53   Carcinogenicity; Developmental Toxicity; Neuro...      1
54   Carcinogenicity; Endocrine Toxicity; Hepatotox...     36
55   Carcinogenicity; Environmental Persistence; He...      1
56                  Carcinogenicity; Environmental tox     72
57   Carcinogenicity; Environmental tox; Hepatotoxi...     36
58   Carcinogenicity; Environmental tox; Neurotoxicity      1
59                       Carcinogenicity; Genotoxicity     42
60   Carcinogenicity; Hematotoxicity; Hepatotoxicit...      1
61   Carcinogenicity; Hematotoxicity; Other Toxicol...      1
62   Carcinogenicity; Hepatotoxicity and Digestive ...      1
63   Carcinogenicity; Hepatotoxicity and Digestive ...      1
64   Carcinogenicity; Hepatotoxicity and Digestive ...     36
65   Carcinogenicity; Immunotoxicity; Respiratory T...      1
66   Carcinogenicity; Nephrotoxicity and Other Toxi...      1
67   Carcinogenicity; Nephrotoxicity and Other Toxi...     36
68                      Carcinogenicity; Neurotoxicity     38
69   Carcinogenicity; Ocular Toxicity; Reproductive...      1
70              Carcinogenicity; Reproductive Toxicity     74
71   Carcinogenicity; Reproductive Toxicity; Respir...      2
72               Carcinogenicity; Respiratory Toxicity     74
73                             Cardiovascular Toxicity      1
74   Cardiovascular Toxicity; Dermatotoxicity; Hepa...      1
75   Cardiovascular Toxicity; Developmental Toxicit...      1
76              Cardiovascular Toxicity; Neurotoxicity     36
77   Cardiovascular Toxicity; Neurotoxicity; Reprod...     36
78   Dermatotoxicity; Developmental Toxicity; Neuro...      1
79   Dermatotoxicity; Hematotoxicity; Ocular Toxici...      1
80   Dermatotoxicity; Nephrotoxicity and Other Toxi...      1
81   Dermatotoxicity; Neurotoxicity; Ocular Toxicit...      1
82   Dermatotoxicity; Neurotoxicity; Respiratory To...      1
83   Dermatotoxicity; Ocular Toxicity; Reproductive...     36
84   Dermatotoxicity; Ocular Toxicity; Respiratory ...      3
85               Dermatotoxicity; Respiratory Toxicity      1
86                              Developmental Toxicity    218
87          Developmental Toxicity; Endocrine Toxicity      2
88   Developmental Toxicity; Endocrine Toxicity; En...      1
89   Developmental Toxicity; Endocrine Toxicity; He...      2
90   Developmental Toxicity; Endocrine Toxicity; He...    252
91   Developmental Toxicity; Endocrine Toxicity; Im...      1
92   Developmental Toxicity; Endocrine Toxicity; Im...    180
93   Developmental Toxicity; Endocrine Toxicity; Ne...    288
94   Developmental Toxicity; Endocrine Toxicity; Re...      1
95   Developmental Toxicity; Environmental tox; Hep...      1
96   Developmental Toxicity; Environmental tox; Neu...      1
97   Developmental Toxicity; Hematotoxicity; Reprod...      1
98   Developmental Toxicity; Nephrotoxicity and Oth...      1
99   Developmental Toxicity; Nephrotoxicity and Oth...      3
100              Developmental Toxicity; Neurotoxicity     38
101  Developmental Toxicity; Neurotoxicity; Reprodu...     73
102      Developmental Toxicity; Reproductive Toxicity     39
103                                 Endocrine Toxicity    510
104  Endocrine Toxicity; Neurotoxicity; Reproductiv...      1
105          Endocrine Toxicity; Reproductive Toxicity      5
106                                 Endocrine toxicity      1
107                                  Environmental tox    146
108                   Environmental tox; Neurotoxicity     73
109  Environmental tox; Neurotoxicity; Ocular Toxic...      1
110  Environmental tox; Neurotoxicity; Reproductive...      1
111  Environmental tox; Neurotoxicity; Respiratory ...      1
112                                 Fragrance Allergen     57
113                                       Genotoxicity      1
114                             Hazard Trait Undefined   1918
115  Hematotoxicity; Hepatotoxicity and Digestive S...     36
116                      Hematotoxicity; Neurotoxicity      4
117  Hepatotoxicity and Digestive System Toxicity; ...      3
118  Musculoskeletal Toxicity; Neurotoxicity; Respi...      1
119     Musculoskeletal Toxicity; Respiratory Toxicity     37
120  Nephrotoxicity and Other Toxicity to the Urina...      1
121  Nephrotoxicity and Other Toxicity to the Urina...      2
122                                      Neurotoxicity    293
123  Neurotoxicity; Ocular Toxicity; Respiratory To...     36
124               Neurotoxicity; Reproductive Toxicity     36
125  Neurotoxicity; Reproductive Toxicity; Respirat...      1
126                Neurotoxicity; Respiratory Toxicity      2
127                                    Ocular Toxicity     36
128              Ocular Toxicity; Respiratory Toxicity      1
129                              Reproductive Toxicity    626
130        Reproductive Toxicity; Respiratory Toxicity      1
131                               Respiratory Toxicity    414

In [ ]:
hazards["Hazard Traits"].unique()

array(['Bioaccumulation; Carcinogenicity; Cardiovascular Toxicity; Dermatotoxicity; Developmental Toxicity; Environmental Persistence; Nephrotoxicity and Other Toxicity to the Urinary System; Neurotoxicity; Reproductive Toxicity',
       'Bioaccumulation; Carcinogenicity; Cardiovascular Toxicity; Developmental Toxicity; Environmental Persistence; Hematotoxicity; Hepatotoxicity and Digestive System Toxicity; Nephrotoxicity and Other Toxicity to the Urinary System; Neurotoxicity; Reproductive Toxicity',
       'Bioaccumulation; Carcinogenicity; Cardiovascular Toxicity; Environmental Persistence; Environmental tox; Hematotoxicity; Hepatotoxicity and Digestive System Toxicity; Immunotoxicity; Nephrotoxicity and Other Toxicity to the Urinary System; Neurotoxicity',
       'Bioaccumulation; Carcinogenicity; Dermatotoxicity; Endocrine Toxicity; Environmental Persistence; Hematotoxicity; Hepatotoxicity and Digestive System Toxicity; Neurotoxicity; Reproductive Toxicity; Respiratory Toxicity',
       'Bioaccumulation; Carcinogenicity; Dermatotoxicity; Environmental Persistence; Environmental tox; Hepatotoxicity and Digestive System Toxicity; Reproductive Toxicity',
       'Bioaccumulation; Carcinogenicity; Developmental Toxicity; Endocrine Toxicity; Environmental Persistence; Hepatotoxicity and Digestive System Toxicity; Immunotoxicity; Reproductive Toxicity; Respiratory Toxicity',
       'Bioaccumulation; Carcinogenicity; Developmental Toxicity; Endocrine Toxicity; Hepatotoxicity and Digestive System Toxicity; Immunotoxicity; Reproductive Toxicity',
       'Bioaccumulation; Carcinogenicity; Developmental Toxicity; Environmental Persistence; Environmental tox; Musculoskeletal Toxicity; Nephrotoxicity and Other Toxicity to the Urinary System; Reproductive Toxicity; Respiratory Toxicity',
       'Bioaccumulation; Carcinogenicity; Developmental Toxicity; Environmental Persistence; Neurotoxicity; Reproductive Toxicity',
       'Bioaccumulation; Carcinogenicity; Environmental Persistence',
       'Bioaccumulation; Carcinogenicity; Environmental Persistence; Environmental tox; Hematotoxicity; Hepatotoxicity and Digestive System Toxicity; Neurotoxicity; Ocular Toxicity; Other Toxicological Hazard Traits; Respiratory Toxicity',
       'Bioaccumulation; Carcinogenicity; Environmental Persistence; Genotoxicity',
       'Bioaccumulation; Carcinogenicity; Environmental Persistence; Genotoxicity; Neurotoxicity; Reproductive Toxicity',
       'Bioaccumulation; Carcinogenicity; Environmental Persistence; Hematotoxicity; Immunotoxicity; Other Toxicological Hazard Traits; Reproductive Toxicity; Respiratory Toxicity',
       'Bioaccumulation; Carcinogenicity; Environmental Persistence; Hepatotoxicity and Digestive System Toxicity; Immunotoxicity; Reproductive Toxicity',
       'Bioaccumulation; Carcinogenicity; Environmental Persistence; Neurotoxicity; Respiratory Toxicity',
       'Bioaccumulation; Cardiovascular Toxicity; Dermatotoxicity; Developmental Toxicity; Endocrine Toxicity; Environmental Persistence; Hepatotoxicity and Digestive System Toxicity; Musculoskeletal Toxicity; Neurotoxicity; Respiratory Toxicity',
       'Bioaccumulation; Developmental Toxicity; Environmental Persistence; Neurotoxicity; Reproductive Toxicity',
       'Bioaccumulation; Endocrine Toxicity; Environmental Persistence',
       'Bioaccumulation; Endocrine Toxicity; Environmental Persistence; Hepatotoxicity and Digestive System Toxicity; Reproductive Toxicity',
       'Bioaccumulation; Endocrine toxicity; Environmental tox',
       'Bioaccumulation; Environmental Persistence',
       'Bioaccumulation; Environmental Persistence ',
       'Bioaccumulation; Environmental Persistence; Environmental tox',
       'Bioaccumulation; Environmental Persistence; Fragrance Allergen',
       'Bioaccumulation; Environmental Persistence; Reproductive Toxicity',
       'Bioaccumulation; Environmental Persistence; Respiratory Toxicity',
       'Bioaccumulation; Environmental tox', 'Carcinogenicity',
       'Carcinogenicity; Cardiovascular Toxicity; Dermatotoxicity; Developmental Toxicity; Hepatotoxicity and Digestive System Toxicity; Neurotoxicity; Other Toxicological Hazard Traits; Respiratory Toxicity',
       'Carcinogenicity; Cardiovascular Toxicity; Dermatotoxicity; Developmental Toxicity; Neurotoxicity; Respiratory Toxicity',
       'Carcinogenicity; Cardiovascular Toxicity; Dermatotoxicity; Hepatotoxicity and Digestive System Toxicity; Nephrotoxicity and Other Toxicity to the Urinary System; Neurotoxicity; Other Toxicological Hazard Traits',
       'Carcinogenicity; Cardiovascular Toxicity; Developmental Toxicity; Genotoxicity; Hematotoxicity; Immunotoxicity; Neurodevelopmental Toxicity; Neurotoxicity; Reproductive Toxicity; Respiratory Toxicity',
       'Carcinogenicity; Cardiovascular Toxicity; Developmental Toxicity; Respiratory Toxicity',
       'Carcinogenicity; Cardiovascular Toxicity; Hematotoxicity; Respiratory Toxicity',
       'Carcinogenicity; Cardiovascular Toxicity; Hepatotoxicity and Digestive System Toxicity; Neurotoxicity; Respiratory Toxicity',
       'Carcinogenicity; Dermatotoxicity; Developmental Toxicity; Genotoxicity; Hematotoxicity; Neurotoxicity; Reproductive Toxicity; Respiratory Toxicity',
       'Carcinogenicity; Dermatotoxicity; Developmental Toxicity; Genotoxicity; Neurotoxicity; Ocular Toxicity; Reproductive Toxicity; Respiratory Toxicity',
       'Carcinogenicity; Dermatotoxicity; Developmental Toxicity; Hematotoxicity; Hepatotoxicity and Digestive System Toxicity; Reproductive Toxicity; Respiratory Toxicity',
       'Carcinogenicity; Dermatotoxicity; Endocrine Toxicity; Hepatotoxicity and Digestive System Toxicity; Nephrotoxicity and Other Toxicity to the Urinary System; Neurotoxicity; Ocular Toxicity',
       'Carcinogenicity; Dermatotoxicity; Hepatotoxicity and Digestive System Toxicity; Nephrotoxicity and Other Toxicity to the Urinary System; Neurotoxicity; Ocular Toxicity',
       'Carcinogenicity; Dermatotoxicity; Hepatotoxicity and Digestive System Toxicity; Nephrotoxicity and Other Toxicity to the Urinary System; Neurotoxicity; Ocular Toxicity; Reproductive Toxicity; Respiratory Toxicity',
       'Carcinogenicity; Dermatotoxicity; Hepatotoxicity and Digestive System Toxicity; Neurotoxicity',
       'Carcinogenicity; Dermatotoxicity; Hepatotoxicity and Digestive System Toxicity; Ocular Toxicity; Respiratory Toxicity',
       'Carcinogenicity; Dermatotoxicity; Hepatotoxicity and Digestive System Toxicity; Reproductive Toxicity',
       'Carcinogenicity; Dermatotoxicity; Neurotoxicity; Ocular Toxicity; Respiratory Toxicity',
       'Carcinogenicity; Dermatotoxicity; Ocular Toxicity; Respiratory Toxicity',
       'Carcinogenicity; Developmental Toxicity',
       'Carcinogenicity; Developmental Toxicity; Endocrine Toxicity; Immunotoxicity; Reproductive Toxicity; Respiratory Toxicity',
       'Carcinogenicity; Developmental Toxicity; Endocrine Toxicity; Neurotoxicity; Reproductive Toxicity',
       'Carcinogenicity; Developmental Toxicity; Environmental tox; Hematotoxicity; Immunotoxicity; Other Toxicological Hazard Traits; Respiratory Toxicity',
       'Carcinogenicity; Developmental Toxicity; Hepatotoxicity and Digestive System Toxicity; Nephrotoxicity and Other Toxicity to the Urinary System; Neurotoxicity; Ocular Toxicity',
       'Carcinogenicity; Developmental Toxicity; Hepatotoxicity and Digestive System Toxicity; Neurotoxicity; Ocular Toxicity; Reproductive Toxicity; Respiratory Toxicity',
       'Carcinogenicity; Developmental Toxicity; Neurotoxicity; Reproductive Toxicity',
       'Carcinogenicity; Endocrine Toxicity; Hepatotoxicity and Digestive System Toxicity; Nephrotoxicity and Other Toxicity to the Urinary System; Respiratory Toxicity',
       'Carcinogenicity; Environmental Persistence; Hematotoxicity; Hepatotoxicity and Digestive System Toxicity; Nephrotoxicity and Other Toxicity to the Urinary System; Neurotoxicity',
       'Carcinogenicity; Environmental tox',
       'Carcinogenicity; Environmental tox; Hepatotoxicity and Digestive System Toxicity; Immunotoxicity; Respiratory Toxicity',
       'Carcinogenicity; Environmental tox; Neurotoxicity',
       'Carcinogenicity; Genotoxicity',
       'Carcinogenicity; Hematotoxicity; Hepatotoxicity and Digestive System Toxicity; Nephrotoxicity and Other Toxicity to the Urinary System; Neurotoxicity; Ocular Toxicity; Respiratory Toxicity',
       'Carcinogenicity; Hematotoxicity; Other Toxicological Hazard Traits',
       'Carcinogenicity; Hepatotoxicity and Digestive System Toxicity',
       'Carcinogenicity; Hepatotoxicity and Digestive System Toxicity; Neurotoxicity; Respiratory Toxicity',
       'Carcinogenicity; Hepatotoxicity and Digestive System Toxicity; Respiratory Toxicity',
       'Carcinogenicity; Immunotoxicity; Respiratory Toxicity',
       'Carcinogenicity; Nephrotoxicity and Other Toxicity to the Urinary System; Neurotoxicity',
       'Carcinogenicity; Nephrotoxicity and Other Toxicity to the Urinary System; Respiratory Toxicity',
       'Carcinogenicity; Neurotoxicity',
       'Carcinogenicity; Ocular Toxicity; Reproductive Toxicity; Respiratory Toxicity',
       'Carcinogenicity; Reproductive Toxicity',
       'Carcinogenicity; Reproductive Toxicity; Respiratory Toxicity',
       'Carcinogenicity; Respiratory Toxicity', 'Cardiovascular Toxicity',
       'Cardiovascular Toxicity; Dermatotoxicity; Hepatotoxicity and Digestive System Toxicity; Nephrotoxicity and Other Toxicity to the Urinary System; Neurotoxicity; Ocular Toxicity; Other Toxicological Hazard Traits; Respiratory Toxicity',
       'Cardiovascular Toxicity; Developmental Toxicity; Hepatotoxicity and Digestive System Toxicity; Immunotoxicity; Neurotoxicity; Respiratory Toxicity',
       'Cardiovascular Toxicity; Neurotoxicity',
       'Cardiovascular Toxicity; Neurotoxicity; Reproductive Toxicity; Respiratory Toxicity',
       'Dermatotoxicity; Developmental Toxicity; Neurotoxicity; Ocular Toxicity; Respiratory Toxicity',
       'Dermatotoxicity; Hematotoxicity; Ocular Toxicity; Respiratory Toxicity',
       'Dermatotoxicity; Nephrotoxicity and Other Toxicity to the Urinary System; Respiratory Toxicity',
       'Dermatotoxicity; Neurotoxicity; Ocular Toxicity; Respiratory Toxicity',
       'Dermatotoxicity; Neurotoxicity; Respiratory Toxicity',
       'Dermatotoxicity; Ocular Toxicity; Reproductive Toxicity; Respiratory Toxicity',
       'Dermatotoxicity; Ocular Toxicity; Respiratory Toxicity',
       'Dermatotoxicity; Respiratory Toxicity', 'Developmental Toxicity',
       'Developmental Toxicity; Endocrine Toxicity',
       'Developmental Toxicity; Endocrine Toxicity; Environmental tox; Immunotoxicity; Ocular Toxicity; Reproductive Toxicity; Respiratory Toxicity',
       'Developmental Toxicity; Endocrine Toxicity; Hepatotoxicity and Digestive System Toxicity; Immunotoxicity; Other Toxicological Hazard Traits; Reproductive Toxicity; Respiratory Toxicity',
       'Developmental Toxicity; Endocrine Toxicity; Hepatotoxicity and Digestive System Toxicity; Neurotoxicity; Reproductive Toxicity',
       'Developmental Toxicity; Endocrine Toxicity; Immunotoxicity; Other Toxicological Hazard Traits; Reproductive Toxicity; Respiratory Toxicity',
       'Developmental Toxicity; Endocrine Toxicity; Immunotoxicity; Reproductive Toxicity; Respiratory Toxicity',
       'Developmental Toxicity; Endocrine Toxicity; Neurotoxicity; Reproductive Toxicity',
       'Developmental Toxicity; Endocrine Toxicity; Reproductive Toxicity',
       'Developmental Toxicity; Environmental tox; Hepatotoxicity and Digestive System Toxicity; Nephrotoxicity and Other Toxicity to the Urinary System; Neurodevelopmental Toxicity; Neurotoxicity; Reproductive Toxicity',
       'Developmental Toxicity; Environmental tox; Neurotoxicity',
       'Developmental Toxicity; Hematotoxicity; Reproductive Toxicity',
       'Developmental Toxicity; Nephrotoxicity and Other Toxicity to the Urinary System; Neurotoxicity; Ocular Toxicity; Respiratory Toxicity',
       'Developmental Toxicity; Nephrotoxicity and Other Toxicity to the Urinary System; Ocular Toxicity; Respiratory Toxicity',
       'Developmental Toxicity; Neurotoxicity',
       'Developmental Toxicity; Neurotoxicity; Reproductive Toxicity',
       'Developmental Toxicity; Reproductive Toxicity',
       'Endocrine Toxicity',
       'Endocrine Toxicity; Neurotoxicity; Reproductive Toxicity',
       'Endocrine Toxicity; Reproductive Toxicity', 'Endocrine toxicity',
       'Environmental tox', 'Environmental tox; Neurotoxicity',
       'Environmental tox; Neurotoxicity; Ocular Toxicity; Respiratory Toxicity',
       'Environmental tox; Neurotoxicity; Reproductive Toxicity',
       'Environmental tox; Neurotoxicity; Respiratory Toxicity',
       'Fragrance Allergen', 'Genotoxicity', 'Hazard Trait Undefined',
       'Hematotoxicity; Hepatotoxicity and Digestive System Toxicity; Nephrotoxicity and Other Toxicity to the Urinary System; Neurotoxicity',
       'Hematotoxicity; Neurotoxicity',
       'Hepatotoxicity and Digestive System Toxicity; Neurotoxicity',
       'Musculoskeletal Toxicity; Neurotoxicity; Respiratory Toxicity',
       'Musculoskeletal Toxicity; Respiratory Toxicity',
       'Nephrotoxicity and Other Toxicity to the Urinary System',
       'Nephrotoxicity and Other Toxicity to the Urinary System; Neurotoxicity',
       'Neurotoxicity',
       'Neurotoxicity; Ocular Toxicity; Respiratory Toxicity',
       'Neurotoxicity; Reproductive Toxicity',
       'Neurotoxicity; Reproductive Toxicity; Respiratory Toxicity',
       'Neurotoxicity; Respiratory Toxicity', 'Ocular Toxicity',
       'Ocular Toxicity; Respiratory Toxicity', 'Reproductive Toxicity',
       'Reproductive Toxicity; Respiratory Toxicity',
       'Respiratory Toxicity'], dtype=object)

In [ ]:
hazards.sort_values("count", ascending = False)

                                         Hazard Traits  count
28                                     Carcinogenicity   2885
114                             Hazard Trait Undefined   1918
129                              Reproductive Toxicity    626
103                                 Endocrine Toxicity    510
21          Bioaccumulation; Environmental Persistence    495
131                               Respiratory Toxicity    414
122                                      Neurotoxicity    293
93   Developmental Toxicity; Endocrine Toxicity; Ne...    288
90   Developmental Toxicity; Endocrine Toxicity; He...    252
86                              Developmental Toxicity    218
92   Developmental Toxicity; Endocrine Toxicity; Im...    180
107                                  Environmental tox    146
47             Carcinogenicity; Developmental Toxicity    108
70              Carcinogenicity; Reproductive Toxicity     74
72               Carcinogenicity; Respiratory Toxicity     74
108                   Environmental tox; Neurotoxicity     73
101  Developmental Toxicity; Neurotoxicity; Reprodu...     73
48   Carcinogenicity; Developmental Toxicity; Endoc...     72
56                  Carcinogenicity; Environmental tox     72
112                                 Fragrance Allergen     57
59                       Carcinogenicity; Genotoxicity     42
102      Developmental Toxicity; Reproductive Toxicity     39
100              Developmental Toxicity; Neurotoxicity     38
68                      Carcinogenicity; Neurotoxicity     38
119     Musculoskeletal Toxicity; Respiratory Toxicity     37
44   Carcinogenicity; Dermatotoxicity; Hepatotoxici...     36
50   Carcinogenicity; Developmental Toxicity; Envir...     36
54   Carcinogenicity; Endocrine Toxicity; Hepatotox...     36
64   Carcinogenicity; Hepatotoxicity and Digestive ...     36
57   Carcinogenicity; Environmental tox; Hepatotoxi...     36
49   Carcinogenicity; Developmental Toxicity; Endoc...     36
76              Cardiovascular Toxicity; Neurotoxicity     36
1    Bioaccumulation; Carcinogenicity; Cardiovascul...     36
67   Carcinogenicity; Nephrotoxicity and Other Toxi...     36
127                                    Ocular Toxicity     36
77   Cardiovascular Toxicity; Neurotoxicity; Reprod...     36
83   Dermatotoxicity; Ocular Toxicity; Reproductive...     36
42   Carcinogenicity; Dermatotoxicity; Hepatotoxici...     36
124               Neurotoxicity; Reproductive Toxicity     36
123  Neurotoxicity; Ocular Toxicity; Respiratory To...     36
115  Hematotoxicity; Hepatotoxicity and Digestive S...     36
43   Carcinogenicity; Dermatotoxicity; Hepatotoxici...     36
0    Bioaccumulation; Carcinogenicity; Cardiovascul...     36
27                  Bioaccumulation; Environmental tox     36
4    Bioaccumulation; Carcinogenicity; Dermatotoxic...     36
17   Bioaccumulation; Developmental Toxicity; Envir...     36
8    Bioaccumulation; Carcinogenicity; Developmenta...     36
7    Bioaccumulation; Carcinogenicity; Developmenta...     36
13   Bioaccumulation; Carcinogenicity; Environmenta...     36
29   Carcinogenicity; Cardiovascular Toxicity; Derm...     36
6    Bioaccumulation; Carcinogenicity; Developmenta...     36
16   Bioaccumulation; Cardiovascular Toxicity; Derm...     36
30   Carcinogenicity; Cardiovascular Toxicity; Derm...     36
22         Bioaccumulation; Environmental Persistence      36
3    Bioaccumulation; Carcinogenicity; Dermatotoxic...     36
2    Bioaccumulation; Carcinogenicity; Cardiovascul...     36
105          Endocrine Toxicity; Reproductive Toxicity      5
116                      Hematotoxicity; Neurotoxicity      4
84   Dermatotoxicity; Ocular Toxicity; Respiratory ...      3
99   Developmental Toxicity; Nephrotoxicity and Oth...      3
117  Hepatotoxicity and Digestive System Toxicity; ...      3
89   Developmental Toxicity; Endocrine Toxicity; He...      2
24   Bioaccumulation; Environmental Persistence; Fr...      2
71   Carcinogenicity; Reproductive Toxicity; Respir...      2
26   Bioaccumulation; Environmental Persistence; Re...      2
19   Bioaccumulation; Endocrine Toxicity; Environme...      2
14   Bioaccumulation; Carcinogenicity; Environmenta...      2
87          Developmental Toxicity; Endocrine Toxicity      2
121  Nephrotoxicity and Other Toxicity to the Urina...      2
9    Bioaccumulation; Carcinogenicity; Environmenta...      2
126                Neurotoxicity; Respiratory Toxicity      2
36   Carcinogenicity; Dermatotoxicity; Developmenta...      2
15   Bioaccumulation; Carcinogenicity; Environmenta...      1
95   Developmental Toxicity; Environmental tox; Hep...      1
130        Reproductive Toxicity; Respiratory Toxicity      1
128              Ocular Toxicity; Respiratory Toxicity      1
96   Developmental Toxicity; Environmental tox; Neu...      1
97   Developmental Toxicity; Hematotoxicity; Reprod...      1
98   Developmental Toxicity; Nephrotoxicity and Oth...      1
125  Neurotoxicity; Reproductive Toxicity; Respirat...      1
5    Bioaccumulation; Carcinogenicity; Developmenta...      1
111  Environmental tox; Neurotoxicity; Respiratory ...      1
110  Environmental tox; Neurotoxicity; Reproductive...      1
120  Nephrotoxicity and Other Toxicity to the Urina...      1
104  Endocrine Toxicity; Neurotoxicity; Reproductiv...      1
118  Musculoskeletal Toxicity; Neurotoxicity; Respi...      1
106                                 Endocrine toxicity      1
12   Bioaccumulation; Carcinogenicity; Environmenta...      1
11   Bioaccumulation; Carcinogenicity; Environmenta...      1
109  Environmental tox; Neurotoxicity; Ocular Toxic...      1
113                                       Genotoxicity      1
10   Bioaccumulation; Carcinogenicity; Environmenta...      1
94   Developmental Toxicity; Endocrine Toxicity; Re...      1
41   Carcinogenicity; Dermatotoxicity; Hepatotoxici...      1
18   Bioaccumulation; Endocrine Toxicity; Environme...      1
35   Carcinogenicity; Cardiovascular Toxicity; Hepa...      1
61   Carcinogenicity; Hematotoxicity; Other Toxicol...      1
60   Carcinogenicity; Hematotoxicity; Hepatotoxicit...      1
32   Carcinogenicity; Cardiovascular Toxicity; Deve...      1
58   Carcinogenicity; Environmental tox; Neurotoxicity      1
33   Carcinogenicity; Cardiovascular Toxicity; Deve...      1
34   Carcinogenicity; Cardiovascular Toxicity; Hema...      1
55   Carcinogenicity; Environmental Persistence; He...      1
53   Carcinogenicity; Developmental Toxicity; Neuro...      1
91   Developmental Toxicity; Endocrine Toxicity; Im...      1
52   Carcinogenicity; Developmental Toxicity; Hepat...      1
51   Carcinogenicity; Developmental Toxicity; Hepat...      1
37   Carcinogenicity; Dermatotoxicity; Developmenta...      1
38   Carcinogenicity; Dermatotoxicity; Developmenta...      1
39   Carcinogenicity; Dermatotoxicity; Endocrine To...      1
46   Carcinogenicity; Dermatotoxicity; Ocular Toxic...      1
45   Carcinogenicity; Dermatotoxicity; Neurotoxicit...      1
62   Carcinogenicity; Hepatotoxicity and Digestive ...      1
63   Carcinogenicity; Hepatotoxicity and Digestive ...      1
31   Carcinogenicity; Cardiovascular Toxicity; Derm...      1
65   Carcinogenicity; Immunotoxicity; Respiratory T...      1
88   Developmental Toxicity; Endocrine Toxicity; En...      1
40   Carcinogenicity; Dermatotoxicity; Hepatotoxici...      1
20   Bioaccumulation; Endocrine toxicity; Environme...      1
85               Dermatotoxicity; Respiratory Toxicity      1
82   Dermatotoxicity; Neurotoxicity; Respiratory To...      1
81   Dermatotoxicity; Neurotoxicity; Ocular Toxicit...      1
80   Dermatotoxicity; Nephrotoxicity and Other Toxi...      1
79   Dermatotoxicity; Hematotoxicity; Ocular Toxici...      1
78   Dermatotoxicity; Developmental Toxicity; Neuro...      1
23   Bioaccumulation; Environmental Persistence; En...      1
75   Cardiovascular Toxicity; Developmental Toxicit...      1
74   Cardiovascular Toxicity; Dermatotoxicity; Hepa...      1
73                             Cardiovascular Toxicity      1
25   Bioaccumulation; Environmental Persistence; Re...      1
69   Carcinogenicity; Ocular Toxicity; Reproductive...      1
66   Carcinogenicity; Nephrotoxicity and Other Toxi...      1