In [358]:
import pandas as pd

In [359]:
chemicals = pd.read_csv("data/chemical_names_cleaned_2_18.csv")

In [360]:
chemicals.head()

,original_ingredient,cas_number,clean_name,api_rn,api_name
0,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,8023-85-6,Cedrus Atlantica Oil,8023-85-6,Cedrus Atlantica Oil
1,"[3R-(3a,3aß,7ß,8aa)]-1-(2,3,4,7,8,8a-hexahydro...",32388-55-9,Acetylcedrene,32388-55-9,Acetylcedrene
2,"1-Naphthalenepropanol, a-ethenyldecahydro- 2-h...",515-03-7,Sclareol,515-03-7,Sclareol
3,Myroxylon Pereirae Oil/Extract (Myroxylon bals...,8007-00-9,Myroxylon Pereirae Oil/Extract,8007-00-9,Myroxylon Pereirae Oil/Extract
4,Turpentine gum (Pinus spp.); Turpentine oil an...,9005-90-7,Turpentine,9005-90-7,Turpentine

In [361]:
chemicals = chemicals.rename(columns = {"original_ingredient": 'Ingredient Name'})

In [362]:
chemicals.head()

,Ingredient Name,cas_number,clean_name,api_rn,api_name
0,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,8023-85-6,Cedrus Atlantica Oil,8023-85-6,Cedrus Atlantica Oil
1,"[3R-(3a,3aß,7ß,8aa)]-1-(2,3,4,7,8,8a-hexahydro...",32388-55-9,Acetylcedrene,32388-55-9,Acetylcedrene
2,"1-Naphthalenepropanol, a-ethenyldecahydro- 2-h...",515-03-7,Sclareol,515-03-7,Sclareol
3,Myroxylon Pereirae Oil/Extract (Myroxylon bals...,8007-00-9,Myroxylon Pereirae Oil/Extract,8007-00-9,Myroxylon Pereirae Oil/Extract
4,Turpentine gum (Pinus spp.); Turpentine oil an...,9005-90-7,Turpentine,9005-90-7,Turpentine

In [363]:
len(chemicals)

505

In [364]:
all_data = pd.read_csv("data/CDPH Search results - 1_12_2026, 3_34_15 PM.csv")

In [366]:
len(all_data)

534508

In [367]:
first_merge = all_data.merge(chemicals, on = "Ingredient Name", how = 'left')

In [368]:
first_merge.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,Concentration,Ingredient Submitted Date,Ingredient Removed Date,cas_number,clean_name,api_rn,api_name
0,18358,Nail Alliance - Entity,Entity Nudite,Cool Pink Nail Sculpting Powder,NaN,NaN,6/24/2019,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,5.000000,6/24/2019,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania
1,38661,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,40.000000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania
2,38662,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Sprinkle,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,31.000000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania
3,38667,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,12.000000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania
4,38665,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,21.500000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania

In [369]:
first_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 534508 entries, 0 to 534507
Data columns (total 17 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Product Id                 534508 non-null  int64
 1   Company                    534508 non-null  object
 2   Brand                      534308 non-null  object
 3   Product Name               534508 non-null  object
 4   Variant                    187813 non-null  object
 5   Product Discontinued Date  39102 non-null   object
 6   Product Submitted Date     534508 non-null  object
 7   Ingredient Name            534186 non-null  object
 8   Function                   433384 non-null  object
 9   Unit of Measure            222747 non-null  object
 10  Concentration              224495 non-null  object
 11  Ingredient Submitted Date  534186 non-null  object
 12  Ingredient Removed Date    6627 non-null    object
 13  cas_number                 447569 non-null  object
 14  clean_name                 534186 non-null  object
 15  api_rn                     532360 non-null  object
 16  api_name                   534186 non-null  object
dtypes: int64(1), object(16)
memory usage: 69.3+ MB

In [370]:
na = first_merge[first_merge["api_name"].isna()]
na.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,Concentration,Ingredient Submitted Date,Ingredient Removed Date,cas_number,clean_name,api_rn,api_name
1402,72818,Exclusive Fragrances & Cosmetics,10 Corso Como,10 Corso Como Massage Oil,10 Corso Como,NaN,6/29/2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404,72816,IPD Inc,10 Corso Como,Corso Como Bath Pearls,Corso Como,NaN,6/25/2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10283,109738,Aloisia Beauty Products Inc.,Aloisia Beauty,Light Hydration Emulsion,NaN,NaN,6/6/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10284,109736,Aloisia Beauty Products Inc.,Aloisia Beauty,Renew Concentrated Serum,NaN,NaN,6/6/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10286,109739,Aloisia Beauty Products Inc.,Aloisia Beauty,Revitalize Eye Cream,NaN,NaN,6/6/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [371]:
na["Ingredient Name"].unique()

array([nan], dtype=object)

In [372]:
na_ingredients = na["Ingredient Name"].unique().tolist()
na_ingredients

[nan]

In [373]:
na_names = pd.DataFrame(na_ingredients)

In [374]:
na_names.to_csv("na_names.csv")

In [375]:
na_names_cleaned = pd.read_csv("data/na_names_cleaned.csv", encoding='latin-1')

na_names_cleaned = na_names_cleaned.apply(
    lambda col: col.str.replace('\xa0', ' ', regex=False) if col.dtype == 'object' else col
)

In [376]:
na_names_cleaned["name"].unique().tolist()

['Cedrus Atlantica Oil/Extract (Cedrus atlantica\\xa0oil and extract; Cedrus Atlantica Bark Extract; Cedrus Atlantica Bark Oil; Cedrus Atlantica Bark Water; Cedrus Atlantica Leaf Extract; Cedrus Atlantica Wood Extract; Cedrus Atlantica Wood Oil) 92201-55-3 / 8023-85-6,',
 '[3R-(3a,3a§,7§,8aa)]-1-(2,3,4,7,8,8a-hexahydro-3,6,8,8-tetramethyl-1H-3a,7-methanoazulen-5-yl)ethan-1-one (Acetyl Cedrene) 32388-55-9,',
 '1-Naphthalenepropanol, a-ethenyldecahydro- 2-hydroxy-a,2,5,5,8a-pentamethyl-, [1R-[1a(R),2§,4a§,8aa]]- (Sclareol; [1R-(1alpha)]-alpha-Ethenyldecahydro-2-hydroxy-a,2,5,5,8a-pentamethyl-1-naphthalenepropanol) 515-03-7,',
 'Myroxylon Pereirae Oil/Extract (Myroxylon balsamum\\xa0var.\\xa0pereirae; extracts and distillates; Balsam Peru oil, absolute and anhydrol (Balsam Oil Peru); Myroxylon Balsamum Pereirae Balsam Extract; Myroxylon Balsamum Pereirae Balsam Oil; Myroxylon Pereirae Oil; Myroxylon Pereirae Resin Extract; Myroxylon Pereirae Resin; Myroxylon Pereirae (Balsam Peru) Oil; Myroxylon Pereirae (Balsam Peru) Resin; Myroxylon Pereirae (Balsam Peru) Resin Extract) 8007-00-9,',
 'Turpentine gum (Pinus\\xa0spp.); Turpentine oil and rectified oil; Turpentine, steam distilled (Pinus\\xa0spp.) (Turpentine) 9005-90-7 / 8006-64-2 / 8052-14-0,',
 'Butane (containing greater than or equal to  0,1\\xa0% butadiene (203-450-8)) 106-97-8,',
 ' Pinus Mugo (Pinus mugo\\xa0leaf and twig oil and extract; Pinus Mugo Leaf Oil; Pinus Mugo Twig Leaf Extract; Pinus Mugo Twig Oil; Pinus Mugo Leaf/Twig Extract) 90082-72-7,',
 '(±)-1,7,7-trimethyl-3-[(4-methylphenyl)methylene]bicyclo[2.2.1]heptan-2-one (covering any of the individual isomers and/or combinations thereof (4-MBC); 4-Methylbenzylidene Camphor (4-MBC)) 36861-47-9,',
 'Pinus Pumila (Pinus pumila\\xa0leaf and twig oil and extract; Pinus Pumila Needle Extract; Pinus Pumila Twig Leaf Extract; Pinus Pumila Twig Leaf Oil; Pinus Mugo Leaf/Twig Extract; Pinus Mugo Twig Oil; Pinus Pumilio Branch/Leaf Oil; Pinus Pumilio Leaf Extract) 97676-05-6],']

In [377]:
na_names_cleaned = na_names_cleaned.rename(columns={'name': 'Ingredient Name'})
na_names_cleaned = na_names_cleaned.rename(columns={'api_cas': 'api_rn'})
na_names_cleaned.head()

,Ingredient Name,api_rn,api_name
0,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,8023-85-6,Cedrus Atlantica Oil
1,"[3R-(3a,3a§,7§,8aa)]-1-(2,3,4,7,8,8a-hexahydro...",32388-55-9,Acetylcedrene
2,"1-Naphthalenepropanol, a-ethenyldecahydro- 2-h...",515-03-7,Sclareol
3,Myroxylon Pereirae Oil/Extract (Myroxylon bals...,8007-00-9,Myroxylon Pereirae Oil/Extract
4,Turpentine gum (Pinus\xa0spp.); Turpentine oil...,9005-90-7,Turpentine

In [378]:
first_merge.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,Concentration,Ingredient Submitted Date,Ingredient Removed Date,cas_number,clean_name,api_rn,api_name
0,18358,Nail Alliance - Entity,Entity Nudite,Cool Pink Nail Sculpting Powder,NaN,NaN,6/24/2019,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,5.000000,6/24/2019,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania
1,38661,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,40.000000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania
2,38662,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Sprinkle,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,31.000000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania
3,38667,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,12.000000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania
4,38665,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,21.500000,9/21/2015,NaN,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania

In [379]:
first_merge.update(na_names_cleaned)

In [380]:
na_names_cleaned

,Ingredient Name,api_rn,api_name
0,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,8023-85-6,Cedrus Atlantica Oil
1,"[3R-(3a,3a§,7§,8aa)]-1-(2,3,4,7,8,8a-hexahydro...",32388-55-9,Acetylcedrene
2,"1-Naphthalenepropanol, a-ethenyldecahydro- 2-h...",515-03-7,Sclareol
3,Myroxylon Pereirae Oil/Extract (Myroxylon bals...,8007-00-9,Myroxylon Pereirae Oil/Extract
4,Turpentine gum (Pinus\xa0spp.); Turpentine oil...,9005-90-7,Turpentine
5,Butane (containing greater than or equal to 0...,106-97-8,Butane
6,Pinus Mugo (Pinus mugo\xa0leaf and twig oil a...,90082-72-7,"Pine,ÊPinus mugo, ext."
7,"(±)-1,7,7-trimethyl-3-[(4-methylphenyl)methyle...",36861-47-9,3-(4_-Methylbenzylidene)camphor
8,Pinus Pumila (Pinus pumila\xa0leaf and twig oi...,97676-05-6,"Pine,ÊPinus pumila, ext."

In [381]:
first_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 534508 entries, 0 to 534507
Data columns (total 17 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Product Id                 534508 non-null  int64
 1   Company                    534508 non-null  object
 2   Brand                      534308 non-null  object
 3   Product Name               534508 non-null  object
 4   Variant                    187813 non-null  object
 5   Product Discontinued Date  39102 non-null   object
 6   Product Submitted Date     534508 non-null  object
 7   Ingredient Name            534186 non-null  object
 8   Function                   433384 non-null  object
 9   Unit of Measure            222747 non-null  object
 10  Concentration              224495 non-null  object
 11  Ingredient Submitted Date  534186 non-null  object
 12  Ingredient Removed Date    6627 non-null    object
 13  cas_number                 447569 non-null  object
 14  clean_name                 534186 non-null  object
 15  api_rn                     532360 non-null  object
 16  api_name                   534186 non-null  object
dtypes: int64(1), object(16)
memory usage: 69.3+ MB

In [382]:
harms = pd.read_csv("reportable_ingredients.csv")

In [383]:
harms.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3324 entries, 0 to 3323
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Chemical Name                 3324 non-null   object
 1   CAS RN                        3049 non-null   object
 2   Synonyms                      571 non-null    object
 3   Hazard Traits                 3324 non-null   object
 4   Authoritative List            3324 non-null   object
 5   When to Report (Any, FF, FA)  3324 non-null   object
 6   Unnamed: 6                    1 non-null      object
dtypes: object(7)
memory usage: 181.9+ KB

In [384]:
harms.rename(columns={'CAS RN': 'api_rn'}, inplace=True)

In [385]:
chemicals.head()

,Ingredient Name,cas_number,clean_name,api_rn,api_name
0,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,8023-85-6,Cedrus Atlantica Oil,8023-85-6,Cedrus Atlantica Oil
1,"[3R-(3a,3aß,7ß,8aa)]-1-(2,3,4,7,8,8a-hexahydro...",32388-55-9,Acetylcedrene,32388-55-9,Acetylcedrene
2,"1-Naphthalenepropanol, a-ethenyldecahydro- 2-h...",515-03-7,Sclareol,515-03-7,Sclareol
3,Myroxylon Pereirae Oil/Extract (Myroxylon bals...,8007-00-9,Myroxylon Pereirae Oil/Extract,8007-00-9,Myroxylon Pereirae Oil/Extract
4,Turpentine gum (Pinus spp.); Turpentine oil an...,9005-90-7,Turpentine,9005-90-7,Turpentine

In [386]:
chemicals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Ingredient Name  504 non-null    object
 1   cas_number       380 non-null    object
 2   clean_name       504 non-null    object
 3   api_rn           489 non-null    object
 4   api_name         504 non-null    object
dtypes: object(5)
memory usage: 19.9+ KB

In [387]:
len(chemicals)

505

In [388]:
harms.head()

,Chemical Name,api_rn,Synonyms,Hazard Traits,Authoritative List,"When to Report (Any, FF, FA)",Unnamed: 6
0,(±) Tetrahydrofurfuryl (R)-2-[4-(6-chloroquino...,119738-06-6,NaN,Reproductive Toxicity,EC Annex VI CMRs - Cat. 1B,FF,NaN
1,"(±)-1,7,7-trimethyl-3-[(4-methylphenyl)methyle...",36861-47-9,"4-Methylbenzylidene Camphor (4-MBC); (±)-1,7,7...",Endocrine Toxicity,EC EDs,FF,NaN
2,"(1a,2a,3ß,6ß)-1,2,3,6-tetrahydro-3,6-methanoph...",2746-19-2,NaN,Respiratory Toxicity,EC Annex VI Resp. Sens. - Cat. 1,FF,NaN
3,"(1R,3E,4S)-1,7,7-trimethyl-3-(4-methylbenzylid...",95342-41-9,NaN,Endocrine Toxicity,EC EDs,FF,NaN
4,"(1R,3Z,4S)-1,7,7-trimethyl-3-(4-methylbenzylid...",852541-21-0,NaN,Endocrine Toxicity,EC EDs,FF,NaN

In [389]:
len(harms)

3324

In [390]:
harms.head()

,Chemical Name,api_rn,Synonyms,Hazard Traits,Authoritative List,"When to Report (Any, FF, FA)",Unnamed: 6
0,(±) Tetrahydrofurfuryl (R)-2-[4-(6-chloroquino...,119738-06-6,NaN,Reproductive Toxicity,EC Annex VI CMRs - Cat. 1B,FF,NaN
1,"(±)-1,7,7-trimethyl-3-[(4-methylphenyl)methyle...",36861-47-9,"4-Methylbenzylidene Camphor (4-MBC); (±)-1,7,7...",Endocrine Toxicity,EC EDs,FF,NaN
2,"(1a,2a,3ß,6ß)-1,2,3,6-tetrahydro-3,6-methanoph...",2746-19-2,NaN,Respiratory Toxicity,EC Annex VI Resp. Sens. - Cat. 1,FF,NaN
3,"(1R,3E,4S)-1,7,7-trimethyl-3-(4-methylbenzylid...",95342-41-9,NaN,Endocrine Toxicity,EC EDs,FF,NaN
4,"(1R,3Z,4S)-1,7,7-trimethyl-3-(4-methylbenzylid...",852541-21-0,NaN,Endocrine Toxicity,EC EDs,FF,NaN

In [391]:
harms_agg = harms.groupby('api_rn').agg({
    'Hazard Traits': ', '.join,
    'Chemical Name': 'first',
    'Synonyms': 'first',
    'Authoritative List': ', '.join,
    'When to Report (Any, FF, FA)': 'first'
}).reset_index()
len(harms_agg)
harms_agg.head()

,api_rn,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)"
0,85-00-7,Hazard Trait Undefined,Diquat dibromide,None,CECBP - Priority Chemicals,FF
1,100-00-5,Carcinogenicity,1-Chloro-4-nitrobenzene,4-Chloronitrobenzene,IARC Carcinogens - 2B; Prop 65,Any
2,100-02-7,Dermatotoxicity; Environmental tox; Other Toxi...,4-Nitrophenol,None,CA TACs; CECBP - Priority Chemicals; CWA 303(c...,FF
3,100-17-4,Carcinogenicity,para-Nitroanisole,None,IARC Carcinogens - 2B; Prop 65,Any
4,100-25-4,Reproductive Toxicity,p-Dinitrobenzene,None,Prop 65,Any

In [392]:
chemicals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Ingredient Name  504 non-null    object
 1   cas_number       380 non-null    object
 2   clean_name       504 non-null    object
 3   api_rn           489 non-null    object
 4   api_name         504 non-null    object
dtypes: object(5)
memory usage: 19.9+ KB

In [393]:
result = chemicals.merge(harms_agg, on='api_rn', how='left')
result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 10 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Ingredient Name               504 non-null    object
 1   cas_number                    380 non-null    object
 2   clean_name                    504 non-null    object
 3   api_rn                        489 non-null    object
 4   api_name                      504 non-null    object
 5   Hazard Traits                 359 non-null    object
 6   Chemical Name                 359 non-null    object
 7   Synonyms                      213 non-null    object
 8   Authoritative List            359 non-null    object
 9   When to Report (Any, FF, FA)  359 non-null    object
dtypes: object(10)
memory usage: 39.6+ KB

In [394]:
len(result)

505

In [395]:
na = result[result["Hazard Traits"].isna()]
na.head()

,Ingredient Name,cas_number,clean_name,api_rn,api_name,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)"
0,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,8023-85-6,Cedrus Atlantica Oil,8023-85-6,Cedrus Atlantica Oil,NaN,NaN,NaN,NaN,NaN
4,Turpentine gum (Pinus spp.); Turpentine oil an...,9005-90-7,Turpentine,9005-90-7,Turpentine,NaN,NaN,NaN,NaN,NaN
10,CITRONELLOL,NaN,CITRONELLOL,106-22-9,Citronellol,NaN,NaN,NaN,NaN,NaN
13,Limonene (1-methyl-4-prop-1-en-2-yl-cyclohexen...,5989-27-5,Limonene (1-methyl-4-prop-1-en-2-yl-cyclohexen...,5989-27-5,(+)-Limonene,NaN,NaN,NaN,NaN,NaN
15,"Aloe vera, non-decolorized (unfiltered) whole ...",NaN,"Aloe vera, non-decolorized (unfiltered) whole ...",8001-97-6,Aloe vera,NaN,NaN,NaN,NaN,NaN

In [396]:
len(na)

146

In [397]:
len(result) - len(na)

359

In [398]:
result = result.dropna(subset =['Hazard Traits'])
len(result)

359

In [399]:
harms_agg.head()

,api_rn,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)"
0,85-00-7,Hazard Trait Undefined,Diquat dibromide,None,CECBP - Priority Chemicals,FF
1,100-00-5,Carcinogenicity,1-Chloro-4-nitrobenzene,4-Chloronitrobenzene,IARC Carcinogens - 2B; Prop 65,Any
2,100-02-7,Dermatotoxicity; Environmental tox; Other Toxi...,4-Nitrophenol,None,CA TACs; CECBP - Priority Chemicals; CWA 303(c...,FF
3,100-17-4,Carcinogenicity,para-Nitroanisole,None,IARC Carcinogens - 2B; Prop 65,Any
4,100-25-4,Reproductive Toxicity,p-Dinitrobenzene,None,Prop 65,Any

In [400]:
harms_agg.rename(columns={'Chemical Name': 'Ingredient Name'}, inplace=True)

In [401]:
na.head()

,Ingredient Name,cas_number,clean_name,api_rn,api_name,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)"
0,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,8023-85-6,Cedrus Atlantica Oil,8023-85-6,Cedrus Atlantica Oil,NaN,NaN,NaN,NaN,NaN
4,Turpentine gum (Pinus spp.); Turpentine oil an...,9005-90-7,Turpentine,9005-90-7,Turpentine,NaN,NaN,NaN,NaN,NaN
10,CITRONELLOL,NaN,CITRONELLOL,106-22-9,Citronellol,NaN,NaN,NaN,NaN,NaN
13,Limonene (1-methyl-4-prop-1-en-2-yl-cyclohexen...,5989-27-5,Limonene (1-methyl-4-prop-1-en-2-yl-cyclohexen...,5989-27-5,(+)-Limonene,NaN,NaN,NaN,NaN,NaN
15,"Aloe vera, non-decolorized (unfiltered) whole ...",NaN,"Aloe vera, non-decolorized (unfiltered) whole ...",8001-97-6,Aloe vera,NaN,NaN,NaN,NaN,NaN

In [402]:
na.to_csv("na_harms.csv")

In [403]:
na.groupby("Ingredient Name").size().rename("count").reset_index().head()

                                     Ingredient Name  count
0  1,1'-Sulfonylbis[3,5-dibromo-4-(2,3-dibromopro...      1
1  1,3-Dioxane, 2-(2,4-dimethyl-3-cyclohexen-1-yl...      1
2  1-(1,2,3,4,5,6,7,8-octahydro-2,3,8,8-tetrameth...      1
3  1-Methoxy-4-(1E)-1-propen-1-yl-benzene (trans-...      1
4  2,4-Hexadienal (89% trans, trans isomer; 11% c...      1

In [404]:
len(na)

146

In [405]:
na_cleaned = pd.read_csv("data/na_harms_cleaned.csv", encoding='latin-1')

In [406]:
na_cleaned

,Unnamed: 0,Ingredient Name,cas_number,clean_name,api_rn,api_name,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)"
0,0,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,8023-85-6,Cedrus Atlantica Oil,8023-85-6,Cedrus Atlantica Oil,Fragrance Allergen,Cedrus Atlantica Oil/Extract,Cedrus atlanticaÊoil and extract; Cedrus Atlan...,Annex III of the EU Cosmetics Regulation No. 1...,FA
1,4,Turpentine gum (PinusÂ spp.); Turpentine oil a...,9005-90-7,Turpentine,9005-90-7,Turpentine,Fragrance Allergen,Turpentine gum (PinusÊspp.); Turpentine oil an...,Turpentine,Annex III of the EU Cosmetics Regulation No. 1...,FA
2,10,CITRONELLOL,NaN,CITRONELLOL,106-22-9,Citronellol,Fragrance Allergen,"Citronellol /+- 3,7-dimethyloct-6-en-1-ol","CITRONELLOL; (3R)-3,7-dimethyloct-6-en-1-ol; (...",Annex III of the EU Cosmetics Regulation No. 1...,FA
3,13,Limonene (1-methyl-4-prop-1-en-2-yl-cyclohexen...,5989-27-5,Limonene (1-methyl-4-prop-1-en-2-yl-cyclohexen...,5989-27-5,(+)-Limonene,Fragrance Allergen,Limonene,1-methyl-4-prop-1-en-2-yl-cyclohexene; dl-limo...,Annex III of the EU Cosmetics Regulation No. 1...,FA
4,15,"Aloe vera, non-decolorized (unfiltered) whole ...",NaN,"Aloe vera, non-decolorized (unfiltered) whole ...",8001-97-6,Aloe vera,Carcinogenicity,"Aloe vera, non-decolorized whole leaf extract",NaN,IARC Carcinogens - 2B; Prop 65,Any
...,...,...,...,...,...,...,...,...,...,...,...
145,500,Goldenseal root powder,NaN,Goldenseal root powder,NaN,Goldenseal root powder,Carcinogenicity,NaN,NaN,IARC Carcinogens - 2B; Prop 65,Any
146,504,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,92201-55-3,Cedrus Atlantica Oil Extract (Cedrus atlantica...,92201-55-3,"Cedrus atlantica, ext.",Fragrance Allergen,Cedrus Atlantica Oil/Extract,Cedrus atlanticaÊoil and extract; Cedrus Atlan...,Annex III of the EU Cosmetics Regulation No. 1...,NaN
147,508,"Alcoholic beverages, when associated with alco...",64-17-5,Ethyl alcohol in alcoholic beverages (Ethanol ...,64-17-5,Ethanol,Hazard Trait Undefined,NaN,NaN,NaN,NaN
148,512,Myristamide DEA 7545-23-5,7545-23-5,Myristamide DEA,7545-23-5,Myristic acid diethanolamide,Hazard Trait Undefined,NaN,NaN,NaN,NaN
149,516,Turpentine gum (PinusÊspp.); Turpentine oil an...,9005-90-7,Turpentine gum (Pinus spp.); Turpentine oil an...,9005-90-7,Turpentine,Fragrance Allergen,Turpentine gum (PinusÊspp.); Turpentine oil an...,Turpentine,Annex III of the EU Cosmetics Regulation No. 1...,NaN

In [407]:
len(na_cleaned)

150

In [408]:
hazards_merged = pd.concat([result, na_cleaned])

In [409]:
len(hazards_merged)

509

In [410]:
hazards_merged.info()

<class 'pandas.core.frame.DataFrame'>
Index: 509 entries, 1 to 149
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Ingredient Name               508 non-null    object
 1   cas_number                    390 non-null    object
 2   clean_name                    508 non-null    object
 3   api_rn                        497 non-null    object
 4   api_name                      508 non-null    object
 5   Hazard Traits                 509 non-null    object
 6   Chemical Name                 441 non-null    object
 7   Synonyms                      294 non-null    object
 8   Authoritative List            470 non-null    object
 9   When to Report (Any, FF, FA)  467 non-null    object
 10  Unnamed: 0                    150 non-null    float64
dtypes: float64(1), object(10)
memory usage: 47.7+ KB

In [411]:
hazards_merged

,Ingredient Name,cas_number,clean_name,api_rn,api_name,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)",Unnamed: 0
1,"[3R-(3a,3aß,7ß,8aa)]-1-(2,3,4,7,8,8a-hexahydro...",32388-55-9,Acetylcedrene,32388-55-9,Acetylcedrene,Fragrance Allergen,"[3R-(3α,3aβ,7β,8aα)]-1-(2,3,4,7,8,8a-hexahydro...",Acetyl Cedrene,Annex III of the EU Cosmetics Regulation No. 1...,FA,NaN
2,"1-Naphthalenepropanol, a-ethenyldecahydro- 2-h...",515-03-7,Sclareol,515-03-7,Sclareol,Bioaccumulation; Environmental Persistence; Fr...,"1-Naphthalenepropanol, a-ethenyldecahydro- 2-h...",Sclareol; [1R-(1alpha)]-alpha-Ethenyldecahydro...,Annex III of the EU Cosmetics Regulation No. 1...,"FA, FF",NaN
3,Myroxylon Pereirae Oil/Extract (Myroxylon bals...,8007-00-9,Myroxylon Pereirae Oil/Extract,8007-00-9,Myroxylon Pereirae Oil/Extract,Fragrance Allergen,Myroxylon Pereirae Oil/Extract,Myroxylon balsamum var. pereirae; extracts and...,Annex III of the EU Cosmetics Regulation No. 1...,FA,NaN
5,Butane (containing greater than or equal to 0...,106-97-8,Butane,106-97-8,Butane,Carcinogenicity; Genotoxicity,"Butane (containing ≥ 0,1 % butadiene (203-450-8))",None,EC Annex VI CMRs - Cat. 1A; EC Annex VI CMRs -...,FF,NaN
6,Pinus Mugo (Pinus mugo leaf and twig oil and e...,90082-72-7,"Pine, Pinus mugo, ext.",90082-72-7,"Pine, Pinus mugo, ext.",Fragrance Allergen,Pinus Mugo,Pinus mugo leaf and twig oil and extract; Pinu...,Annex III of the EU Cosmetics Regulation No. 1...,FA,NaN
...,...,...,...,...,...,...,...,...,...,...,...
145,Goldenseal root powder,NaN,Goldenseal root powder,NaN,Goldenseal root powder,Carcinogenicity,NaN,NaN,IARC Carcinogens - 2B; Prop 65,Any,500.0
146,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,92201-55-3,Cedrus Atlantica Oil Extract (Cedrus atlantica...,92201-55-3,"Cedrus atlantica, ext.",Fragrance Allergen,Cedrus Atlantica Oil/Extract,Cedrus atlanticaÊoil and extract; Cedrus Atlan...,Annex III of the EU Cosmetics Regulation No. 1...,NaN,504.0
147,"Alcoholic beverages, when associated with alco...",64-17-5,Ethyl alcohol in alcoholic beverages (Ethanol ...,64-17-5,Ethanol,Hazard Trait Undefined,NaN,NaN,NaN,NaN,508.0
148,Myristamide DEA 7545-23-5,7545-23-5,Myristamide DEA,7545-23-5,Myristic acid diethanolamide,Hazard Trait Undefined,NaN,NaN,NaN,NaN,512.0
149,Turpentine gum (PinusÊspp.); Turpentine oil an...,9005-90-7,Turpentine gum (Pinus spp.); Turpentine oil an...,9005-90-7,Turpentine,Fragrance Allergen,Turpentine gum (PinusÊspp.); Turpentine oil an...,Turpentine,Annex III of the EU Cosmetics Regulation No. 1...,NaN,516.0

In [412]:

len(all_data)

534508

In [413]:
all_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 534508 entries, 0 to 534507
Data columns (total 13 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Product Id                 534508 non-null  int64
 1   Company                    534508 non-null  object
 2   Brand                      534308 non-null  object
 3   Product Name               534508 non-null  object
 4   Variant                    187813 non-null  object
 5   Product Discontinued Date  39102 non-null   object
 6   Product Submitted Date     534508 non-null  object
 7   Ingredient Name            534186 non-null  object
 8   Function                   433384 non-null  object
 9   Unit of Measure            222747 non-null  object
 10  Concentration              224495 non-null  object
 11  Ingredient Submitted Date  534186 non-null  object
 12  Ingredient Removed Date    6627 non-null    object
dtypes: int64(1), object(12)
memory usage: 53.0+ MB

In [414]:
all_data.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,Concentration,Ingredient Submitted Date,Ingredient Removed Date
0,18358,Nail Alliance - Entity,Entity Nudite,Cool Pink Nail Sculpting Powder,NaN,NaN,6/24/2019,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,5.000000,6/24/2019,NaN
1,38661,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,40.000000,9/21/2015,NaN
2,38662,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Sprinkle,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,31.000000,9/21/2015,NaN
3,38667,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,12.000000,9/21/2015,NaN
4,38665,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,21.500000,9/21/2015,NaN

In [415]:
final_merge = all_data.merge(hazards_merged, on = "Ingredient Name", how = 'left')

In [416]:
final_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 534514 entries, 0 to 534513
Data columns (total 23 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Product Id                    534514 non-null  int64
 1   Company                       534514 non-null  object
 2   Brand                         534314 non-null  object
 3   Product Name                  534514 non-null  object
 4   Variant                       187814 non-null  object
 5   Product Discontinued Date     39104 non-null   object
 6   Product Submitted Date        534514 non-null  object
 7   Ingredient Name               534192 non-null  object
 8   Function                      433390 non-null  object
 9   Unit of Measure               222748 non-null  object
 10  Concentration                 224496 non-null  object
 11  Ingredient Submitted Date     534192 non-null  object
 12  Ingredient Removed Date       6627 non-null    object
 13  cas_number                    447311 non-null  object
 14  clean_name                    533878 non-null  object
 15  api_rn                        532242 non-null  object
 16  api_name                      533878 non-null  object
 17  Hazard Traits                 534200 non-null  object
 18  Chemical Name                 527158 non-null  object
 19  Synonyms                      454215 non-null  object
 20  Authoritative List            530637 non-null  object
 21  When to Report (Any, FF, FA)  529833 non-null  object
 22  Unnamed: 0                    157739 non-null  float64
dtypes: float64(1), int64(1), object(21)
memory usage: 93.8+ MB

In [417]:
na_final =final_merge[final_merge["Hazard Traits"].isna()]
len(na_final)

314

In [418]:
final_merge.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,...,cas_number,clean_name,api_rn,api_name,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)",Unnamed: 0
0,18358,Nail Alliance - Entity,Entity Nudite,Cool Pink Nail Sculpting Powder,NaN,NaN,6/24/2019,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN
1,38661,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN
2,38662,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Sprinkle,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN
3,38667,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN
4,38665,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN

In [419]:
na_final.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,...,cas_number,clean_name,api_rn,api_name,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)",Unnamed: 0
896,115795,Davines S.p.A.,[comfort zone],[comfort zone] - AROMASOUL INDIAN blend,NaN,NaN,9/8/2022,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,Fragrance,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1217,135693,Davines S.p.A.,[comfort zone],[comfort zone] - TRANQUILLITYTM eau de toilette,NaN,NaN,5/30/2024,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,Fragrance,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1381,170568,Davines S.p.A.,[comfort zone],[comfort zone] – TRANQUILLITYTM magnesium body...,NaN,NaN,11/27/2025,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,Fragrance,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1432,151733,"ONEOSEVEN Co., Ltd.",107,SCALP PURIFYING Microbiome Shampoo,NaN,NaN,3/16/2025,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,Fragrance,Percent,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2552,171817,"Fourcompany Co.,Ltd.",Abib,Abib Airy clear Sunscreen gel Smoothing tube,NaN,NaN,12/18/2025,Cedrus Atlantica Oil/Extract (Cedrus atlantica...,Conditioning/Emollient,Percent,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [434]:
harm_updates = {
    'Cedrus Atlantica Oil/Extract (Cedrus atlantica\xa0oil and extract; Cedrus Atlantica Bark Extract; Cedrus Atlantica Bark Oil; Cedrus Atlantica Bark Water; Cedrus Atlantica Leaf Extract; Cedrus Atlantica Wood Extract; Cedrus Atlantica Wood Oil) 92201-55-3 / 8023-85-6': 'Fragrance Allergen',
    'Alcoholic beverages, when associated with alcohol abuse': 'Hazard Trait Undefined',
    'Myristamide DEA 7545-23-5 ': 'Hazard Trait Undefined',
    'Turpentine gum (Pinus\xa0spp.); Turpentine oil and rectified oil; Turpentine, steam distilled (Pinus\xa0spp.) (Turpentine) 9005-90-7 / 8006-64-2 / 8052-14-0': 'Hazard Trait Undefined',
}

for ingredient, hazard in harm_updates.items():
    final_merge.loc[final_merge['Ingredient Name'].str.contains(ingredient, na=False, regex = False), 'Hazard Traits'] = hazard

In [435]:
final_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 534514 entries, 0 to 534513
Data columns (total 23 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Product Id                    534514 non-null  int64
 1   Company                       534514 non-null  object
 2   Brand                         534314 non-null  object
 3   Product Name                  534514 non-null  object
 4   Variant                       187814 non-null  object
 5   Product Discontinued Date     39104 non-null   object
 6   Product Submitted Date        534514 non-null  object
 7   Ingredient Name               534192 non-null  object
 8   Function                      433390 non-null  object
 9   Unit of Measure               222748 non-null  object
 10  Concentration                 224496 non-null  object
 11  Ingredient Submitted Date     534192 non-null  object
 12  Ingredient Removed Date       6627 non-null    object
 13  cas_number                    447311 non-null  object
 14  clean_name                    533878 non-null  object
 15  api_rn                        532242 non-null  object
 16  api_name                      533878 non-null  object
 17  Hazard Traits                 534514 non-null  object
 18  Chemical Name                 527158 non-null  object
 19  Synonyms                      454215 non-null  object
 20  Authoritative List            530637 non-null  object
 21  When to Report (Any, FF, FA)  529833 non-null  object
 22  Unnamed: 0                    157739 non-null  float64
dtypes: float64(1), int64(1), object(21)
memory usage: 93.8+ MB

In [438]:
final_merge.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,...,cas_number,clean_name,api_rn,api_name,Hazard Traits,Chemical Name,Synonyms,Authoritative List,"When to Report (Any, FF, FA)",Unnamed: 0
0,18358,Nail Alliance - Entity,Entity Nudite,Cool Pink Nail Sculpting Powder,NaN,NaN,6/24/2019,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN
1,38661,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN
2,38662,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Sprinkle,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN
3,38667,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN
4,38665,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,...,13463-67-7,Titanium dioxide (CI 77891),13463-67-7,Titania,Carcinogenicity,"Titanium dioxide (airborne, unbound particles ...",CI 77891,IARC Carcinogens - 2B; Prop 65,Any,NaN

In [437]:
final_merge.to_csv("final_hazard_merge_2_19.csv")