In [1]:
import pandas as pd

In [2]:
# download data and put in the data/ folder. Then change below to data/cdph_data.csv
source_data = "data/CDPH Search results - 1_12_2026, 3_34_15 PM.csv"
cdph = pd.read_csv(source_data, low_memory = False)
# ORIGINAL cdph = pd.read_csv("cdph_data.csv", low_memory = False)
cdph.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,Concentration,Ingredient Submitted Date,Ingredient Removed Date
0,18358,Nail Alliance - Entity,Entity Nudite,Cool Pink Nail Sculpting Powder,NaN,NaN,6/24/2019,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,5.000000,6/24/2019,NaN
1,38661,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,40.000000,9/21/2015,NaN
2,38662,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Sprinkle,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,31.000000,9/21/2015,NaN
3,38667,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,12.000000,9/21/2015,NaN
4,38665,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,21.500000,9/21/2015,NaN

In [3]:
cdph.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 534508 entries, 0 to 534507
Data columns (total 13 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Product Id                 534508 non-null  int64
 1   Company                    534508 non-null  object
 2   Brand                      534308 non-null  object
 3   Product Name               534508 non-null  object
 4   Variant                    187813 non-null  object
 5   Product Discontinued Date  39102 non-null   object
 6   Product Submitted Date     534508 non-null  object
 7   Ingredient Name            534186 non-null  object
 8   Function                   433384 non-null  object
 9   Unit of Measure            222747 non-null  object
 10  Concentration              224495 non-null  object
 11  Ingredient Submitted Date  534186 non-null  object
 12  Ingredient Removed Date    6627 non-null    object
dtypes: int64(1), object(12)
memory usage: 53.0+ MB

In [4]:
cdph["discontinued_year"] = pd.to_datetime(cdph["Product Discontinued Date"]).dt.year
cdph["product_submitted_year"] = pd.to_datetime(cdph["Product Submitted Date"]).dt.year
cdph["ingredient_submitted_date"] = pd.to_datetime(cdph["Ingredient Submitted Date"]).dt.year
cdph["ingredient_removed_year"] = pd.to_datetime(cdph["Ingredient Removed Date"]).dt.year

In [5]:
cdph["discontinued_year"] = cdph["discontinued_year"].astype("Int64")
cdph["product_submitted_year"] = cdph["product_submitted_year"].astype("Int64")
cdph["ingredient_submitted_date"] = cdph["ingredient_submitted_date"].astype("Int64")
cdph["ingredient_removed_year"] = cdph["ingredient_removed_year"].astype("Int64")

In [6]:
cdph.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,Concentration,Ingredient Submitted Date,Ingredient Removed Date,discontinued_year,product_submitted_year,ingredient_submitted_date,ingredient_removed_year
0,18358,Nail Alliance - Entity,Entity Nudite,Cool Pink Nail Sculpting Powder,NaN,NaN,6/24/2019,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,5.000000,6/24/2019,NaN,<NA>,2019,2019,<NA>
1,38661,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,40.000000,9/21/2015,NaN,<NA>,2015,2015,<NA>
2,38662,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Sprinkle,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,31.000000,9/21/2015,NaN,<NA>,2015,2015,<NA>
3,38667,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,12.000000,9/21/2015,NaN,<NA>,2015,2015,<NA>
4,38665,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,21.500000,9/21/2015,NaN,<NA>,2015,2015,<NA>

In [7]:
submissions = cdph.groupby("product_submitted_year").size().rename("product_count").reset_index()
submissions

    product_submitted_year  product_count
0                     2009          28251
1                     2010          13522
2                     2011           4191
3                     2012           3317
4                     2013           5787
5                     2014           7647
6                     2015           6825
7                     2016           4008
8                     2017           7256
9                     2018           9387
10                    2019          13123
11                    2020           3543
12                    2021          17232
13                    2022         105184
14                    2023          58541
15                    2024          89591
16                    2025         155075
17                    2026           2028

In [8]:
discontinued = cdph.groupby("discontinued_year").size().rename("product_count").reset_index()
discontinued

    discontinued_year  product_count
0                2001              2
1                2004             21
2                2005              6
3                2006             16
4                2007            222
5                2008            366
6                2009            742
7                2010           1064
8                2011           1241
9                2012            975
10               2013           3886
11               2014           2283
12               2015           1783
13               2016           2138
14               2017           1014
15               2018            752
16               2019            724
17               2020            676
18               2021           1683
19               2022           3884
20               2023           5689
21               2024           4029
22               2025           5903
23               2027              3

In [9]:
total_products = discontinued["product_count"].sum()
print(total_products)

39102

In [10]:
import altair as alt

# Discontinued Products by Year

In [11]:
alt.Chart(discontinued).mark_bar().encode(
    x="discontinued_year",
    y="product_count"
)

alt.Chart(...)

# Submitted Products by Year

In [12]:
alt.Chart(submissions).mark_bar().encode(
    x="product_submitted_year",
    y="product_count"
)

alt.Chart(...)

In [13]:
product_types = cdph.groupby("Product Category").size().rename("product_count").reset_index().sort_values("product_count", ascending=False)

KeyError: 'Product Category'

In [ ]:
pd.set_option('display.max_rows', None)
product_types.sort_values("product_count", ascending = False)
product_types

                                     Product Category  product_count
25                              Foundations and Bases         237005
68                            Perfumes/Eaux de Parfum         231647
79        Skin Moisturizers (making a cosmetic claim)          79633
87                      Toilet Water/Eaux de Toilette          74532
11                              Body Washes and Soaps          65144
63                            Other Skin Care Product          48725
41         Lip Color - Lipsticks, Liners, and Pencils          40441
33           Hair Shampoos (making a cosmetic claim)           38935
29                      Hair Conditioners (rinse-out)          32932
55                                   Other Fragrances          30501
66                        Perfumes - Oils and Lotions          29005
38                      Hand Cleansers and Sanitizers          26583
36                              Hair Styling Products          26224
18                                         Eye Shadow          24872
77                                     Skin Cleansers          24233
61                       Other Personal Care Product           23916
13                                            Cologne          21635
21                                       Facial Cream          21617
42                                    Lip Gloss/Shine          19883
56                            Other Hair Care Product          19673
30                               Hair Dyes and Colors          18376
89                                Underarm Deodorants          16996
50                             Nail Polish and Enamel          14951
28                       Hair Conditioners (leave-in)          14412
39                            Indoor Tanning Products          12443
20                                       Face Powders          12370
40                 Lip Balm (making a cosmetic claim)          11783
2   Anti-Wrinkle/Anti-Aging Products (making a cos...          10112
19                           Eyeliner/Eyebrow Pencils           9127
10                                           Blushes            8994
82               Sunscreen (making a cosmetic claim)            8450
22                                       Facial Masks           8058
73                              Scrubs and Exfoliants           7467
12                      Bubble and Foam Bath Products           7145
58                               Other Makeup Product           6441
81                      Sprays (excluding fragrances)           6439
54                                Other Bath Products           5340
1                                 Aftershave Products           4939
3           Antiperspirants (making a cosmetic claim)           4910
9                                      Bath Additives           4272
52                                Nighttime Skin Care           4099
84                       Tattoos and Permanent Makeup           3746
74            Shaving Cream and other Beard Softeners           3529
80               Skin Toner (making a cosmetic claim)           3350
88                                 UV Gel Nail Polish           3313
46                           Mascara/Eyelash Products           3046
17                                            Douches           2760
67                      Perfumes - Solids and Powders           2682
85                            Teeth Cleaning Products           2485
4               Artificial Nails and Related Products           2400
48                            Nail Creams and Lotions           2370
62                              Other Shaving Product           2125
64                          Other Sun-Related Product           1564
34        Hair Shampoos with Anti-Dandruff properties           1527
7                                      Baby Wash/Soap           1429
6                                      Baby Skin Care           1382
37                   Hair Tints and Rinses (coloring)           1259
5                                       Baby Shampoos           1241
71                  Products Related to Hair Coloring           1189
32                         Hair Rinses (non-coloring)           1150
78                                    Skin Fresheners           1118
45                                Makeup Preparations           1102
83                                   Suntan Enhancers           1047
65                         Paints (e.g. facial, body)           1001
72                                             Rouges            946
0             Acne Products (making a cosmetic claim)            925
86                           Teeth Whitening Products            889
35                                 Hair Straighteners            883
44                                   Makeup Fixatives            878
53                                Other Baby Products            838
70  Powders (excluding aftershave, baby powder, an...            775
49                                    Nail Decoration            750
57                        Other Hair Coloring Product            698
23                                Feminine Deodorants            618
76          Skin Bleaching (making a cosmetic claim)             587
27                        Hair Color Sprays (aerosol)            547
47                  Mouthwashes and Breath Fresheners            530
43   Lubricants  (e.g. personal, sexual, massage oil)            519
59                               Other Nail Products             502
51                    Nail Polish and Enamel Removers            484
15                                       Depilatories            381
24                            Foot Powders and Sprays            363
14                                  Cuticle Softeners            258
8                            Basecoats and Undercoats            223
26                                      Hair Bleaches            218
31                         Hair Lighteners with Color            120
69                      Permanent Waves and Wave Sets            107
60                         Other Oral Hygiene Product             75
75          Skin Astringent (making a cosmetic claim)             66
16                              Diaper Rash Treatment             12

In [ ]:
thisyear=cdph[cdph["discontinued_year"] == 2025]
thisyear.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,...,Ingredient Removed Date,UPC,Body Area,Product Category,Product Form,Intended Market,discontinued_year,product_submitted_year,ingredient_submitted_date,ingredient_removed_year
890,119884,Davines S.p.A.,[comfort zone],/ SKIN REGIMEN / cleansing cream,NaN,10/15/2025,12/30/2022,Limonene (1-methyl-4-prop-1-en-2-yl-cyclohexen...,Fragrance,NaN,...,NaN,8004608516866,Face,Skin Cleansers,Cream/Gel/Foam,General population,2025,2022,2023,<NA>
891,119884,Davines S.p.A.,[comfort zone],/ SKIN REGIMEN / cleansing cream,NaN,10/15/2025,12/30/2022,Diethyl phthalate (DEP) 84-66-2,Fragrance,NaN,...,NaN,8004608516866,Face,Skin Cleansers,Cream/Gel/Foam,General population,2025,2022,2022,<NA>
892,119884,Davines S.p.A.,[comfort zone],/ SKIN REGIMEN / cleansing cream,NaN,10/15/2025,12/30/2022,LINALOOL,Fragrance,NaN,...,NaN,8004608516866,Face,Skin Cleansers,Cream/Gel/Foam,General population,2025,2022,2023,<NA>
895,130717,Davines S.p.A.,[comfort zone],/ SKIN REGIMEN / hand cream,NaN,10/15/2025,10/24/2023,Limonene (1-methyl-4-prop-1-en-2-yl-cyclohexen...,Fragrance,NaN,...,NaN,8004608500056,Hands,Other Skin Care Product,Cream/Gel/Foam,General population,2025,2023,2023,<NA>
896,130717,Davines S.p.A.,[comfort zone],/ SKIN REGIMEN / hand cream,NaN,10/15/2025,10/24/2023,LINALOOL,Fragrance,NaN,...,NaN,8004608500056,Hands,Other Skin Care Product,Cream/Gel/Foam,General population,2025,2023,2023,<NA>

need to calculate length of time from product submitted date to product discontinued date

In [ ]:
thisyear.groupby("Product Category").size().rename("product_count").reset_index().sort_values("product_count", ascending = False)

                                     Product Category  product_count
40                            Other Skin Care Product           2658
52        Skin Moisturizers (making a cosmetic claim)           2165
58                      Toilet Water/Eaux de Toilette           1894
5                               Body Washes and Soaps           1680
45                            Perfumes/Eaux de Parfum           1259
12                                       Facial Cream            894
34                                   Other Fragrances            526
26         Lip Color - Lipsticks, Liners, and Pencils            346
35                            Other Hair Care Product            343
48                              Scrubs and Exfoliants            318
36                               Other Makeup Product            285
15                              Foundations and Bases            222
39                              Other Shaving Product            219
25                 Lip Balm (making a cosmetic claim)            219
6                       Bubble and Foam Bath Products            211
50                                     Skin Cleansers            210
13                                       Facial Masks            201
18                      Hair Conditioners (rinse-out)            189
27                                    Lip Gloss/Shine            185
20           Hair Shampoos (making a cosmetic claim)             185
31                             Nail Polish and Enamel            166
33                                Other Bath Products            160
9                                          Eye Shadow            153
38                       Other Personal Care Product             148
43                        Perfumes - Oils and Lotions            137
2   Anti-Wrinkle/Anti-Aging Products (making a cos...            111
46  Powders (excluding aftershave, baby powder, an...            108
4                                            Blushes              88
53               Skin Toner (making a cosmetic claim)             71
7                                             Cologne             64
32                                Nighttime Skin Care             61
41                          Other Sun-Related Product             55
23                              Hair Styling Products             52
10                           Eyeliner/Eyebrow Pencils             51
3                                      Bath Additives             44
1                                 Aftershave Products             39
49            Shaving Cream and other Beard Softeners             37
11                                       Face Powders             34
44                      Perfumes - Solids and Powders             30
30                            Nail Creams and Lotions             30
60                                Underarm Deodorants             26
17                       Hair Conditioners (leave-in)             21
16                        Hair Color Sprays (aerosol)             20
59                                 UV Gel Nail Polish             19
29                  Mouthwashes and Breath Fresheners             18
19                               Hair Dyes and Colors             16
47                                             Rouges             16
14                            Foot Powders and Sprays             16
55               Sunscreen (making a cosmetic claim)              15
54                      Sprays (excluding fragrances)             12
21        Hair Shampoos with Anti-Dandruff properties             11
24                      Hand Cleansers and Sanitizers             10
8                                   Cuticle Softeners             10
56                                   Suntan Enhancers              9
28                           Mascara/Eyelash Products              8
51                                    Skin Fresheners              7
57                            Teeth Cleaning Products              6
42                         Paints (e.g. facial, body)              3
0             Acne Products (making a cosmetic claim)              2
22                                 Hair Straighteners              2
37                               Other Nail Products               1

In [ ]:
thisyear.groupby("Brand").size().rename("product_count").reset_index().sort_values("product_count", ascending = False)

                                              Brand  product_count
85              The Body Shop International Limited           9259
84                                    The Body Shop           1596
41                          Lush Handmade Cosmetics            788
24                                        Gold Bond            639
57                             Neal's Yard Remedies            526
73                                     SERGE LUTENS            407
5                                      BEAUTY RENEW            263
22                                             Glee            185
32                    ISSEY MIYAKE - FUSION D'ISSEY            162
64                             PB Premiere Editions            148
52            NARCISO RODRIGUEZ - MUSC NOIR FOR HER            143
30                    ISSEY MIYAKE - A DROP D'ISSEY            123
9                                   CASHMERE SECRET            119
16                                      Dr. Squatch            105
33                     ISSEY MIYAKE - L'EAU D'ISSEY            100
91                                            Venus             87
10                                    CELIA DE LUXE             82
34          ISSEY MIYAKE - L'EAU D'ISSEY POUR HOMME             70
83                                       Texture ID             66
82                                       Suntegrity             64
15                                  Doctor Eckstein             64
60                                    OPI Gel Color             62
8                                     CASHMERE CARE             60
68                                          Proraso             56
35                                       Jack Black             45
81                                     Summer's Eve             44
18                              European Wax Center             43
78                                     SensatioNail             42
31                    ISSEY MIYAKE - A DROP D´ISSEY             40
61             OPI Infinite Shine Long-Wear Lacquer             39
66                                          PERLIER             37
62                                 OPI Nail Lacquer             35
71                                        RATIONALE             32
75                                 SUSANNE KAUFMANN             25
2                                               Act             24
79                                         Softsoap             23
90                                          Trilogy             23
4                                  Andalou Naturals             23
72                                          RED PRO             20
45                                           MAELYS             19
94                                   [comfort zone]             18
38                                             LILY             18
26          HAIR COMPANY PROFESSIONAL DOUBLE ACTION             16
1                                            AVEENO             15
77                                      Selsun Blue             15
59                                         Nutrafol             15
14                                              DHC             15
54                      NARCISO RODRIGUEZ - NARCISO             14
11                                           CHANEL             14
46                                            MONAT             13
13                        Clairol Natural Instincts             13
21                                         Gillette             13
50                           Merle Norman Cosmetics             12
93                                             YUNI             12
87                                      Three Ships             12
47                                        Manscaped             12
0                                           AG Care             11
53            NARCISO RODRIGUEZ - MUSC NUDE FOR HER             11
69                                            Prose             11
86                                The White Company             11
3                                             Acure             10
74                                    SERGE LUTENS               9
63                            OPI Powder Perfection              7
95                                            got2b              6
58                          News Anchor Thick Hair               6
7                                          CARROTEN              6
27       HAIR COMPANY PROFESSIONAL INIMITABLE STYLE              6
39                                        LUBRIDERM              6
76                                          Sahajan              5
29                               INSTITUT ESTHEDERM              5
65                                         PCA SKIN              5
37                                  Kate Somerville              5
6                                        Beauty Pie              4
80                                       StriVectin              4
49                                     Merle Norman              4
70                                          Queen V              4
89                                     Trader Joe's              3
56                                  Nature's Answer              3
36                            John Masters Naturals              3
51                                   Mineral Fusion              3
67                               Physicians Formula              3
92                             Wella Professionals               3
40                                             Lush              3
88                               Thrive Causemetics              3
42                                         Lush Ltd              2
43                           Lush Manufacturing Ltd              2
25  Gold Bond Ultimate Men's Essentials Body Powder              2
12                                          Cezanne              2
17                                          Eucerin              1
23                                         Glossier              1
19                                          Fing'rs              1
20                               Function of Beauty              1
55                                       NEUTROGENA              1
28                                             ING               1
44                          Lush Manufacturing Ltd.              1
48                                       Maybelline              1