In [1]:
import pandas as pd

In [25]:
# download data and put in the data/ folder. Then change below to data/cdph_data.csv
source_data = "data/CDPH Search results - 1_12_2026, 3_34_15 PM.csv"
cdph = pd.read_csv(source_data, low_memory = False)
# ORIGINAL cdph = pd.read_csv("cdph_data.csv", low_memory = False)
len(cdph)

534508

In [18]:
len(cdph[cdph["Brand"] == "Glossier"])

636

In [14]:
cdph["Ingredient Name"].unique()

array(['Titanium dioxide (CI 77891) 13463-67-7 / 1317-70-0 / 1317-80-2 / 98084-96-9',
       'CITRONELLOL ', 'LINALOOL ', 'HEXYL CINNAMAL ',
       'Limonene (1-methyl-4-prop-1-en-2-yl-cyclohexene; dl-limonene (racemic); Dipentene; (R)-p-mentha-1,8-diene; (d-limonene); (S)-p-mentha-1,8-diene; (l-limonene)) 5989-27-5 / 138-86-3 / 7705-14-8 / 5989-54-8',
       'Lilial ',
       'Aloe vera, non-decolorized (unfiltered) whole leaf extract ',
       '1,6-Octadien-3-ol, 3,7-dimethyl- (LINALOOL) 78-70-6', 'CITRAL ',
       'GERANIOL ',
       'Citronellol /+- 3,7-dimethyloct-6-en-1-ol (CITRONELLOL; (3R)-3,7-dimethyloct-6-en-1-ol; (3S)-3,7-dimethyloct-6-en-1-ol) 106-22-9 / 26489-01-0 / 1117-61-9 / 7540-51-4',
       'Benzyl benzoate 120-51-4', 'BUTYLPHENYL METHYLPROPIONAL ',
       '2-Benzylideneoctanal (HEXYL CINNAMAL) 101-86-0',
       '2-Phenoxyethyl isobutyrate 103-60-6',
       '1,3,4,6,7,8-Hexahydro-4,6,6,7,8,8-hexamethylcyclopenta-?-2-benzopyran (Hexamethylindanopyran) 1222-05-5',
       'Isoeugenol (Phenol, 2-methoxy-4-(1-propenyl); (E)-2-methoxy-4-(prop-1-enyl)phenol; (trans-Isoeugenol); (Z)-2-methoxy-4-(prop-1-enyl)phenol; (cis-Isoeugenol)) 5932-68-3 / 97-54-1 / 5912-86-7',
       'ALPHA-ISOMETHYL IONONE ',
       '2-(4-tert-Butylbenzyl)propionaldehyde (Lilial; BUTYLPHENYL METHYLPROPIONAL) 80-54-6',
       'Methyl 2-Octynoate (Methyl Oct-2-ynoate; Methyl heptine carbonate) 111-12-6',
       'Cyclopentasiloxane ', 'Cyclohexasiloxane ',
       '2,6-Octadien-1-ol, 3,7-dimethyl-, (2E)- (GERANIOL) 106-24-1',
       'Citral (3,7-Dimethyl-2,6-octadienal; (E)-3,7-dimethylocta-2,6-dienal; (Z)-3,7-dimethylocta-2,6-dienal; Geranial; Neral) 5392-40-5 / 141-27-5 / 106-26-3',
       'Benzyl alcohol 100-51-6',
       '2H-1-Benzopyran-2-one (COUMARIN) 91-64-5',
       'Benzyl salicylate 118-58-1',
       'Hydroxycitronellal (7-Hydroxycitronellal) 107-75-5',
       '2,6,10-Dodecatrien-1-ol, 3,7,11-trimethyl- (FARNESOL) 4602-84-0',
       '2-methyl-5-(prop-1-en-2-yl)cyclohex-2-en-1-one; (5R)-2-Methyl-5-prop-1-en-2-ylcyclohex-2-en-1-one;(5S)-2-Methyl-5-prop-1-en-2-ylcyclohex-2-en-1-one (Carvone) 99-49-0 / 6485-40-1 / 2244-16-8',
       'Rose Ketones (1-(2,6,6-trimethyl-2-cyclohexen-1-yl)-2-buten-1-one; 1-(2,6,6-Trimethylcyclohexa-1,3-dien-1-yl)-2-buten-1-one; 1-(2,6,6-Trimethyl-3-cyclohexen-1-yl)-2-buten-1-one; (Z)-1-(2,6,6-trimethyl-1-cyclohexen-1-yl)-2-buten-1-one; (E)-1-(2,6,6-Trimethyl-1-cyclohexen-1-yl)-2-buten-1-one; Alpha-Damascone; cis-Rose ketone 1; trans-Rose ketone 1; Rose ketone 4 (Damascone); Rose ketone 3 (delta-Damascone); trans-Rose ketone 3; cis-Rose ketone 2 (cis-beta-Damascone); trans-Rose ketone 2 (trans-beta-Damascone)) 43052-87-5 / 23726-94-5 / 24720-09-0 / 23696-85-7 / 57378-68-4 / 71048-82-3 / 23726-92-3 / 23726-91-2',
       '2-Propenal, 3-phenyl- (CINNAMAL) 104-55-2',
       'Bornan-2-one; 1,7,7-Trimethylbi-cyclo[2.2.1]-2-heptanone (Camphor) 76-22-2 / 21368-68-3 / 464-49-3 / 464-48-2',
       'Phenol, 2-methoxy-4-(2-propenyl)- (EUGENOL) 97-53-0',
       '3-Methyl-4-(2,6,6-trimethyl-2-cyclohexen-1-yl)-3-buten-2-one (ALPHA-ISOMETHYL IONONE; Methyl ionones) 127-51-5',
       'Cinnamyl alcohol 104-54-1',
       '1-(1,2,3,4,5,6,7,8-octahydro-2,3,8,8-tetramethyl-2-naphthyl)ethan-1-one; 1-(1,2,3,4,5,6,7,8-octahydro-2,3,5,5-tetramethyl-2-naphthyl)ethan-1-one; 1-(1,2,3,5,6,7,8,8a-octahydro-2,3,8,8-tetramethyl-2-naphthyl)ethan-1-one; 1-(1,2,3,4,6,7,8,8a-octahydro-2,3,8,8-tetramethyl-2-naphthyl)ethan-1-one (Tetramethyl acetyloctahydronaphthalenes) 54464-57-2 / 54464-59-4 / 68155-66-8 / 68155-67-9',
       'Bumetrizole (UV-326) 3896-11-5',
       '3,7-Dimethyl octa-1,6-diene-3-yl acetate (Linalyl Acetate) 115-95-7',
       'Diethyl hexyl adipate 103-23-1',
       'beta-Myrcene (Myrcene) 123-35-3',
       'Mentha spicata oil (spearmint oil) (Mentha Viridis Leaf Oil; Mentha Spicata Flower/Leaf/Stem Oil; Mentha Spicata Leaf/Stem Oil; Mentha Viridis (Spearmint) Leaf Oil) 8008-79-5 / 84696-51-5',
       'Methyleugenol (Methyl eugenol) 93-15-2', 'Estragole 140-67-0',
       'Eucalyptus Globulus Oil (Eucalyptus Globulus Leaf Oil; Eucalyptus Globulus Leaf/Twig Oil; Eucalyptus Oil) 97926-40-4 / 8000-48-4',
       'Pentyl-2-hydroxy-benzoate (Amyl Salicylate) 2050-08-0',
       'Menthol (dl-menthol; l-menthol; d-menthol) 89-78-1 / 1490-04-6 / 2216-51-5 / 15356-60-2',
       'Mentha piperita oil (Mentha Piperita (Peppermint) Oil) 8006-90-4 / 84082-70-2',
       'Juniperus Virginiana Oil (Juniperus Virginiana Wood Oil) 8000-27-9 / 85085-41-2',
       '4-Hydroxy-3-methoxybenz-aldehyde (Vanillin) 121-33-5',
       '2-Benzylideneheptanal (AMYL CINNAMAL) 122-40-7',
       'Carbon black 1333-86-4', 'Ethanol in alcoholic beverages 64-17-5',
       'Silica, crystalline (airborne particles of respirable size) (Quartz; Quartz powder) 14464-46-1 / 14808-60-7 / 15468-32-3 / 7631-86-9',
       'Diethyl phthalate (DEP) 84-66-2', 'EUGENOL ', 'COUMARIN ',
       'Acetophenone 98-86-2',
       '2-Propenoic acid, 3-phenyl-, phenylmethyl ester (BENZYL CINNAMATE) 103-41-3',
       '4-Methoxybenzyl alcohol (ANISE ALCOHOL) 105-13-5',
       'Lavandula Oil/Extract (Lavandula hybrida oil/extract; Lavandula intermedia oil/extract; Lavandula angustifolia oil/extract; Lavandula Hybrida Oil; Lavandula Hybrida Extract; Lavandula Hybrida Flower Extract; Lavandula Intermedia Flower/Leaf/Stem Extract; Lavandula Intermedia Flower/Leaf/Stem Oil; Lavandula Intermedia Oil; Lavandula Angustifolia Oil; Lavandula Angustifolia Flower/Leaf/Stem Extract; Lavandula Angustifolia (Lavender) Flower Extract; Lavandula Angustifolia (Lavender) Flower Oil; Lavandula Angustifolia (Lavender) Flower/Leaf/Stem Extract; Lavandula Angustifolia (Lavender) Flower/Leaf/Stem Juice; Lavandula Angustifolia (Lavender) Flower/Leaf/Stem Oil; Lavandula Angustifolia (Lavender) Oil) 91722-69-9 / 8022-15-9 / 93455-96-0 / 93455-97-1 / 92623-76-2 / 84776-65-8 / 8000-28-0 / 90063-37-9',
       'p-Mentha-1,3-diene (Alpha-Terpinene) 99-86-5',
       'Citrus aurantium bergamia oil (Bergamot oil) (Citrus Aurantium Bergamia Peel Oil) 8007-75-8 / 89957-91-5 / 68648-33-9 / 85049-52-1',
       'Pogostemon cablin oil 8014-09-3 / 84238-39-1',
       '(1R,4E,9S)-4,11,11-Trimethyl-8-methylenebicyclo[7.2.0]undec-4-ene (Beta-Caryophyllene) 87-44-5',
       'p-Mentha-1,4(8)-diene (Terpinolene) 586-62-9',
       '2,6-Octadien-1-ol, 3,7-dimethyl-,1-acetate, (2E)- (Geranyl Acetate) 105-87-3',
       '2-(4-methylcyclohex-3-en-1-yl)propan-2-ol; p-Menth-1-en-8-ol (alpha-Terpineol); 1-methyl-4-(1-methylvinyl)cyclohexan-1-ol (beta-Terpineol); 1-methyl-4-(1-methylethylidene)cyclohexan-1-ol (gamma-Terpineol) (Terpineol) 8000-41-7 / 98-55-5 / 138-87-4 / 586-81-2',
       'Cedrus Atlantica Oil/Extract (Cedrus atlantica\xa0oil and extract; Cedrus Atlantica Bark Extract; Cedrus Atlantica Bark Oil; Cedrus Atlantica Bark Water; Cedrus Atlantica Leaf Extract; Cedrus Atlantica Wood Extract; Cedrus Atlantica Wood Oil) 92201-55-3 / 8023-85-6',
       'Pinene (2,6,6-Trimethylbi-cyclo[3.1.1]hept-2-ene (alpha-Pinene); 6,6-Dimethyl- 2-methylenebicyclo[3.1.1]heptane (beta-Pinene)) 80-56-8 / 7785-70-8 / 127-91-3 / 18172-67-3',
       '2-Methyl-1-phenyl-2-propyl acetate; Dimethylbenzyl Carbinyl Acetate (Dimethyl Phenethyl Acetate) 151-05-3',
       '1-Methoxy-4-(1E)-1-propen-1-yl-benzene (trans-Anethole) (Anethole) 104-46-1 / 4180-23-8',
       '2-Methoxy-4-prop-1-enylphenyl acetate (Isoeugenyl Acetate) 93-29-8',
       'Citrus Aurantium Peel Oil (Citrus Aurantium Amara Peel Oil; Citrus Aurantium Dulcis Peel Oil; Citrus Sinensis Peel Oil; Citrus Aurantium Amara (Bitter Orange) Peel Oil; Citrus Aurantium Dulcis (Orange) Peel Oil; Citrus Sinensis (Orange) Peel Oil) 68916-04-1 / 72968-50-4 / 97766-30-8 / 8028-48-6 / 8008-57-9',
       'Santalum album oil (Santalum Album (Sandalwood) Oil) 8006-87-9 / 84787-70-2',
       'Oxacyclohepta-decan-2-one (Hexadecanolactone) 109-29-5',
       'Pelargonium graveolens oil (Pelargonium Graveolens Flower Oil; Pelargonium Graveolens Leaf Oil) 90082-51-2 / 8000-46-2',
       'Rose Flower Oil/Extract (Rosa damascena flower oil/extract; Rosa alba flower oil/extract; Rosa canina flower oil; Rosa centifolia oil/extract; Rosa gallica flower oil; Rosa moschata flower oil; Rosa rugosa flower oil; Rosa Damascena Flower Oil; Rosa Damascena Flower Extract; Rosa Alba Flower Oil; Rosa Alba Flower Extract; Rosa Centifolia Flower Oil; Rosa Centifolia Flower Extract; Rosa Gallica Flower Extract; Rosa Hybrid Flower Extract; Rosa Moschata Oil) 8007-01-0 / 90106-38-0 / 93334-48-6 / 84696-47-9 / 84604-12-6 / 84604-13-7 / 92347-25-6',
       '[3R-(3a,3aß,7ß,8aa)]-1-(2,3,4,7,8,8a-hexahydro-3,6,8,8-tetramethyl-1H-3a,7-methanoazulen-5-yl)ethan-1-one (Acetyl Cedrene) 32388-55-9',
       'Lemongrass Oil (Cymbopogon Schoenanthus Oil; Cymbopogon Flexuosus Oil; Cymbopogon Citratus Leaf Oil; Cymbopogon Citratus Leaf/Stem Oil; Cymbopogon Flexuosus Leaf/Stem Oil) 8007-02-1 / 89998-16-3 / 91844-92-7',
       'Citrus limon oil (Citrus Limon Peel Oil; Citrus Limon (Lemon) Peel Oil) 84929-31-7 / 8008-56-8',
       'Phenol 108-95-2', 'Butylated hydroxyanisole (BHA) 25013-16-5',
       '2-Phenoxyethanol 122-99-6',
       'Tertiary butyl alcohol (TBA) (t-Butyl alcohol) 75-65-0',
       'Cocamide diethanolamine (Cocamide DEA; Cocamide; Coconut oil diethanolamine condesate) 68603-42-9 / 61789-19-3 / 661791-31-9 / 68155-06-6',
       nan,
       'Ginkgo biloba extract (Ginkgo biloba leaf extract; Ginkgo biloba leaf; Ginkgo biloba leaf powder; Ginkgo biloba nut extract; Ginkgo biloba root extract; Ginkgo biloba leaf water; Ginkgo biloba leaf cell extract) 90045-36-6',
       'Jasmine Oil/Extract (Jasminum Grandiflorum Flower Extract; Jasminum Officinale Oil; Jasminum Officinale Flower Extract; Jasminum Grandiflorum (Jasmine) Flower Extract; Jasminum Grandiflorum (Jasmine) Flower Oil; Jasminum Officinale (Jasmine) Extract; Jasminum Officinale (Jasmine) Flower Extract; Jasminum Officinale (Jasmine) Oil) 84776-64-7 / 90045-94-6 / 8022-96-6 / 8024-43-9',
       'Polyquaternium compounds (Polyquats) ',
       'Isopropanol (Isopropyl alcohol) 67-63-0',
       'Sodium hydroxide 1310-73-2',
       '1,4-Dioxane (1,4-Diethyleneoxide) 123-91-1',
       'Ethylene oxide (Oxirane) 75-21-8',
       'Cetrimonium chloride 112-02-7',
       'Titanium dioxide (airborne, unbound particles of respirable size) (CI 77891) 13463-67-7',
       'Benzaldehyde 100-52-7',
       'o-Hydroxy-benzaldehyde (Salicylaldehyde) 90-02-8',
       'Methyl 2-hydroxybenzoate (Methyl Salicylate) 119-36-8',
       'Phenol, 2-methoxy-4-(2-propenyl)-, acetate (Eugenyl Acetate) 93-28-7',
       '5-(2,3-Dimethyl-tricyclo[2.2.1.02,6]-hept-3-yl)-2-methylpent-2-en-1-ol (alpha-Santalol) ((1S-(1a,2a(Z),4a))-2-Methyl-5-(2-methyl-3-methylenebicyclo[2.2.1]hept-2-yl)-2-penten-1-ol; beta-Santalol; Santalol) 11031-45-1 / 115-71-9 / 77-42-9',
       'Eugenia Caryophyllus Oil (Eugenia Caryophyllus Leaf Oil; Eugenia Caryophyllus Flower Oil; Eugenia Caryophyllus Stem oil; Eugenia Caryophyllus Bud oil; Eugenia Caryophyllus (Clove) Bud Oil; Eugenia Caryophyllus (Clove) Flower Oil; Eugenia Caryophyllus (Clove) Leaf Oil; Eugenia Caryophyllus (Clove) Stem Oil) 8000-34-8 /  8015-97-2 / 84961-50-2',
       'Cinnamomum cassia leaf oil (Cinnamomum cassia oil) 8007-80-5 / 84961-46-6',
       'Citrus Aurantium Flower Oil (Citrus Aurantium Amara Flower Oil; Citrus Aurantium Dulcis Flower Oil; Citrus Aurantium Amara (Bitter Orange) Flower Oil; Citrus Aurantium Dulcis (Orange)Flower Oil) 72968-50-4 / 8028-48-6 / 8016-38-4',
       'AMYL CINNAMAL ', 'Pulegone 89-82-7', 'CINNAMAL ',
       'L-Menthol ethylene glycol carbonate 156324-78-6',
       '1,7,7-trimethyl-3-(phenylmethylene)bicyclo[2.2.1]heptan-2-one (3-Benzylidene camphor (3-BC)) 15087-24-8',
       'Cocamide MEA 68140-00-1',
       'Titanium dioxide (1317-70-0) 1317-70-0',
       'Oak moss extract (EVERNIA PRUNASTRI EXTRACT; Evernia prunastri (oakmoss) extract) 90028-68-5',
       '3-Methyl-5-(2,2,3-Trimethyl-3-Cyclopentenyl)pent-4-en-2-ol (Trimethylcyclopentenyl Methylisopentenol) 67801-20-1',
       'Triethanolamine 102-71-6',
       'Cananga Odorata oil/extract (Cananga odorata flower oil and extract; Ylang Ylang flower oil and extract; Cananga Odorata Flower Extract; Cananga Odorata Flower Oil) 83863-30-3 / 8006-81-3 / 68606-83-7 / 93686-30-7',
       'Ginkgo Biloba Leaf Extract ', 'Formaldehyde (gas) 50-00-0',
       '1-Naphthalenepropanol, a-ethenyldecahydro- 2-hydroxy-a,2,5,5,8a-pentamethyl-, [1R-[1a(R),2ß,4aß,8aa]]- (Sclareol; [1R-(1alpha)]-alpha-Ethenyldecahydro-2-hydroxy-a,2,5,5,8a-pentamethyl-1-naphthalenepropanol) 515-03-7',
       '3-(2,2-Dimethyl-3-hydroxypropyl)toluene (Trimethylbenzenepropanol) 103694-68-4',
       '3-Propylidene-1(3H)-isobenzofuranone (3-Propylidenephthalide) 17369-59-4',
       'Laurus nobilis oil (Laurus Nobilis Leaf Oil) 8002-41-3 / 8007-48-5 / 84603-73-6',
       'Diethylene glycol monoethyl ether 111-90-0',
       '2-Pentyl-3-phenylprop-2-en-1-ol (AMYLCINNAMYL ALCOHOL) 101-85-9',
       'Cinnamomum zeylanicum bark oil 8015-91-6 / 84649-98-9',
       'Cetylpyridinium chloride 123-03-5', 'BENZYL CINNAMATE ',
       'Isopropyl Alcohol ', 'Aspartame 22839-47-0', 'Retinyl palmitate ',
       'Vitamin A palmitate 79-81-2', 't-butyl alcohol ', 'Cocamide DEA ',
       'FARNESOL ',
       'Coal tars (Coal tar; Coal tar extract; Coal tar solution; Coal tar distillates) ',
       'Phenacetin 62-44-2', 'Styrene 100-42-5',
       'Sodium sulfate 7757-82-6',
       '2-Naphthalenol, 1-[4-(phenylazo)phenyl]azo- (Red 17; Solvent Red 23; CI 26100; Aka225) 85-86-9',
       'Siloxanes and silicones, di-Me, hydrogen-terminated (Bis-hydrogen dimethicone; Hydrogen dimethicone) 70900-21-9',
       'Decamethylcyclopentasiloxane (D5) (Cyclopentasiloxane) 541-02-6',
       'Octamethylcyclotetrasiloxane (D4) (Cyclotetrasiloxane) 556-67-2',
       'Naphtha (petroleum), hydrotreated heavy (C10-11 Isoalkane (Formerly C10-11 Isoparaffin); C10-13 Isoalkane (Formerly C10-13 Isoparaffin); C11-12 Isoalkane (Formerly C11-12 Isoparaffin); C11-13 Isoalkane (Formerly C11-13 Isoparaffin); C10-12 Alkane/Cycloalkane) 64742-48-9',
       '6-Methylcoumarin (6-Methyl Coumarin) 92-48-8',
       'Myroxylon Pereirae Oil/Extract (Myroxylon balsamum\xa0var.\xa0pereirae; extracts and distillates; Balsam Peru oil, absolute and anhydrol (Balsam Oil Peru); Myroxylon Balsamum Pereirae Balsam Extract; Myroxylon Balsamum Pereirae Balsam Oil; Myroxylon Pereirae Oil; Myroxylon Pereirae Resin Extract; Myroxylon Pereirae Resin; Myroxylon Pereirae (Balsam Peru) Oil; Myroxylon Pereirae (Balsam Peru) Resin; Myroxylon Pereirae (Balsam Peru) Resin Extract) 8007-00-9',
       'Dodecamethylcyclohexasiloxane (D6) (Cyclohexasiloxane) 540-97-6',
       'Isobutane (containing greater than or equal to 0.1 % butadiene (203-450-8)) 75-28-5',
       'Behentrimonium chloride 17301-53-0',
       'Methylparaben (Methyl p-Hydroxybenzoate) 99-76-3',
       'n-Propylparaben (Propylparaben) 94-13-3',
       'Distillates (petroleum), hydrotreated middle (C12-20 Isoalkane (Formerly C12-20 Isoparaffin); C13-14 Alkane; C15-19 Alkane; C13-15 Alkane) 64742-46-7',
       'Myristamide DEA 7545-23-5', 'Aloe vera, whole leaf extract ',
       'Hydroxyisohexyl 3-cyclohexene carboxaldehyde (Lyral) 31906-04-4',
       'Quartz 14808-60-7', 'Bromelain, juice (Bromelain) 9001-00-7',
       'Papain 9001-73-4', 'Bromelain ', 'Caffeine 58-08-2',
       'ANISE ALCOHOL ', 'AMYLCINNAMYL ALCOHOL ', 'Acetaldehyde 75-07-0',
       'Retinyl acetate ',
       'Retinol/retinyl esters, when in daily dosages in excess of 10,000 IU, or 3,000 retinol equivalents. (Retinol; Retinol palmitate; Vitamin A; Vitamin A palmitate; All-trans retinoic acid; Retinyl acetate; Acetic acid, retinyl ester; Retinol palmitate; Vitamin A acetate; Retinyl palmitate; Retinol, palmitate, all-trans-; Retinyl acetate, all-trans-; Retinol acetate) ',
       'Retinol 68-26-8',
       "Adenosine, N-benzoyl-5'-O-[bis(4-methoxyphenyl) phenylmethyl]-2'-deoxy- 64325-78-6",
       'Glycol ethers ', 'Mineral oils, untreated and mildly treated ',
       'p-Cresol 106-44-5',
       'Turpentine gum (Pinus\xa0spp.); Turpentine oil and rectified oil; Turpentine, steam distilled (Pinus\xa0spp.) (Turpentine) 9005-90-7 / 8006-64-2 / 8052-14-0',
       '3-Methylphenol (m-Cresol) 108-39-4',
       '1,3-Dioxane, 2-(2,4-dimethyl-3-cyclohexen-1-yl)-5-methyl-5-(1-methylpropyl)- 117933-89-8 / 186309-28-4',
       'Diammonium peroxodisulphate 7727-54-0',
       'Ammonia, Total 7664-41-7',
       'Dipotassium peroxodisulphate 7727-21-1', '8-hydroxyquinoline ',
       'Butane (containing greater than or equal to  0,1\xa0% butadiene (203-450-8)) 106-97-8',
       'Petrolatum 8009-03-8', 'Benzalkonium chloride 8001-54-5',
       'C13-15 Alkane ', '4-t-Butylbenzoic Acid ',
       'Benzophenone 119-61-9', 'Dimethoxydiglycol ',
       'Dichloroacetic acid 79-43-6',
       'Ethyl paraben (Ethyl 4-hydroxybenzoate) 120-47-8',
       'Urs-12-en-28-oic acid, 3-hydroxy-, (3beta)- (Ursolic Acid) 77-52-1',
       'Ethylene glycol (Glycol) 107-21-1',
       'Carbon black (airborne, unbound particles of respirable size) 1333-86-4',
       'Benzo[b]thiophen-3(2H)-one, 6-chloro-2-(6-chloro-4-methyl- 3-oxobenzo[b]thien-2(3H)-ylidene)-4-methyl- (Red 30; Vat red 1; CI 73360; Aka226) 2379-74-0',
       'Trisiloxane, octamethyl- (Octamethyltrisiloxane; Trisiloxane) 107-51-7',
       'Talc-based body powder (perineal use of) 14807-96-6',
       'Aluminum (Aluminum powder; CI 77000) 7429-90-5',
       'Decamethyltetrasiloxane (Tetrasiloxane) 141-62-8',
       'Bronze Powder ',
       'Talc (includes Talc-based body powder (perineal use of), Talc containing asbestiform fibers other than asbestos, and Talc not containing asbestiform fibers) 14807-96-6',
       'Distillates (petroleum), heavy hydrocracked (C14-17 Alkane, C15-23 Alkane, C14-19 Alkane, C18-21 Alkane) 64741-76-0',
       'Copper (Bronze powder; Copper powder; CI 77400) 7440-50-8',
       'Safrole (5-(2-propenyl)-1,3-benzodioxole) 94-59-7',
       'Coffea arabica extract 84650-00-0', 'Diethanolamine 111-42-2',
       'Treemoss extract (EVERNIA FURFURACEA EXTRACT; Evernia furfuracea (treemoss) extract) 90028-67-4',
       '1,2,4-Trimethylbenzene (Trimethylbenzene) 95-63-6',
       '2,4-Dimethylphenol 105-67-9', '1-Methylnaphthalene 90-12-0',
       '1,3,5-Trimethylbenzene (Mesitylene) 108-67-8',
       'All-trans retinoic acid 302-79-4', 'Benzophenone-3 131-57-7',
       'Ursolic Acid ',
       '4- hydroxy-3-(1,2,3,4-tetrahydro-1-naphthyl) coumarin ',
       'Propylene glycol mono-t-butyl ether (1-tert-Butoxypropan-2-ol) 57018-52-7',
       'Isoprene 78-79-5', 'EVERNIA PRUNASTRI EXTRACT ', 'Sclareol ',
       '2-Ethylhexyl acrylate (Ethylhexyl Acrylate) 103-11-7',
       'A-alpha-C (2-Amino-9H-pyrido[2,3-b]indole) 26148-68-5', 'Red 27 ',
       'Di(2-ethylhexyl)phthalate (DEHP) 117-81-7',
       'Chlorine dioxide 10049-04-4', 'Hydrogenated Mineral Oil ',
       'Myrcene ', 'Coffee bean extract ', 'Coffee extract ',
       'Vitamin A 11103-57-4', 'Evernia Prunastri (Oakmoss) Extract ',
       'Isobutyl alcohol 78-83-1', 'EVERNIA FURFURACEA EXTRACT ',
       'Pinus Mugo (Pinus mugo\xa0leaf and twig oil and extract; Pinus Mugo Leaf Oil; Pinus Mugo Twig Leaf Extract; Pinus Mugo Twig Oil; Pinus Mugo Leaf/Twig Extract) 90082-72-7',
       'Verbena absolute (Lippia citriodora absolute; Lippia Citrodora Flower Extract; Lippia Citrodora Flower/Leaf/Stem Extract; Lippia Citrodora Leaf Extract) 8024-12-2 / 85116-63-8',
       'Narcissus Extract (Narcissus Poeticus Extract; Narcissus Pseudonarcissus Flower Extract; Narcissus Jonquilla Extract; Narcissus Tazetta Extract; Narcissus Pseudonarcissus (Daffodil) Flower Extract) 90064-26-9 / 68917-12-4 / 90064-27-0 / 90064-25-8',
       'Diethylene glycol monobutyl ether 112-34-5',
       'Propionaldehyde 123-38-6',

In [9]:
len(cdph)

534508

In [24]:
cdph.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,Concentration,Ingredient Submitted Date,Ingredient Removed Date
0,18358,Nail Alliance - Entity,Entity Nudite,Cool Pink Nail Sculpting Powder,NaN,NaN,6/24/2019,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,5.000000,6/24/2019,NaN
1,38661,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,40.000000,9/21/2015,NaN
2,38662,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Sprinkle,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,31.000000,9/21/2015,NaN
3,38667,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,12.000000,9/21/2015,NaN
4,38665,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,21.500000,9/21/2015,NaN

In [22]:
null = cdph[cdph['Ingredient Name'].isna()]
null.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,Concentration,Ingredient Submitted Date,Ingredient Removed Date
1402,72818,Exclusive Fragrances & Cosmetics,10 Corso Como,10 Corso Como Massage Oil,10 Corso Como,NaN,6/29/2010,NaN,NaN,NaN,NaN,NaN,NaN
1404,72816,IPD Inc,10 Corso Como,Corso Como Bath Pearls,Corso Como,NaN,6/25/2010,NaN,NaN,NaN,NaN,NaN,NaN
10283,109738,Aloisia Beauty Products Inc.,Aloisia Beauty,Light Hydration Emulsion,NaN,NaN,6/6/2022,NaN,NaN,NaN,NaN,NaN,NaN
10284,109736,Aloisia Beauty Products Inc.,Aloisia Beauty,Renew Concentrated Serum,NaN,NaN,6/6/2022,NaN,NaN,NaN,NaN,NaN,NaN
10286,109739,Aloisia Beauty Products Inc.,Aloisia Beauty,Revitalize Eye Cream,NaN,NaN,6/6/2022,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
ts = cdph[cdph["Concentration"] == "Trade Secret"]

In [23]:
cdph["Ingredient Name"].nunique()

495

In [5]:
ts.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,Concentration,Ingredient Submitted Date,Ingredient Removed Date
151,32263,Mary Kay Inc.,Mary Kay,Blonde Mechanical Brow Pencil,BLACK IRON OXIDE,3/15/2010,3/26/2014,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,Trade Secret,3/26/2014,NaN
152,32264,Mary Kay Inc.,Mary Kay,Blonde Mechanical Brow Pencil,COSMETIC RUSSET IRON OXIDE,3/15/2010,3/26/2014,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,Trade Secret,3/26/2014,NaN
153,32273,Mary Kay Inc.,Mary Kay,Brow Definer Pencil,BLACK IRON OXIDE,NaN,3/26/2014,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,Trade Secret,3/26/2014,NaN
154,32275,Mary Kay Inc.,Mary Kay,Brow Definer Pencil,COSMETIC RUSSET IRON OXIDE,NaN,3/26/2014,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,Trade Secret,3/26/2014,NaN
155,32274,Mary Kay Inc.,Mary Kay,Brow Definer Pencil,COSMETIC YELLOW IRON OXIDE,NaN,3/26/2014,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,Trade Secret,3/26/2014,NaN

In [8]:
pd.set_option("display.max_rows", None)
ts_brand = ts.groupby("Brand").size().rename("count").reset_index()
ts_brand.sort_values("count", ascending = False)

                                                  Brand  count
628                                             Kryolan  16411
373                                     Elizabeth Arden   2638
829                                             PERLIER   1795
188                                  CLE DE PEAU BEAUTE   1764
599                                         KIKO MILANO   1708
232                                   Charlotte Tilbury   1549
81                                                Aveda   1540
470                                             Granado   1521
950                                            SHISEIDO   1376
492                            HARBOR NATURAL COSMETICS   1353
1088                                    Tom Ford Beauty   1330
905                                             RITUALS   1317
751                                              NATURA   1241
1063                                    TIZIANA TERENZI   1210
810                                         ORGANIC WAY   1142
1181                                   e.l.f. Cosmetics   1101
346                                           Dr Teal's   1017
62                              Anastasia Beverly Hills    971
817                                               Oribe    945
145                                         Bobbi Brown    932
105                                            BY TERRY    915
79                                      Australian Gold    862
640                                     LIFE COLOR PLUS    853
880                                             Proraso    821
260                                            Clinique    814
656                                             Le Labo    784
49                                       Ajmal Perfumes    767
1167                                       bareMinerals    766
372                                              Elemis    741
437                               GERMAINE DE CAPUCCINI    736
632                                         L'Erbolario    724
799                                                OFRA    686
754                                      NEOM Wellbeing    684
849                                     Panier Des Sens    647
198                                               CREED    636
461                                            Glossier    635
332                                              Difeel    592
170                                           By Kilian    581
438                                  GIARDINO BENESSERE    568
923                                              Revlon    561
763                                                NUXE    551
1115                                            V CANTO    537
831                                            PHYTOMER    533
1156                                              ZARA     518
430                                      Frederic Malle    499
616                                        Kevyn Aucoin    475
1027                                         St Tropez     471
639                                               LELAS    468
647                                              La Mer    447
1162                                              aesop    447
1171                                         bodycology    435
577                                             Jergens    434
826                                        PAUL  &  JOE    428
714                                     Maryaj Perfumes    416
690                                               MONAT    412
305                                     DOLCE & GABBANA    400
580                                           Jo Malone    393
242                                            Claire's    390
823                                              Ouidad    378
212                                        Calvin Klein    377
211                                      California Tan    361
364                                               ETLEE    359
476                                      Gritti Venetia    353
112                                      Bain de Nature    347
945                                        SALT & STONE    345
982                            Sei Bella - Confidential    343
548                                             INSIGHT    329
2                                       & Other Stories    310
910                                        RUDY PROFUMI    309
729                                         Milk makeup    300
434                                  Fruit of the Earth    300
172                                         C.O.Bigelow    299
329                                       Designer Skin    295
845                                     Pacifica Beauty    290
733                                             Mitchum    285
1008                                 Smashbox Cosmetics    285
63                                     Andalou Naturals    284
480                                     Grown Alchemist    283
846                                      Palm Beach Tan    283
934                                         Rogue & Co.    280
1041                                            Sun Bum    278
732                                              Miniso    276
60                                        American Crew    272
917                                           Raw Sugar    270
218                                               Cantu    270
184                                                 CHI    270
570                                          JR Watkins    268
1161                                 Zotos Professional    265
710                                            Mary Kay    259
985                                           Senegence    258
916                                         Rare Beauty    258
165                                   Bumble and Bumble    256
1122                                           Vegamour    250
15                                               AINHOA    249
111                                              Badger    247
181                                    CAROLINA HERRERA    246
924                                 Revlon Professional    245
942                                              S-Curl    245
979                                    Seaweed Bath Co.    237
13                                              AG Care    237
134                                               Bigen    236
932                                        RoC Skincare    235
865                                                Pink    234
1094                                Too Faced Cosmetics    234
1060                                      TIGI Bed Head    231
187                                               CHLOE    230
374                                    Elizabeth Arden     225
1099                                    True Botanicals    221
1207                                          unbranded    220
830                                          PHYTOCEANE    217
1064                                              TOCCA    216
1130                                        W3LL PEOPLE    214
166                                            Burberry    214
676                                                 MAC    212
300                                           DEREK LAM    212
18                                               ALBION    211
781                                               Neuma    210
157                                          Boy Smells    208
1028                                           St. Ives    208
697                                         Maine Beach    207
881                                               Prose    206
312                                             Darphin    202
414                                     Faith In Nature    199
840                                           PROMASTER    196
869                                     Pleines Natures    192
1061                                         TIMEPHORIA    191
120                                          Beauty Pie    189
867                                  Pinnacle Cosmetics    188
822                                                Ouai    188
317                                     Delia Cosmetics    187
552                                      Image Skincare    184
590                                       Juicy Couture    183
801                                       OPI Gel Color    180
151                                         Bondi Boost    179
78                                              As I Am    178
789                                           Non-brand    175
124                                       Beautycounter    172
765                                           Nails Inc    170
773                            Nature;s Protein Doo Gro    167
833                             PHYTORELAX LABORATORIES    166
116                                    Baylis & Harding    164
529                                           Hugo Boss    164
1074                                    Team Dr. Joseph    163
1184                            eos Evolution of Smooth    162
37                                               Adidas    161
435                                  Function of Beauty    161
400                                            Evidence    160
325                                         Dermalogica    159
802                OPI Infinite Shine Long-Wear Lacquer    157
725                                        Michael Kors    156
864                                  Physicians Formula    156
660                                         Lip Smacker    155
201                                               CUTEX    155
103                                      BRAÉ HAIR CARE    154
1185                                            epionce    154
390                                 Essences Botaniques    147
852                                       Pattern (BHG)    147
17                                                 AKRO    146
645                                              LUSETA    141
786                                       Nicole Miller    140
285                                     Crème of Nature    138
265                                            Cococare    138
146                                      Body Fantasies    138
646                                       La Collection    137
1039                                     Summer Fridays    137
807                               OPI Powder Perfection    136
863                                          Philosophy    136
367                                     EXTREME CAVIAR     135
26                                             ANNA SUI    133
1098                                            Trilogy    133
221                                              Carmex    133
137                                            Bioglitz    132
531                                             Hurraw!    129
981                                           Sei Bella    129
870                                               Ponds    128
20                                      ALTER EGO ITALY    128
292                                               Curls    127
815                                            Old Navy    127
343                                   Dollar Shave Club    127
1093                                          Too Faced    127
966                                               SUKIN    126
313                                            Davidoff    126
272                                          ColorProof    126
921                                         Reservation    126
820                                             Osmosis    125
501                                      HI PEACH LAYNE    122
619                             Kimchi chic beauty llc     120
412                                             FLEUR'S    119
189                                                 CND    118
666                                                Love    116
1140                                         Wet n Wild    116
269                                  Collection Noel 2     116
581                                         John Frieda    115
94                                         BEAUTY RENEW    114
912                                             Rabanne    114
546                                          INFINIMENT    114
556                                          Innersense    112
709                                              Marvis    111
303                                                DKNY    111
459                                               Gleam    110
586                                               Joico    109
545                                            IN ASTRA    109
1084                                 Thrive Causemetics    107
481                                          H&M Beauty    107
220                                              Caress    105
723                              Merle Norman Cosmetics    105
576                                 Jason Wu Beauty LLC    104
663                                             LolaVie    103
621                                                Kiss    103
948                                        SEMI DI LINO    103
319                                             Delon +    102
648                                             LaCOSTE    101
387                                   Ermenegildo Zegna    101
716                                   Meaningful Beauty    101
1053                                     Swedish Beauty     98
868                                   Plaisirs Nature 3     97
758                                       NOTEZ LIBRARY     96
447                                               GUESS     95
487          HAIR COMPANY PROFESSIONAL INIMITABLE STYLE     95
1038                                           Sulfur 8     94
622                                              Kitsch     93
989                                            Sephora      93
75                                               Arlo's     92
97                                        BLACK BACCARA     91
857                                       Personal Care     90
861                                   Peter Thomas Roth     89
440                                          GLOSSPOPPI     89
428                                        Formula 1006     89
835              PLASTICA DOS FIOS HAIR PLASTIC SURGERY     88
788                                                 No7     88
670                                              Lumene     87
234                                             Chenice     87
67                                              Anthony     87
1035                                   Studio Selection     87
465                                      Good Chemistry     86
174                                CADIVEU PROFESSIONAL     86
1085                                      Thrive Market     86
144                                          Blue Magic     86
777                                             Nautica     86
254                                         Claus Porto     85
550                                               Icing     85
441                                           GM COLLIN     84
939                                                 Roz     84
909                                         RUBY KISSES     84
51                                     Alchimie Forever     84
508                               Hand in Hand Soap LLC     83
997                                          ShortLooks     83
511                                          Happy Nuts     81
726                                      Mild By Nature     80
678                                    MAKE UP FOR EVER     79
1117                                     VIE COLLECTION     79
72                                               Aramis     79
1175                                         copy that.     79
1135                    Wella Professionals Color Touch     79
585                                      John Varvatos      79
411                                                FILA     79
328                                    Design Imposters     78
541                                          IL MAKIAGE     78
728                                                Milk     77
571                                                 JVN     77
739                                            Moor Spa     76
617                                       Keys Soulcare     76
611                                     Kate Somerville     75
961                                     SORALI COSMETIC     75
895                                          RACHEL ZOE     74
429                                             Frankly     74
95                                                 BEBE     74
937                                                Roux     74
563                                  JEAN PAUL GAULTIER     73
30                                ATOM FRESH LABORATORY     73
587                                   Jones Road Beauty     72
686                                              MILANI     72
12                                     ACQUA DI COLONIA     72
615                                        Kevin Murphy     71
744                                               Murad     71
1165                                             b.pure     70
408                                 FARMACY BEAUTY, LLC     70
497                                       HD LIFE STYLE     70
1032                                         StriVectin     67
1154                                        Young Nails     67
963                                             STETSON     67
836                                 PLATINUM & DIAMONDS     67
703                                         Marc Jacobs     66
572                                               JWOWW     65
482                                         H2O at Home     65
907                                              ROOTON     64
436                                      Future Society     64
1186                                            eva+avo     64
427                                   Florence by Mills     64
1091                                     Tommy Hilfiger     63
886                                            Pura Dor     63
369                                            Ecostyle     61
21                                                AMORA     61
193                                           COMModity     61
131                                               Betco     61
1124                                          Vera Wang     60
1121                                               Veet     59
875                                            Proactiv     59
1086                                           TimeWise     59
279                                   Couleurs Nature 4     59
36                                          Addison Rae     59
626                                              Kroger     59
672                                         Luna Bronze     58
584                          John Paul Mitchell Systems     58
106                                             BYKARTE     57
1133                                          Walgreens     57
397                                            Evereden     57
634                                       L:a BRUKET AB     56
1157                                    ZO Skin Health      56
344                                         Donna Karan     56
156                                      Bottega Veneta     55
592                                                KAHI     55
1070                                       Tammy Taylor     55
965                                        SUBLIME GOLD     55
718                                              Medik8     54
365                                              ETORAS     54

In [ ]:
cdph.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 534508 entries, 0 to 534507
Data columns (total 17 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Product Id                 534508 non-null  int64
 1   Company                    534508 non-null  object
 2   Brand                      534308 non-null  object
 3   Product Name               534508 non-null  object
 4   Variant                    187813 non-null  object
 5   Product Discontinued Date  39102 non-null   object
 6   Product Submitted Date     534508 non-null  object
 7   Ingredient Name            534186 non-null  object
 8   Function                   433384 non-null  object
 9   Unit of Measure            222747 non-null  object
 10  Concentration              224495 non-null  object
 11  Ingredient Submitted Date  534186 non-null  object
 12  Ingredient Removed Date    6627 non-null    object
 13  discontinued_year          39102 non-null   Int64
 14  product_submitted_year     534508 non-null  Int64
 15  ingredient_submitted_date  534186 non-null  Int64
 16  ingredient_removed_year    6627 non-null    Int64
dtypes: Int64(4), int64(1), object(12)
memory usage: 71.4+ MB

In [ ]:
cdph["Function"].unique()

array([nan, 'Fragrance', 'Conditioning/Emollient', 'Other (Specify)',
       'Preservative/Stabilizer', 'Flavor', 'Opacifying Agent',
       'Bulking/Viscosity', 'Solvent', 'Surfactant', 'Colorant',
       'Anticaking/Absorbents', 'Antioxidant', 'Moisturizing/Humectant',
       'Buffering/pH Adjusting', 'UV Inhibitor', 'Contaminant',
       'Emulsifier', 'Base'], dtype=object)

In [ ]:
cdph.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 534508 entries, 0 to 534507
Data columns (total 13 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Product Id                 534508 non-null  int64
 1   Company                    534508 non-null  object
 2   Brand                      534308 non-null  object
 3   Product Name               534508 non-null  object
 4   Variant                    187813 non-null  object
 5   Product Discontinued Date  39102 non-null   object
 6   Product Submitted Date     534508 non-null  object
 7   Ingredient Name            534186 non-null  object
 8   Function                   433384 non-null  object
 9   Unit of Measure            222747 non-null  object
 10  Concentration              224495 non-null  object
 11  Ingredient Submitted Date  534186 non-null  object
 12  Ingredient Removed Date    6627 non-null    object
dtypes: int64(1), object(12)
memory usage: 53.0+ MB

There have been 534,508 products reported since the beginning of the program

39,102 have been discontinued (appx 7%)

In [ ]:
cdph["discontinued_year"] = pd.to_datetime(cdph["Product Discontinued Date"]).dt.year
cdph["product_submitted_year"] = pd.to_datetime(cdph["Product Submitted Date"]).dt.year
cdph["ingredient_submitted_date"] = pd.to_datetime(cdph["Ingredient Submitted Date"]).dt.year
cdph["ingredient_removed_year"] = pd.to_datetime(cdph["Ingredient Removed Date"]).dt.year

In [ ]:
cdph["discontinued_year"] = cdph["discontinued_year"].astype("Int64")
cdph["product_submitted_year"] = cdph["product_submitted_year"].astype("Int64")
cdph["ingredient_submitted_date"] = cdph["ingredient_submitted_date"].astype("Int64")
cdph["ingredient_removed_year"] = cdph["ingredient_removed_year"].astype("Int64")

In [ ]:
cdph.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,Concentration,Ingredient Submitted Date,Ingredient Removed Date,discontinued_year,product_submitted_year,ingredient_submitted_date,ingredient_removed_year
0,18358,Nail Alliance - Entity,Entity Nudite,Cool Pink Nail Sculpting Powder,NaN,NaN,6/24/2019,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,5.000000,6/24/2019,NaN,<NA>,2019,2019,<NA>
1,38661,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,40.000000,9/21/2015,NaN,<NA>,2015,2015,<NA>
2,38662,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Black-Sprinkle,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,31.000000,9/21/2015,NaN,<NA>,2015,2015,<NA>
3,38667,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,12.000000,9/21/2015,NaN,<NA>,2015,2015,<NA>
4,38665,"Xtreme Color, Inc.",Hard Candy,Fierce Effects- Shadow Duo,Brown-Solid,NaN,9/21/2015,Titanium dioxide (CI 77891) 13463-67-7 / 1317-...,NaN,mg/g,21.500000,9/21/2015,NaN,<NA>,2015,2015,<NA>

In [ ]:
no_ts = cdph[cdph["Concentration"] != "Trade Secret"]

In [ ]:
no_ts["Concentration"] = no_ts["Concentration"].astype("float")

/var/folders/p6/tqnlcwnd075_z06_lxt45pv40000gn/T/ipykernel_91911/1848226041.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  no_ts["Concentration"] = no_ts["Concentration"].astype("float")

In [ ]:
no_ts.info()

<class 'pandas.core.frame.DataFrame'>
Index: 420446 entries, 0 to 534507
Data columns (total 17 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Product Id                 420446 non-null  int64
 1   Company                    420446 non-null  object
 2   Brand                      420262 non-null  object
 3   Product Name               420446 non-null  object
 4   Variant                    143897 non-null  object
 5   Product Discontinued Date  36508 non-null   object
 6   Product Submitted Date     420446 non-null  object
 7   Ingredient Name            420124 non-null  object
 8   Function                   322652 non-null  object
 9   Unit of Measure            109965 non-null  object
 10  Concentration              110433 non-null  float64
 11  Ingredient Submitted Date  420124 non-null  object
 12  Ingredient Removed Date    5764 non-null    object
 13  discontinued_year          36508 non-null   Int64
 14  product_submitted_year     420446 non-null  Int64
 15  ingredient_submitted_date  420124 non-null  Int64
 16  ingredient_removed_year    5764 non-null    Int64
dtypes: Int64(4), float64(1), int64(1), object(11)
memory usage: 59.3+ MB

In [ ]:
no_ts["Concentration"].mean()

np.float64(22.88877946678982)

In [ ]:
no_ts.info()

<class 'pandas.core.frame.DataFrame'>
Index: 420446 entries, 0 to 534507
Data columns (total 17 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Product Id                 420446 non-null  int64
 1   Company                    420446 non-null  object
 2   Brand                      420262 non-null  object
 3   Product Name               420446 non-null  object
 4   Variant                    143897 non-null  object
 5   Product Discontinued Date  36508 non-null   object
 6   Product Submitted Date     420446 non-null  object
 7   Ingredient Name            420124 non-null  object
 8   Function                   322652 non-null  object
 9   Unit of Measure            109965 non-null  object
 10  Concentration              110433 non-null  float64
 11  Ingredient Submitted Date  420124 non-null  object
 12  Ingredient Removed Date    5764 non-null    object
 13  discontinued_year          36508 non-null   Int64
 14  product_submitted_year     420446 non-null  Int64
 15  ingredient_submitted_date  420124 non-null  Int64
 16  ingredient_removed_year    5764 non-null    Int64
dtypes: Int64(4), float64(1), int64(1), object(11)
memory usage: 59.3+ MB

In [ ]:
import altair as alt

In [ ]:
cdph.sort_values("Concentration")

In [ ]:
submissions = cdph.groupby("product_submitted_year").size().rename("product_count").reset_index()
submissions

    product_submitted_year  product_count
0                     2009          28251
1                     2010          13522
2                     2011           4191
3                     2012           3317
4                     2013           5787
5                     2014           7647
6                     2015           6825
7                     2016           4008
8                     2017           7256
9                     2018           9387
10                    2019          13123
11                    2020           3543
12                    2021          17232
13                    2022         105184
14                    2023          58541
15                    2024          89591
16                    2025         155075
17                    2026           2028

In [ ]:
discontinued = cdph.groupby("discontinued_year").size().rename("product_count").reset_index()
discontinued

    discontinued_year  product_count
0                2001              2
1                2004             21
2                2005              6
3                2006             16
4                2007            222
5                2008            366
6                2009            742
7                2010           1064
8                2011           1241
9                2012            975
10               2013           3886
11               2014           2283
12               2015           1783
13               2016           2138
14               2017           1014
15               2018            752
16               2019            724
17               2020            676
18               2021           1683
19               2022           3884
20               2023           5689
21               2024           4029
22               2025           5903
23               2027              3

In [ ]:
total_products = discontinued["product_count"].sum()
print(total_products)

39102

In [ ]:
import altair as alt

# Discontinued Products by Year

In [ ]:
alt.Chart(discontinued).mark_bar().encode(
    x="discontinued_year",
    y="product_count"
)

alt.Chart(...)

# Submitted Products by Year

In [ ]:
alt.Chart(submissions).mark_bar().encode(
    x="product_submitted_year",
    y="product_count"
)

alt.Chart(...)

In [ ]:
ingredients = cdph.groupby("Ingredient Name").size().rename("total_count").reset_index()
ingredients.sort_values("total_count", ascending = False)

                                       Ingredient Name  total_count
451  Titanium dioxide (CI 77891) 13463-67-7 / 1317-...        91510
311  Limonene (1-methyl-4-prop-1-en-2-yl-cyclohexen...        42034
10   1,6-Octadien-3-ol, 3,7-dimethyl- (LINALOOL) 78...        29596
125                            Benzyl alcohol 100-51-6        17246
128                         Benzyl salicylate 118-58-1        15145
302                                          LINALOOL         14827
183  Citronellol /+- 3,7-dimethyloct-6-en-1-ol (CIT...        14264
126                           Benzyl benzoate 120-51-4        14030
25   2,6-Octadien-1-ol, 3,7-dimethyl-, (2E)- (GERAN...        13247
157                                       CITRONELLOL         11504
289  Hydroxycitronellal (7-Hydroxycitronellal) 107-...        11491
156                                            CITRAL         10417
269                                          GERANIOL         10389
32      2-Benzylideneoctanal (HEXYL CINNAMAL) 101-86-0         9975
57   3-Methyl-4-(2,6,6-trimethyl-2-cyclohexen-1-yl)...         9851
52            2H-1-Benzopyran-2-one (COUMARIN) 91-64-5         9698
180  Citral (3,7-Dimethyl-2,6-octadienal; (E)-3,7-d...         8647
53   3,7-Dimethyl octa-1,6-diene-3-yl acetate (Lina...         8011
158                                          COUMARIN          7278
452  Titanium dioxide (airborne, unbound particles ...         7189
281                                    HEXYL CINNAMAL          7156
12   1-(1,2,3,4,5,6,7,8-octahydro-2,3,8,8-tetrameth...         7070
5    1,3,4,6,7,8-Hexahydro-4,6,6,7,8,8-hexamethylcy...         6255
381  Pinene (2,6,6-Trimethylbi-cyclo[3.1.1]hept-2-e...         5402
63   4-Hydroxy-3-methoxybenz-aldehyde (Vanillin) 12...         5050
294  Isoeugenol (Phenol, 2-methoxy-4-(1-propenyl); ...         4885
239                                           EUGENOL          4883
424  Silica, crystalline (airborne particles of res...         4813
185  Citrus Aurantium Peel Oil (Citrus Aurantium Am...         4480
44                           2-Phenoxyethanol 122-99-6         4273
378  Phenol, 2-methoxy-4-(2-propenyl)- (EUGENOL) 97...         4186
77                             ALPHA-ISOMETHYL IONONE          3992
28   2-(4-methylcyclohex-3-en-1-yl)propan-2-ol; p-M...         3988
187  Citrus limon oil (Citrus Limon Peel Oil; Citru...         3954
179                          Cinnamyl alcohol 104-54-1         3942
26   2,6-Octadien-1-ol, 3,7-dimethyl-,1-acetate, (2...         3462
384       Pogostemon cablin oil 8014-09-3 / 84238-39-1         3359
441  Talc (includes Talc-based body powder (perinea...         2973
0    (1R,4E,9S)-4,11,11-Trimethyl-8-methylenebicycl...         2597
417  Rose Ketones (1-(2,6,6-trimethyl-2-cyclohexen-...         2576
186  Citrus aurantium bergamia oil (Bergamot oil) (...         2483
477                    beta-Myrcene (Myrcene) 123-35-3         2407
31      2-Benzylideneheptanal (AMYL CINNAMAL) 122-40-7         2286
475  [3R-(3a,3aß,7ß,8aa)]-1-(2,3,4,7,8,8a-hexahydro...         2256
24   2,6,10-Dodecatrien-1-ol, 3,7,11-trimethyl- (FA...         2184
300  Juniperus Virginiana Oil (Juniperus Virginiana...         2170
472                        Vitamin A palmitate 79-81-2         2106
259                                          FARNESOL          2100
141          Butylated hydroxyanisole (BHA) 25013-16-5         1989
155                                          CINNAMAL          1927
340                                    Mica 12001-26-2         1851
78                                      AMYL CINNAMAL          1832
45                 2-Phenoxyethyl isobutyrate 103-60-6         1821
306  Lavandula Oil/Extract (Lavandula hybrida oil/e...         1795
368  Pelargonium graveolens oil (Pelargonium Graveo...         1699
164                             Carbon black 1333-86-4         1698
489       p-Mentha-1,4(8)-diene (Terpinolene) 586-62-9         1690
371  Pentyl-2-hydroxy-benzoate (Amyl Salicylate) 20...         1532
195  Cocamide diethanolamine (Cocamide DEA; Cocamid...         1503
47           2-Propenal, 3-phenyl- (CINNAMAL) 104-55-2         1441
488       p-Mentha-1,3-diene (Alpha-Terpinene) 99-86-5         1385
110                              Benzaldehyde 100-52-7         1292
38   2-Methyl-1-phenyl-2-propyl acetate; Dimethylbe...         1276
432                         Sodium hydroxide 1310-73-2         1255
134  Bornan-2-one; 1,7,7-Trimethylbi-cyclo[2.2.1]-2...         1237
29   2-(4-tert-Butylbenzyl)propionaldehyde (Lilial;...         1169
318  Menthol (dl-menthol; l-menthol; d-menthol) 89-...         1094
339   Methylparaben (Methyl p-Hydroxybenzoate) 99-76-3         1093
415                                 Retinyl palmitate          1082
338             Methyleugenol (Methyl eugenol) 93-15-2          984
50   2-methyl-5-(prop-1-en-2-yl)cyclohex-2-en-1-one...          965
107                       BUTYLPHENYL METHYLPROPIONAL           959
224                    Diethyl phthalate (DEP) 84-66-2          906
106                                  BENZYL CINNAMATE           884
480            n-Propylparaben (Propylparaben) 94-13-3          879
416  Rose Flower Oil/Extract (Rosa damascena flower...          846
58   3-Methyl-5-(2,2,3-Trimethyl-3-Cyclopentenyl)pe...          830
48   2-Propenoic acid, 3-phenyl-, phenylmethyl este...          807
279                                     Glycol ethers           804
249   Ethyl paraben (Ethyl 4-hydroxybenzoate) 120-47-8          782
84                                Acetophenone 98-86-2          760
325  Methyl 2-Octynoate (Methyl Oct-2-ynoate; Methy...          755
413  Retinol/retinyl esters, when in daily dosages ...          752
226         Diethylene glycol monoethyl ether 111-90-0          742
254  Eucalyptus Globulus Oil (Eucalyptus Globulus L...          702
341        Mineral oils, untreated and mildly treated           701
80                                      ANISE ALCOHOL           666
163  Carbon black (airborne, unbound particles of r...          650
37   2-Methoxy-4-prop-1-enylphenyl acetate (Isoeuge...          644
244                                 Estragole 140-67-0          619
162  Cananga Odorata oil/extract (Cananga odorata f...          588
365  Oxacyclohepta-decan-2-one (Hexadecanolactone) ...          580
64    4-Methoxybenzyl alcohol (ANISE ALCOHOL) 105-13-5          570
55   3-(2,2-Dimethyl-3-hydroxypropyl)toluene (Trime...          554
316  Mentha piperita oil (Mentha Piperita (Peppermi...          552
184  Citrus Aurantium Flower Oil (Citrus Aurantium ...          534
458                           Triethanolamine 102-71-6          502
13   1-Methoxy-4-(1E)-1-propen-1-yl-benzene (trans-...          469
296            Isopropanol (Isopropyl alcohol) 67-63-0          467
212  Decamethylcyclopentasiloxane (D5) (Cyclopentas...          441
109                 Behentrimonium chloride 17301-53-0          423
297                                 Isopropyl Alcohol           422
210                                Cyclopentasiloxane           389
151  CI 77891 (airborne, unbound particles of respi...          370
446  Tertiary butyl alcohol (TBA) (t-Butyl alcohol)...          363
299  Jasmine Oil/Extract (Jasminum Grandiflorum Flo...          359
343                                           Myrcene           353
317  Mentha spicata oil (spearmint oil) (Mentha Vir...          351
410                                    Retinol 68-26-8          341
79                               AMYLCINNAMYL ALCOHOL           316
255  Eugenia Caryophyllus Oil (Eugenia Caryophyllus...          302
276  Ginkgo biloba extract (Ginkgo biloba leaf extr...          289
361  Oak moss extract (EVERNIA PRUNASTRI EXTRACT; E...          271
194                            Cocamide MEA 68140-00-1          271
121                              Benzophenone 119-61-9          269
290  Hydroxyisohexyl 3-cyclohexene carboxaldehyde (...          268
169                      Cetrimonium chloride 112-02-7          261
287                              Hydroquinone 123-31-9          254
9           1,4-Dioxane (1,4-Diethyleneoxide) 123-91-1          253
420  Santalum album oil (Santalum Album (Sandalwood...          245
91   Aloe vera, non-decolorized (unfiltered) whole ...          238
166  Cedrus Atlantica Oil/Extract (Cedrus atlantica...          234
397                                   Pulegone 89-82-7          232
400                                  Quartz 14808-60-7          227
178  Cinnamomum zeylanicum bark oil 8015-91-6 / 846...          226
490                        p-Phenylenediamine 106-50-3          224
69   5-(2,3-Dimethyl-tricyclo[2.2.1.02,6]-hept-3-yl...          224
193                                      Cocamide DEA           222
380                          Phosphoric acid 7664-38-2          216
487                                  p-Cresol 106-44-5          214
92                      Aloe vera, whole leaf extract           209
326  Methyl 2-hydroxybenzoate (Methyl Salicylate) 1...          203
309  Lemongrass Oil (Cymbopogon Schoenanthus Oil; C...          197
204                                     Cosmetic talc           195
433                           Sodium sulfate 7757-82-6          190
419  Safrole (5-(2-propenyl)-1,3-benzodioxole) 94-59-7          184
252                   Ethylene oxide (Oxirane) 75-21-8          180
374                               Petrolatum 8009-03-8          179
93      Aluminum (Aluminum powder; CI 77000) 7429-90-5          173
379  Phenol, 2-methoxy-4-(2-propenyl)-, acetate (Eu...          171
223                     Diethyl hexyl adipate 103-23-1          164
310                                            Lilial           159
284                              Hydrogen Dimethicone           155
322                  Methanol (Methyl alcohol) 67-56-1          152
262                         Formaldehyde (gas) 50-00-0          152
454                                   Toluene 108-88-3          150
43   2-Pentyl-3-phenylprop-2-en-1-ol (AMYLCINNAMYL ...          141
209                                 Cyclohexasiloxane           131
445  Talc-based body powder (perineal use of) 14807...          131
345  Myroxylon Pereirae Oil/Extract (Myroxylon bals...          124
470                               Vitamin A 11103-57-4          117
81                                Acetaldehyde 75-07-0          114
246             Ethanol in alcoholic beverages 64-17-5          107
16   1-Naphthalenepropanol, a-ethenyldecahydro- 2-h...          107
83                                     Acetone 67-64-1          104
95                            Ammonia, Total 7664-41-7          101
177  Cinnamomum cassia leaf oil (Cinnamomum cassia ...           97
298  Isopropyl alcohol manufacture using strong acids            97
388              Polyquaternium compounds (Polyquats)            93
274                        Ginkgo Biloba Leaf Extract            87
421                                          Sclareol            85
257               Evernia Prunastri (Oakmoss) Extract            85
465  Turpentine gum (Pinus spp.); Turpentine oil an...           79
425  Siloxanes and silicones, di-Me, hydrogen-termi...           78
448             Titanium dioxide (1317-70-0) 1317-70-0           76
394                                     Propylparaben            74
436                                   Styrene 100-42-5           73
161                                   Caffeine 58-08-2           71
456  Treemoss extract (EVERNIA FURFURACEA EXTRACT; ...           71
199                                            Coffee            68
60   3-Propylidene-1(3H)-isobenzofuranone (3-Propyl...           67
238  Dodecamethylcyclohexasiloxane (D6) (Cyclohexas...           66
463  Trisiloxane, octamethyl- (Octamethyltrisiloxan...           66
197                  Coffea arabica extract 84650-00-0           63
347  N,N-Dimethyl-p-toluidine (Dimethyltolylamine) ...           62
250                  Ethylene glycol (Glycol) 107-21-1           56
336       Methylene chloride (Dichloromethane) 75-09-2           55
405                                            Red 27            54
293                           Isobutyl alcohol 78-83-1           53
236  Distillates (petroleum), hydrotreated middle (...           52
493                                   t-butyl alcohol            52
355  Narcissus Extract (Narcissus Poeticus Extract;...           46
182                Citric acid, nickel salt 22605-92-1           46
247                            Ethyl acrylate 140-88-5           45
132                                           Black 2            45
142     Butylparaben (butyl 4-hydroxybenzoate) 94-26-8           42
222                            Diethanolamine 111-42-2           41
486                      p-Aminodiphenylamine 101-54-2           41
133  Black 2 (airborne, unbound particles of respir...           41
123                            Benzophenone-3 131-57-7           40
450           Titanium dioxide (98084-96-9) 98084-96-9           38
241                         EVERNIA PRUNASTRI EXTRACT            37
191  Coal tars (Coal tar; Coal tar extract; Coal ta...           36
389                               Progesterone 57-83-0           36
305  Laurus nobilis oil (Laurus Nobilis Leaf Oil) 8...           35
119  Benzo[b]thiophen-3(2H)-one, 6-chloro-2-(6-chlo...           35
376                                 Phenacetin 62-44-2           33
292  Isobutane (containing greater than or equal to...           33
202  Copper (Bronze powder; Copper powder; CI 77400...           33
462                                       Trisiloxane            32
4    1,2,4-Trimethylbenzene (Trimethylbenzene) 95-63-6           30
71   5-sec-butyl-2-(2,4-dimethylcyclohex-3-en-1-yl)...           30
366                                   Papain 9001-73-4           28
270  Gases (petroleum), dry sour, gas-concn.-unit-o...           28
391  Propylene glycol mono-t-butyl ether (1-tert-Bu...           28
206                 Cresols, Cresol mixtures 1319-77-3           27
112                                    Benzene 71-43-2           27
70   5-Methoxypsoralen with ultraviolet A therapy 4...           25
22                         2,4-Dimethylphenol 105-67-9           24
143                                     C13-15 Alkane            23
392                            Propylene oxide 75-56-9           23
372  Perfluoroalkyl and polyfluoroalkyl substances ...           23
256             Evernia Furfuracea (Treemoss) Extract            22
404                                            Red 21            22
348  N-Methylpyrrolidone (Methyl pyrrolidone) 872-50-4           22
304                  Lauramide diethanolamine 120-40-1           21
189                                 Coal tar 8007-45-2           21
46                2-Phenoxyethyl propionate 23495-12-7           21
150                                          CI 77891            21
139  Butane (containing greater than or equal to  0...           20
307                                     Lead 7439-92-1           20
14                         1-Methylnaphthalene 90-12-0           20
6         1,3,5-Trimethylbenzene (Mesitylene) 108-67-8           20
170                  Cetylpyridinium chloride 123-03-5           20
423                         Selenium sulfide 7446-34-6           19
168                        Cetrimonium bromide 57-09-0           19
449             Titanium dioxide (1317-80-2) 1317-80-2           18
426      Silver (CI 77820; Colloidal silver) 7440-22-4           18
42   2-Naphthalenol, 1-[4-(phenylazo)phenyl]azo- (R...           18
229                                 Dimethoxydiglycol            18
85                                  Acrylamide 79-06-1           18
7    1,3-Dioxane, 2-(2,4-dimethyl-3-cyclohexen-1-yl...           18
216                 Di-n-butyl phthalate (DBP) 84-74-2           17
3                           1,1-Dichloroethane 75-34-3           17
362  Octamethylcyclotetrasiloxane (D4) (Cyclotetras...           17
228                             Dihydrosafrole 94-58-6           17
434  Spiro[isobenzofuran-1(3H),9'-[9H]xanthen]-3-on...           16
353  Naphtha (petroleum), hydrotreated heavy (C10-1...           16
82                 Acetic acid, retinyl ester 127-47-9           16
111                    Benzalkonium chloride 8001-54-5           16
468  Verbena absolute (Lippia citriodora absolute; ...           15
219                        Dichloroacetic acid 79-43-6           14
398                                  Pyridine 110-86-1           14
363                Oil Orange SS (Daidai403) 2646-17-5           14
129  Bis(2-methoxyethyl) ether (Dimethoxydiglycol, ...           13
443                Talc containing asbestiform fibers            13
261  Formaldehyde (Formaldehyde (gas); Formaldehyde...           13
474                                     Zinc 7440-66-6           13
390                           Propionaldehyde 123-38-6           13
181       Citric acid, ammonium nickel salt 18283-82-4           13
430  Sodium N-(hydroxymethyl)glycinate (Sodium Hydr...           13
217              Diammonium peroxodisulphate 7727-54-0           13
418                     Rosin, hydrogenated 65997-06-0           12
330            Methyl chloride (Chloromethane) 74-87-3           12
232             Dipotassium peroxodisulphate 7727-21-1           12
203                                     Copper Powder            12
99          Arsenic (7440-38-2) and arsenic compounds            12
334                  Methyl methacrylate (MMA) 80-62-6           11
103             Aspirin (Acetylsalicylic acid) 50-78-2           11
481   o-Hydroxy-benzaldehyde (Salicylaldehyde) 90-02-8           11
240                        EVERNIA FURFURACEA EXTRACT            11
120  Benzoic acid, 2,3,4,5-tetrachloro-6-(2, 4,5,7-...           11
104                              Avobenzone 70356-09-1           10
72        6-Methylcoumarin (6-Methyl Coumarin) 92-48-8           10
11   1,7,7-trimethyl-3-(phenylmethylene)bicyclo[2.2...           10
86                                Acrylic acid 79-10-7           10
479                                  n-Hexane 110-54-3           10
36   2-Ethylhexyl acrylate (Ethylhexyl Acrylate) 10...           10
146                                          CI 73360            10
403        Quinoline and its strong acid salts 91-22-5            9
136             Bromelain, juice (Bromelain) 9001-00-7            9
414                                   Retinyl acetate             9
442                                     Talc (powder)             9
27   2-(2H-benzotriazol-2-yl)-4-(1,1,3,3-tetramethy...            9
1    (±)-1,7,7-trimethyl-3-[(4-methylphenyl)methyle...            9
457                       Trichloroacetic acid 76-03-9            9
483                             o-Phenylphenol 90-43-7            8
18   2,2-Bis(bromomethyl)-1,3-propanediol (2,2-Bis(...            8
201                                    Coffee extract             8
165                             Carbon black extracts             8
59                  3-Methylphenol (m-Cresol) 108-39-4            8
460  Trimethylolpropane triacrylate, technical grad...            8
282  Hexamethylene-1,6-diisocyanate (Hexamethylene ...            8
160                              Caffeic acid 331-39-5            7
308           Lead acetate (Lead di(acetate)) 301-04-2            7
399       Pyrithione zinc (Zinc pyrithione) 13463-41-7            7
406                                            Red 30             7
8     1,4-Dichlorobenzene (p-Dichlorobenzene) 106-46-7            7
377                                    Phenol 108-95-2            7
94                                    Aluminum Powder             7
491  reaction mass of: cis-4- hydroxy-3-(1,2,3,4-te...            7
40                   2-Methylphenol (o-Cresol) 95-48-7            6
54   3,7-dimethylocta-2,6- dienenitrile (Geranonitr...            6

In [ ]:
pd.set_option('display.max_rows', None)
brands = cdph.groupby("Brand").size().rename("total_count").reset_index()
top_50_brands = brands.sort_values("total_count", ascending = False).head(50)
top_50_brands

                                    Brand  total_count
551                     Bath & Body Works        57104
2143                              Kryolan        22538
4136             Victoria's Secret Beauty        15386
2336              Lush Handmade Cosmetics         9285
1242                                 Dove         4778
3448                             Sephora          4735
911                     Charlotte Tilbury         4330
2993               Parfums Christian Dior         4049
1346                      Elizabeth Arden         3998
2349               L’OCCITANE EN PROVENCE         3981
1591                             GUERLAIN         3907
3961  The Body Shop International Limited         3829
494                               BVLGARI         3658
1238                              Dossier         3630
758                                CHANEL         3567
1806                        Henry Jacques         3349
84                                   ALT.         3244
2234                              Lancome         3226
2607                                 NARS         3220
3978                    The White Company         3181
3233                               Revlon         3136
2817                            Old Spice         3075
2152                        L'OREAL PARIS         3069
2641                                  NYX         3007
1640                             Goldwell         2742
4326                         bareMinerals         2611
4437                                tarte         2601
2474                           Maybelline         2413
770                    CLE DE PEAU BEAUTE         2391
2147                                L'BEL         2366
2151                              L'OREAL         2158
2560                          Moroccanoil         2077
1566                       GIORGIO ARMANI         2055
4230                                  YSL         2027
1302                                 ESPA         1941
2356                     MAKE UP FOR EVER         1862
2300               Love Beauty And Planet         1850
217               Anastasia Beverly Hills         1832
3332                             SHISEIDO         1829
68                         ACQUA DI PARMA         1802
2866                              PERLIER         1800
1116                              Davines         1759
1983                                Jafra         1750
3388                         Sally Hansen         1742
1095                      DOLCE & GABBANA         1741
1246                            Dr Teal's         1730
3960                        The Body Shop         1715
3338                       SISLEY - PARIS         1715
2055                          KIKO MILANO         1711
1041                            Covergirl         1659

In [ ]:
alt.Chart(top_50_brands).mark_bar().encode(
    x = "total_count",
    y = alt.Y("Brand").sort("-x")
)

alt.Chart(...)

In [ ]:
product_types = cdph.groupby("Product Category").size().rename("product_count").reset_index().sort_values("product_count", ascending=False)

KeyError: 'Product Category'

In [ ]:
pd.set_option('display.max_rows', None)
product_types.sort_values("product_count", ascending = False)
product_types

                                     Product Category  product_count
25                              Foundations and Bases         237005
68                            Perfumes/Eaux de Parfum         231647
79        Skin Moisturizers (making a cosmetic claim)          79633
87                      Toilet Water/Eaux de Toilette          74532
11                              Body Washes and Soaps          65144
63                            Other Skin Care Product          48725
41         Lip Color - Lipsticks, Liners, and Pencils          40441
33           Hair Shampoos (making a cosmetic claim)           38935
29                      Hair Conditioners (rinse-out)          32932
55                                   Other Fragrances          30501
66                        Perfumes - Oils and Lotions          29005
38                      Hand Cleansers and Sanitizers          26583
36                              Hair Styling Products          26224
18                                         Eye Shadow          24872
77                                     Skin Cleansers          24233
61                       Other Personal Care Product           23916
13                                            Cologne          21635
21                                       Facial Cream          21617
42                                    Lip Gloss/Shine          19883
56                            Other Hair Care Product          19673
30                               Hair Dyes and Colors          18376
89                                Underarm Deodorants          16996
50                             Nail Polish and Enamel          14951
28                       Hair Conditioners (leave-in)          14412
39                            Indoor Tanning Products          12443
20                                       Face Powders          12370
40                 Lip Balm (making a cosmetic claim)          11783
2   Anti-Wrinkle/Anti-Aging Products (making a cos...          10112
19                           Eyeliner/Eyebrow Pencils           9127
10                                           Blushes            8994
82               Sunscreen (making a cosmetic claim)            8450
22                                       Facial Masks           8058
73                              Scrubs and Exfoliants           7467
12                      Bubble and Foam Bath Products           7145
58                               Other Makeup Product           6441
81                      Sprays (excluding fragrances)           6439
54                                Other Bath Products           5340
1                                 Aftershave Products           4939
3           Antiperspirants (making a cosmetic claim)           4910
9                                      Bath Additives           4272
52                                Nighttime Skin Care           4099
84                       Tattoos and Permanent Makeup           3746
74            Shaving Cream and other Beard Softeners           3529
80               Skin Toner (making a cosmetic claim)           3350
88                                 UV Gel Nail Polish           3313
46                           Mascara/Eyelash Products           3046
17                                            Douches           2760
67                      Perfumes - Solids and Powders           2682
85                            Teeth Cleaning Products           2485
4               Artificial Nails and Related Products           2400
48                            Nail Creams and Lotions           2370
62                              Other Shaving Product           2125
64                          Other Sun-Related Product           1564
34        Hair Shampoos with Anti-Dandruff properties           1527
7                                      Baby Wash/Soap           1429
6                                      Baby Skin Care           1382
37                   Hair Tints and Rinses (coloring)           1259
5                                       Baby Shampoos           1241
71                  Products Related to Hair Coloring           1189
32                         Hair Rinses (non-coloring)           1150
78                                    Skin Fresheners           1118
45                                Makeup Preparations           1102
83                                   Suntan Enhancers           1047
65                         Paints (e.g. facial, body)           1001
72                                             Rouges            946
0             Acne Products (making a cosmetic claim)            925
86                           Teeth Whitening Products            889
35                                 Hair Straighteners            883
44                                   Makeup Fixatives            878
53                                Other Baby Products            838
70  Powders (excluding aftershave, baby powder, an...            775
49                                    Nail Decoration            750
57                        Other Hair Coloring Product            698
23                                Feminine Deodorants            618
76          Skin Bleaching (making a cosmetic claim)             587
27                        Hair Color Sprays (aerosol)            547
47                  Mouthwashes and Breath Fresheners            530
43   Lubricants  (e.g. personal, sexual, massage oil)            519
59                               Other Nail Products             502
51                    Nail Polish and Enamel Removers            484
15                                       Depilatories            381
24                            Foot Powders and Sprays            363
14                                  Cuticle Softeners            258
8                            Basecoats and Undercoats            223
26                                      Hair Bleaches            218
31                         Hair Lighteners with Color            120
69                      Permanent Waves and Wave Sets            107
60                         Other Oral Hygiene Product             75
75          Skin Astringent (making a cosmetic claim)             66
16                              Diaper Rash Treatment             12

In [ ]:
alt.Chart()

In [ ]:
thisyear=cdph[cdph["discontinued_year"] == 2025]
thisyear.head()

,Product Id,Company,Brand,Product Name,Variant,Product Discontinued Date,Product Submitted Date,Ingredient Name,Function,Unit of Measure,...,Ingredient Removed Date,UPC,Body Area,Product Category,Product Form,Intended Market,discontinued_year,product_submitted_year,ingredient_submitted_date,ingredient_removed_year
890,119884,Davines S.p.A.,[comfort zone],/ SKIN REGIMEN / cleansing cream,NaN,10/15/2025,12/30/2022,Limonene (1-methyl-4-prop-1-en-2-yl-cyclohexen...,Fragrance,NaN,...,NaN,8004608516866,Face,Skin Cleansers,Cream/Gel/Foam,General population,2025,2022,2023,<NA>
891,119884,Davines S.p.A.,[comfort zone],/ SKIN REGIMEN / cleansing cream,NaN,10/15/2025,12/30/2022,Diethyl phthalate (DEP) 84-66-2,Fragrance,NaN,...,NaN,8004608516866,Face,Skin Cleansers,Cream/Gel/Foam,General population,2025,2022,2022,<NA>
892,119884,Davines S.p.A.,[comfort zone],/ SKIN REGIMEN / cleansing cream,NaN,10/15/2025,12/30/2022,LINALOOL,Fragrance,NaN,...,NaN,8004608516866,Face,Skin Cleansers,Cream/Gel/Foam,General population,2025,2022,2023,<NA>
895,130717,Davines S.p.A.,[comfort zone],/ SKIN REGIMEN / hand cream,NaN,10/15/2025,10/24/2023,Limonene (1-methyl-4-prop-1-en-2-yl-cyclohexen...,Fragrance,NaN,...,NaN,8004608500056,Hands,Other Skin Care Product,Cream/Gel/Foam,General population,2025,2023,2023,<NA>
896,130717,Davines S.p.A.,[comfort zone],/ SKIN REGIMEN / hand cream,NaN,10/15/2025,10/24/2023,LINALOOL,Fragrance,NaN,...,NaN,8004608500056,Hands,Other Skin Care Product,Cream/Gel/Foam,General population,2025,2023,2023,<NA>

need to calculate length of time from product submitted date to product discontinued date

In [ ]:
thisyear.groupby("Product Category").size().rename("product_count").reset_index().sort_values("product_count", ascending = False)

                                     Product Category  product_count
40                            Other Skin Care Product           2658
52        Skin Moisturizers (making a cosmetic claim)           2165
58                      Toilet Water/Eaux de Toilette           1894
5                               Body Washes and Soaps           1680
45                            Perfumes/Eaux de Parfum           1259
12                                       Facial Cream            894
34                                   Other Fragrances            526
26         Lip Color - Lipsticks, Liners, and Pencils            346
35                            Other Hair Care Product            343
48                              Scrubs and Exfoliants            318
36                               Other Makeup Product            285
15                              Foundations and Bases            222
39                              Other Shaving Product            219
25                 Lip Balm (making a cosmetic claim)            219
6                       Bubble and Foam Bath Products            211
50                                     Skin Cleansers            210
13                                       Facial Masks            201
18                      Hair Conditioners (rinse-out)            189
27                                    Lip Gloss/Shine            185
20           Hair Shampoos (making a cosmetic claim)             185
31                             Nail Polish and Enamel            166
33                                Other Bath Products            160
9                                          Eye Shadow            153
38                       Other Personal Care Product             148
43                        Perfumes - Oils and Lotions            137
2   Anti-Wrinkle/Anti-Aging Products (making a cos...            111
46  Powders (excluding aftershave, baby powder, an...            108
4                                            Blushes              88
53               Skin Toner (making a cosmetic claim)             71
7                                             Cologne             64
32                                Nighttime Skin Care             61
41                          Other Sun-Related Product             55
23                              Hair Styling Products             52
10                           Eyeliner/Eyebrow Pencils             51
3                                      Bath Additives             44
1                                 Aftershave Products             39
49            Shaving Cream and other Beard Softeners             37
11                                       Face Powders             34
44                      Perfumes - Solids and Powders             30
30                            Nail Creams and Lotions             30
60                                Underarm Deodorants             26
17                       Hair Conditioners (leave-in)             21
16                        Hair Color Sprays (aerosol)             20
59                                 UV Gel Nail Polish             19
29                  Mouthwashes and Breath Fresheners             18
19                               Hair Dyes and Colors             16
47                                             Rouges             16
14                            Foot Powders and Sprays             16
55               Sunscreen (making a cosmetic claim)              15
54                      Sprays (excluding fragrances)             12
21        Hair Shampoos with Anti-Dandruff properties             11
24                      Hand Cleansers and Sanitizers             10
8                                   Cuticle Softeners             10
56                                   Suntan Enhancers              9
28                           Mascara/Eyelash Products              8
51                                    Skin Fresheners              7
57                            Teeth Cleaning Products              6
42                         Paints (e.g. facial, body)              3
0             Acne Products (making a cosmetic claim)              2
22                                 Hair Straighteners              2
37                               Other Nail Products               1

In [ ]:
thisyear.groupby("Brand").size().rename("product_count").reset_index().sort_values("product_count", ascending = False)

                                              Brand  product_count
85              The Body Shop International Limited           9259
84                                    The Body Shop           1596
41                          Lush Handmade Cosmetics            788
24                                        Gold Bond            639
57                             Neal's Yard Remedies            526
73                                     SERGE LUTENS            407
5                                      BEAUTY RENEW            263
22                                             Glee            185
32                    ISSEY MIYAKE - FUSION D'ISSEY            162
64                             PB Premiere Editions            148
52            NARCISO RODRIGUEZ - MUSC NOIR FOR HER            143
30                    ISSEY MIYAKE - A DROP D'ISSEY            123
9                                   CASHMERE SECRET            119
16                                      Dr. Squatch            105
33                     ISSEY MIYAKE - L'EAU D'ISSEY            100
91                                            Venus             87
10                                    CELIA DE LUXE             82
34          ISSEY MIYAKE - L'EAU D'ISSEY POUR HOMME             70
83                                       Texture ID             66
82                                       Suntegrity             64
15                                  Doctor Eckstein             64
60                                    OPI Gel Color             62
8                                     CASHMERE CARE             60
68                                          Proraso             56
35                                       Jack Black             45
81                                     Summer's Eve             44
18                              European Wax Center             43
78                                     SensatioNail             42
31                    ISSEY MIYAKE - A DROP D´ISSEY             40
61             OPI Infinite Shine Long-Wear Lacquer             39
66                                          PERLIER             37
62                                 OPI Nail Lacquer             35
71                                        RATIONALE             32
75                                 SUSANNE KAUFMANN             25
2                                               Act             24
79                                         Softsoap             23
90                                          Trilogy             23
4                                  Andalou Naturals             23
72                                          RED PRO             20
45                                           MAELYS             19
94                                   [comfort zone]             18
38                                             LILY             18
26          HAIR COMPANY PROFESSIONAL DOUBLE ACTION             16
1                                            AVEENO             15
77                                      Selsun Blue             15
59                                         Nutrafol             15
14                                              DHC             15
54                      NARCISO RODRIGUEZ - NARCISO             14
11                                           CHANEL             14
46                                            MONAT             13
13                        Clairol Natural Instincts             13
21                                         Gillette             13
50                           Merle Norman Cosmetics             12
93                                             YUNI             12
87                                      Three Ships             12
47                                        Manscaped             12
0                                           AG Care             11
53            NARCISO RODRIGUEZ - MUSC NUDE FOR HER             11
69                                            Prose             11
86                                The White Company             11
3                                             Acure             10
74                                    SERGE LUTENS               9
63                            OPI Powder Perfection              7
95                                            got2b              6
58                          News Anchor Thick Hair               6
7                                          CARROTEN              6
27       HAIR COMPANY PROFESSIONAL INIMITABLE STYLE              6
39                                        LUBRIDERM              6
76                                          Sahajan              5
29                               INSTITUT ESTHEDERM              5
65                                         PCA SKIN              5
37                                  Kate Somerville              5
6                                        Beauty Pie              4
80                                       StriVectin              4
49                                     Merle Norman              4
70                                          Queen V              4
89                                     Trader Joe's              3
56                                  Nature's Answer              3
36                            John Masters Naturals              3
51                                   Mineral Fusion              3
67                               Physicians Formula              3
92                             Wella Professionals               3
40                                             Lush              3
88                               Thrive Causemetics              3
42                                         Lush Ltd              2
43                           Lush Manufacturing Ltd              2
25  Gold Bond Ultimate Men's Essentials Body Powder              2
12                                          Cezanne              2
17                                          Eucerin              1
23                                         Glossier              1
19                                          Fing'rs              1
20                               Function of Beauty              1
55                                       NEUTROGENA              1
28                                             ING               1
44                          Lush Manufacturing Ltd.              1
48                                       Maybelline              1